### ISSUE TITLE
搭建好了，小爱回答叫不出。

### ISSUE THREAD

**Issue by ASQ112** [idootop/mi-gpt#101]
搭建好了，小爱回答叫不出。

**Comment by idootop** [comment]
提 issue 前先在 [常见问题](https://github.com/idootop/mi-gpt/blob/main/docs/faq.md) 和已经关闭的 issue 下面找找是否有相似的问题答案。

<img width="1042" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/d92549b5-1afe-4dac-903b-af31d4396bba">
