### ISSUE TITLE
TTS语音切换失败，请大佬帮忙看下

### ISSUE THREAD

**Issue by zxwmail** [idootop/mi-gpt#105]
tts控制台显示错误信息：
/api/tts.mp3?speaker=undefined+text=
本地播放切换都正常，像如下的方式
http://xxx:4321/api/tts.mp3?speaker=BV701_streaming&text=很高兴认识你
感觉就是语音类型没在tts里面设置好，配置文件如下，没找到啥错误
version: "3.8"
services:
  mi-gpt:
    image: idootop/mi-gpt-tts:latest
    ports:
      - "4321:3000"
    environment:
      - TTS_BASE_URL=http://xxx:4321/api
      - TTS_DEFAULT_SPEAKER=BV701_streaming
      - VOLCANO_TTS_APP_ID=xxx
      - VOLCANO_TTS_ACCESS_TOKEN=xxx
      #VOLCANO_TTS_USER_ID=火山引擎账号 ID（可选）
    restart: unless-stopped

**Comment by idootop** [comment]
> 本地播放切换都正常

控制台打印的是每次声音合成的请求日志，不是错误信息。

> TTS语音切换失败

可能是小爱识别出来的文字和实际的音色名称不一致，你可以逐字检查一下控制台输出的音色切换的日志。
