### ISSUE TITLE
为什么进入这个地址总是403错误

### ISSUE THREAD

**Issue by taozhiyuai** [idootop/mi-gpt#106]
为什么进入这个地址https://github.com/idootop/mi-gpt总是403错误

`403
> ERROR CODE: "HTTP 403 Forbidden"

> ERROR DESCRIPTION: "Access Denied. You may be accessing content that violates relevant laws and regulations."

> ERROR POSSIBLY CAUSED BY: [Browse illegal content...]

> If you believe this page is a legitimate page, please send the URL to the webmaster email (kgithub@uoo.im) for manual review.

> SOME PAGES ON THIS SERVER THAT YOU DO HAVE PERMISSION TO ACCESS: [[KGitHub](https://github.com/), [KGitHub Help](https://help.github.com/)]

> KGitHub was originally intended to help the student and developer groups with download acceleration, so please do not abuse it.

> 错误码: "拒绝访问"

> 错误描述: "拒绝访问。你可能正在访问违反相关法律和法规的内容。"

> 可能由以下原因造成的错误: [浏览非法内容...]

> 若您认为本页面为正常页面，请将网址发送至站长邮箱（kgithub@uoo.im）进行人工审核

> 本服务器上的一些页面，你确实有访问的权限: [[KGitHub](https://github.com/), [KGitHub Help](https://help.github.com/)]

> KGitHub初衷为帮助学生与开发者群体进行下载加速，请勿滥用`

**Comment by idootop** [comment]
关掉你用的 KGithub 加速服务

**Comment by taozhiyuai** [comment]
为什么别的项目就可以加速呢

**Comment by idootop** [comment]
不清楚，这你得找 KGithub 他们反馈，本项目不存在违反相关法律和法规的内容，他们误报与本项目无关。
