### ISSUE TITLE
其他大模型的api应该填什么呢？

### ISSUE THREAD

**Issue by NikoYomi** [idootop/mi-gpt#108]
看到示例中apenai是这个，那么豆包之类的其他大模型应该填什么呢？

# OpenAI（也支持通义千问、MoonShot、DeepSeek、gemini等模型）
OPENAI_MODEL=gemini-pro
OPENAI_API_KEY=sk-xxxxxxx
OPENAI_BASE_URL=https://oneapi.url.com/v1

**Comment by idootop** [comment]
具体如何填写，请自行查阅你所用到的大模型服务或 OpenAI API 转换项目（比如：[One API](https://github.com/songquanpeng/one-api) 和 [simple-one-api](https://github.com/fruitbars/simple-one-api)）的官方文档。
