### ISSUE TITLE
_callMiIOT failed, device_list 

### ISSUE THREAD

**Issue by iamsk** [idootop/mi-gpt#109]
❌ _callMiIOT failed {
  isError: true,
  code: 'ECONNREFUSED',
  message: '未知',
  error: {
    request: {
      method: 'post',
      url: 'https://api.io.mi.com/app/home/device_list',
---
调试信息显示MiNA 设备列表返回正常，说明账号密码ok，设备DID也对应，唯一错误是这个。
device_list url 直接浏览器访问可请求，code 2 auth err，请问如何解决？

**Comment by iamsk** [comment]
> 你是在海外服务器上运行的？ get device_list 接口在海外有可能获取不到数据。

深圳本地网络，MAC电脑

**Comment by idootop** [comment]
没什么好的解决方法，试试看换个网络环境，比如手机给电脑开个热点。或者明天再试试看

**Comment by iamsk** [comment]
> 没什么好的解决方法，试试看换个网络环境，比如手机给电脑开个热点。或者明天再试试看

使用python代码重放debug中的请求：{"code":0,"message":"auth err"}

我试试换手机热点
