### ISSUE TITLE
tts报错，日志如下

### ISSUE THREAD

**Issue by binghan2000** [idootop/mi-gpt#110]
下载mp3不好用

🔥 /api/tts.mp3
stdout: 735518c5 ❌ Error code: 3001
stdout: 735518c5 ❌ Error message: {"reqid":"735518c5-45f7-46a2-8ca8-57d4d8d37c51","message":"extract request resource id: get resource id: access denied","code":403,"backend_code":0}
stdout: 735518c5 ❌ Generate failed!
stderr: node:events:510
stderr:     throw err; // Unhandled 'error' event
stderr:     ^
stderr: 
stderr: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('error')
stderr:     at Readable.emit (node:events:508:17)
stderr:     at emitErrorNT (node:internal/streams/destroy:169:8)
stderr:     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
stderr:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
stderr:   code: 'ERR_UNHANDLED_ERROR',
stderr:   context: 'error'
stderr: }
stderr: 
stderr: Node.js v20.14.0

环境：

TTS_DEFAULT_SPEAKER=BV002_streamin
VOLCANO_TTS_APP_ID=XXX
VOLCANO_TTS_ACCESS_TOKEN=XXX
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=20.14.0
YARN_VERSION=1.22.22

**Comment by idootop** [comment]
检查你的 app id 和 token 是否是有效的语音合成凭证，或者配置一下你的 user_id 环境变量试试看。

**Comment by binghan2000** [comment]
看火山，发现没有调用?

**Comment by idootop** [comment]
感觉是你配置的环境变量没生效

**Comment by idootop** [comment]
参考下官方文档的说明：https://www.volcengine.com/docs/6561/79823

<img width="1191" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/ed54d35d-31c6-4440-b3ea-23e088f59d6b">

**Comment by idootop** [comment]
@binghan2000  检查下你开通的服务是不是【语音合成】，以及是否开启了【试用】音色。

![image](https://github.com/idootop/mi-gpt/assets/35302658/87afdfc0-32f1-4f3d-948f-327dfbc0fa24)

检查你的语音合成服务的 cluster ID 是否为`volcano_tts`

![image](https://github.com/idootop/mi-gpt/assets/35302658/083823ef-7723-4f29-a9af-10a4c9072209)
