### ISSUE TITLE
提示授权验证账号，打开网站授权过之后，1个小时后重试还是提示这个

### ISSUE THREAD

**Issue by caopengfei** [idootop/mi-gpt#113]
使用docker方式部署在阿里云的centos7上，启动后查看日志提示“触发小米账号异地登录安全验证机制，请在浏览器打开以下链接，并按照网页提示授权验证账号”，复制地址后，在本地电脑上打开网页，按网页上的提示使用其他设备的方式授权了，网页显示“ok”。
然后等待了1个小时，docker restart重启容器后，还是提示“触发小米账号异地登录安全验证机制，请在浏览器打开以下链接，并按照网页提示授权验证账号”
![image](https://github.com/idootop/mi-gpt/assets/10126284/58e622dc-ca26-46e3-aabc-57d6725562bf)

**Comment by idootop** [comment]
继续等待，一般要等好久，晚上或者明天再试试看。
