### ISSUE TITLE
删除“对话记忆”

### ISSUE THREAD

**Issue by lmk123** [idootop/mi-gpt#114]
我发现有时候我改了配置文件之后，机器人还是带着之前的”对话记忆”，我想要删掉记忆，让机器人完全重新开始，是不是只要删除 `.bot.json` 和 `.mi.json` 就可以了？

**Comment by idootop** [comment]
主要是这几个文件：
<img width="780" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/e132c7fe-5466-488d-9d2d-83895e225e3a">

会话记录存储在本地 db 内，在初始化 db 时会创建当前的 bot 和用户记录，并将 id 记录到 `.bot.json` 文件中作为索引（为将来支持多用户做准备）。

理论上只删除 `.bot.json` 也可以实现“删除记忆”的效果，相当于重新创建了用户记录，但历史用户的会话消息还在。

要想完整清除数据，建议一并删除上面的那几个文件。

**Comment by lmk123** [comment]
我现在就是想要实现多个机器人的功能 :joy:

我开发了一个命令行工具，这个命令行工具可以通过读取一个配置文件 migpt.json 来跑 MiGPT，然后我现在想实现这么一个功能：每个 migpt.json 对应一个机器人。

比如以下文件目录：

```
~/Desktop/
    ├─ robot_张三/
    │    ├─ migpt.json
    │    ├─ .bot.json
    │    ├─ .mi.json
    ├─ robot_李四/
    │    ├─ migpt.json
    │    ├─ .bot.json
    │    ├─ .mi.json
```

按照我的理解：

1. 虽然张三和李四这两个机器人的对话记录都存储在 `prisma/app.db` 当中，但它们两个的记忆相互之间是完全独立的，它们的“人设”相互之间不会受到影响。
2. 如果我把 `prisma/app.db` 删除了，那就意味着 `robot_张三` 和 `robot_李四` 这两个机器人的记忆全都没了。
3. 如果以上两点成立，那么当我想要删除 `robot_张三` 这个机器人的时候，我只能删除 `robot_张三` 这个文件夹，因为如果我把 `prisma/app.db` 也删除了，那李四也会受到影响。

我的理解正确吗 :joy:

**Comment by idootop** [comment]
额，是的。我建议 db 就别删了，把创建时的 `.bot.json` 文件保存起来，切换账号的时候再恢复过来

**Comment by idootop** [comment]
@lmk123  不过注意这里的多账号应该以设备 did 作为唯一标识，同一个设备只能同时绑定一个 MiGPT 实例，不然会产生冲突和不可预期的行为。

**Comment by lmk123** [comment]
也就是说，如果我只有一台音箱的话，没有任何问题。

如果我有两台音箱 A 和 B，那么我要确保在音箱 A 创建的机器人，以后也只能运行在音箱 A 上，否则就会出问题，对吗？

**Comment by idootop** [comment]
非也。

不是`在音箱 A 创建的机器人，以后也只能运行在音箱 A 上`

而是一个音箱在同一时刻只应该运行一个机器人 A

如果机器人 A 和 B 同时绑定并运行在音箱 1 上，那么就会产生冲突。（机器人 A 和 B同时在拉取处理来自音箱 1 的消息）

**Comment by lmk123** [comment]
感谢答疑解惑，我明白了
