### ISSUE TITLE
获取 Mi Service Token失败 超时

### ISSUE THREAD

**Issue by GitSarp** [idootop/mi-gpt#116]
采用docker compose部署， 设备为“小爱音箱 万能遥控板”

token获取超时(oracle日本的服务器)，请问是否可以通过变量或其他方式增加超时时间？导致后面输出找不到设备（did开启了debug之后找到应该不会错）

```
  mi-gpt  | ❌ 获取 Mi Service Token 失败 {
  mi-gpt  |   isError: true,
  mi-gpt  |   code: 'ECONNABORTED',
  mi-gpt  |   message: 'timeout of 3000ms exceeded',
  mi-gpt  |   error: {
  mi-gpt  |     request: {
  mi-gpt  |       method: 'get',
  mi-gpt  |       url: 'https://api2.mina.mi.com/sts?d=android_xxxxxxxxxxxxxx',
  mi-gpt  |       headers: '{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip, deflate","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 10; RMX2111 Build/QP1A.190711.020) APP/xiaomi.mico APPV/2004040 MK/Uk1YMjExMQ== PassportSDK/3.8.3 passport-ui/3.8.3"}',
  mi-gpt  |       data: '{}'
  mi-gpt  |     },
  mi-gpt  |     response: undefined
  mi-gpt  |   }
  mi-gpt  | }
  mi-gpt  | ❌ 找不到设备：xxxxx
```

**Comment by GitSarp** [comment]
奇怪的是，在开启debug和trace之后，token获取超时失败，为什么还能打印出设备列表 ><    这个不依赖token吗

**Comment by idootop** [comment]
> 请问是否可以通过变量或其他方式增加超时时间？

有的，只是没在文档中对外说明

```js
// .migpt.js
export default {
    speaker:{
        timeout: 10 * 1000, // 超时时长，单位毫秒
        // ...
    }
}
```

> 奇怪的是，在开启debug和trace之后，token获取超时失败，为什么还能打印出设备列表 >< 这个不依赖token吗

一共需要登录两次：Mina 和 MIoT，应该是你其中一个登录成功获取到设备列表了。

**Comment by In2013** [comment]
> > 请问是否可以通过变量或其他方式增加超时时间？
> 
> 有的，只是没在文档中对外说明
> 
> // .migpt.js
> export default {
>     speaker:{
>         timeout: 10 * 1000, // 超时时长，单位毫秒
>         // ...
>     }
> }
> > 奇怪的是，在开启debug和trace之后，token获取超时失败，为什么还能打印出设备列表 >< 这个不依赖token吗
> 
> 一共需要登录两次：Mina 和 MIoT，应该是你其中一个登录成功获取到设备列表了。

docker容器中，这个文件在哪啊
