### ISSUE TITLE
只能召唤出傻妞，召唤出来就不能对话了，小爱音箱Play L05B 

### ISSUE THREAD

**Issue by xiaoshuai220** [idootop/mi-gpt#117]
![1718984118658(1)](https://github.com/idootop/mi-gpt/assets/53173115/9986b2e5-8464-4da7-a88a-3f5b68c684c6)

**Comment by idootop** [comment]
把配置文件里的 streamResponse 改成 false 然后重启项目。

你的这个型号不支持连续对话（streamResponse）

<img width="930" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/b906ea82-059a-4991-b850-780c3562e348">

**Comment by xiaoshuai220** [comment]
不符合连续对话，我怎么使用 呢？ 每个对话都需要先召唤傻妞吗？

**Comment by idootop** [comment]
不支持连续对话的机型，只能每次向AI提问前带上“小爱同学”和你设置的callAIKeywords。比如：
- 小爱同学，请问 xxxx
- 小爱同学，你 xxxx

**Comment by xiaoshuai220** [comment]
> 不支持连续对话的机型，只能每次向AI提问前带上“小爱同学”和你设置的callAIKeywords。比如：
> 
> * 小爱同学，请问 xxxx
> * 小爱同学，你 xxxx

好的，感谢！
