### ISSUE TITLE
请问一下, 自定义 TTS 里面,. 那个更像阳光甜妹呀

### ISSUE THREAD

**Issue by eachann1024** [idootop/mi-gpt#118]
台湾甜妹还是不如阳光甜妹啊

**Comment by idootop** [comment]
哪来的阳光甜妹，火山有这款音色？

**Comment by eachann1024** [comment]
> 哪来的阳光甜妹，火山有这款音色？

豆包里面有呀, 太爱了 
![image](https://github.com/idootop/mi-gpt/assets/43348055/62fe9d92-36aa-49f9-aac0-bbb5bdf6c38f)

**Comment by idootop** [comment]
可以，没毛病，我喜欢「文静毛毛」哈哈。

不过有一个曲线救国的方法，火山 TTS 有克隆音色的服务，可以克隆这个阳光甜妹的音色。
