### ISSUE TITLE
小爱音箱 pro, 召唤 XX 之后, 小爱会回答一半,接着中断, 第三方TTS才开始中途插入, 好突兀呀

### ISSUE THREAD

**Issue by eachann1024** [idootop/mi-gpt#119]
有没有啥妙招能让小爱乖乖闭嘴，专门等着第三方来应答呢？

另外呀，火山 TTS 回答一句话的时候，在逗号之类的地方都不停顿一下，这种状况着实怪异得很哟！

**Comment by idootop** [comment]
> 有没有啥妙招能让小爱乖乖闭嘴，专门等着第三方来应答呢？

无解，唯有刷机。

> 火山 TTS 回答一句话的时候，在逗号之类的地方都不停顿一下

一般的 TTS 服务都会存在着问题，你可以自己改代码换成别家做的好的 TTS 服务。
