### ISSUE TITLE
一直无法登陆成功

### ISSUE THREAD

**Issue by mxyblog** [idootop/mi-gpt#121]
日志消息：
🐛 注意：授权成功后，大约需要等待 1 个小时左右账号信息才会更新，请在更新后再尝试重新登录。
❌ 小米账号登录失败 &&&START&&&。。。。。。这里省略一些。。。
2024/06/22 09:53:38 Speaker ❌ 初始化 Mi Services 失败
2024/06/22 09:53:38 database ❌ Error: ❌ Assertion failed

试了很多遍了 等了好多个小时了 本地访问授权地址授权后提示ok 重启docker和容器还是不行

是不是需要在服务器上访问那个授权地址啊 可是linux的怎么弄。

大佬们指教下

**Comment by idootop** [comment]
可以在本地运行 `MiGPT` 登录成功后把 `.mi.json` 文件导出，
然后挂载到服务器上（对应是放在容器的 `/app/.mi.json` 路径下）即可解决此问题。相关 issue：https://github.com/idootop/mi-gpt/issues/22#issuecomment-2148956802
```shell
docker run -d  --env-file $(pwd)/.env \
    -v $(pwd)/.migpt.js:/app/.migpt.js \
    -v $(pwd)/.mi.json:/app/.mi.json \
    idootop/mi-gpt:latest
```
