### ISSUE TITLE
默认音色怎么设置？参数写了，感觉没用

### ISSUE THREAD

**Issue by binghan2000** [idootop/mi-gpt#122]
设置里面：TTS_DEFAULT_SPEAKER=BV002_streaming

但是实际调用时，就是就默认语音

/api/tts.mp3?speaker=undefined+text=你好，我是雨果

这个怎么处理？

**Comment by idootop** [comment]
浏览器访问 `[你的 ip+端口]/api/tts.mp3?speaker=BV002_streaming&text=你好，我是雨果`，查看音色是否生效。

如果音色正确，说明你的环境变量未配置生效。

**Comment by binghan2000** [comment]
检查了好几遍，设置没有问题，但是就是不生效，如何处理？
