### ISSUE TITLE
安装时出现error

### ISSUE THREAD

**Issue by HMSXEF** [idootop/mi-gpt#129]
![Uploading 微信截图_20240625111856.png…]()

**Comment by idootop** [comment]
你的错误截图没传上来，重新上传一下。

**Comment by HMSXEF** [comment]
![微信截图_20240625111856](https://github.com/idootop/mi-gpt/assets/141598320/ba9195fb-0e24-4c9b-9bf5-6ae288cff9e4)

**Comment by HMSXEF** [comment]
抱歉，可能当时没有传上

**Comment by idootop** [comment]
看日志是你的网络问题，换个网络环境或节点试试看。

**Comment by HMSXEF** [comment]
> 看日志是你的网络问题，换个网络环境或节点试试看。

是需要更换到国外节点吗

**Comment by idootop** [comment]
你没把日志截完整，不确定是那个链接访问失败。

如果你用的是 OpenAI 的 LLM，则需要使用海外网络才能访问。
