### ISSUE TITLE
给依赖 mi-gpt 的项目打包 armv7l 镜像时失败

### ISSUE THREAD

**Issue by lmk123** [idootop/mi-gpt#130]
重现问题的 repo 以及报错信息：

https://github.com/lmk123/migpt-server-docker-issue

但是在 amd64 和 arm64 里是正常的，Dockerfile 见 https://github.com/lmk123/migpt-cli/blob/main/docker/Dockerfile

我看到你的 Dockerfile 里有一项 `RUN [ ! "$TARGETARCH" = "arm" ] && rm -rf ./prisma/engines || true` 可能跟这个问题有关，但是没理解这句命令是干嘛的 :joy:

**Comment by idootop** [comment]
删除非 armv7 arch 下的内置 prisma armv7 engines 的（只在arm v7下有用），你的问题应该与这个命令无关。

**Comment by idootop** [comment]
你把 engines 文件先放到 `MiGPT` 原始的 node_modules 目录下面试试看

```shell
/usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/prisma/engines/
```

> PS: 不晓得在 npm install 的时候会不会覆盖掉

![image](https://github.com/idootop/mi-gpt/assets/35302658/86255570-b6cc-47a1-98c9-37fd66cb34ed)

**Comment by idootop** [comment]
另外，我在本地构建的 prisma engines 和 docker 都是针对 `linux/arm32/v7` arch 的，

不晓得和你选择的 `linux/armv7l` 是不是一个东西

![image](https://github.com/idootop/mi-gpt/assets/35302658/5a59350f-11ca-4e8e-ac82-9e7c8aa61779)

**Comment by lmk123** [comment]
我先是尝试把 platform 改成了 `linux/arm32/v7`，会报同样的错误

然后在 Dockerfile 里加了一条 `COPY ./armv7l /usr/local/lib/node_modules/migpt-server/node_modules/.prisma/client`，也还是报了同样的错

然后我尝试把二进制文件改个名：

```
query-engine-linux-arm
libquery_engine-linux-arm.so.node
schema-engine-linux-arm
```

还是同样的报错 :joy:

再尝试把 platform 改成 `linux/arm/v7`，把二进制文件改名为：

```
# 因为我在控制台看 prisma 检测出来的架构是 armv7l 所以就试试改成这个
query-engine-linux-armv7l
libquery_engine-linux-armv7l.so.node
schema-engine-linux-armv7l
```

也还是报同样的错误 :joy:

**Comment by idootop** [comment]
放弃 armv7 吧😂

**Comment by lmk123** [comment]
真肝不动了，放弃了 :joy:

**Comment by idootop** [comment]
根据我的测试，我在 example 分支下，按照 mi-gpt 的 dockerfile 配置对应 engines 文件和环境变量，然后在项目根目录执行 `npm install && npm run start` 可正常构建和运行 armv7 的镜像。

目测可能全局/嵌套安装 mi-gpt 到项目，在 armv7 下，可能哪里有些不太支持。

**Comment by lmk123** [comment]
那我也直接基于源码来打包试试
