### ISSUE TITLE
召唤出错 小爱音箱也不发声 看log是配额不足 难道只能chatgpt的付费版本才能使用么？

### ISSUE THREAD

**Issue by jerryfang527** [idootop/mi-gpt#135]
2024/06/28 04:27:14 Speaker 🔊 请稍等
2024/06/28 04:27:20 Open AI ❌ LLM 响应异常 RateLimitError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at APIError.generate (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/error.js:63:20)
    at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (/app/dist/index.cjs:1238:20) {
  status: 429,

  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '89aaec7c7cd94a4e-TPE',
    connection: 'keep-alive',
    'content-length': '337',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 28 Jun 2024 04:27:20 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=aPTBvVsj3P9QpMSM6QAygxbQbzK9jrCno77PtrILzCs-1719548840-1.0.1.1-fmO4X31YnuPJEbxCvQ.Cgtkmhs4Acf._qhzt3G8biotDS_mk8ipORuXucuQxsL6hys7rq7sd5ciCDuuobMn25g; path=/; expires=Fri, 28-Jun-24 04:57:20 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=IEgwX9Tbi_9X8nJ6A5dWz2nqdFLTlmXyKnpF3BZ8HkM-1719548840601-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    vary: 'Origin',
    'x-request-id': 'req_4e973900894b43b9be43743dfc483e52'
  },
  request_id: 'req_4e973900894b43b9be43743dfc483e52',
  error: {
    message: 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
    type: 'insufficient_quota',
    param: null,
    code: 'insufficient_quota'
  },
  code: 'insufficient_quota',
  param: null,
  type: 'insufficient_quota'
}
2024/06/28 04:27:20 Speaker 🔊 啊哦，出错了，请稍后再试吧！
2024/06/28 04:27:54 Speaker 🔊 大白已退出
2024/06/28 07:57:41 Speaker 🔥 召唤大白
2024/06/28 07:57:42 Speaker 🔊 你好，我是大白，很高兴认识你
2024/06/28 07:58:15 Speaker 🔊 大白已退出
2024/06/28 11:56:57 Speaker 🔥 召唤大白
2024/06/28 11:56:57 Speaker 🔊 你好，我是大白，很高兴认识你
2024/06/28 11:57:30 Speaker 🔊 大白已退出
2024/06/28 12:45:57 Speaker 🔥 明天什么天气
2024/06/28 12:46:13 Speaker 🔥 召唤大白
2024/06/28 12:46:13 Speaker 🔊 你好，我是大白，很高兴认识你
2024/06/28 12:46:21 Speaker 🔥 召唤大白
2024/06/28 12:46:21 Speaker 🔊 请稍等
2024/06/28 12:46:29 Open AI ❌ LLM 响应异常 RateLimitError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at APIError.generate (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/error.js:63:20)
    at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.51.0/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (/app/dist/index.cjs:1238:20) {
  status: 429,

  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '89adc7a6f8a84a1c-TPE',
    connection: 'keep-alive',
    'content-length': '337',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 28 Jun 2024 12:46:29 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=lilpNcBqDzIfY5Jo72SQU8GT2AYb2_KtB37EJwRahdY-1719578789-1.0.1.1-f6_swm.u_1mutltdSMcq8i0nzMHy9ErSzw1KextxtJOX_YGAX_lQ9dHAy5t12x3StElmS2SEk562XC399tiy1Q; path=/; expires=Fri, 28-Jun-24 13:16:29 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=rqyBiPI7oElPlUzGv1OmKHyVdy16S9HueuB0HBJfV.g-1719578789165-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    vary: 'Origin',
    'x-request-id': 'req_2be451edfbf842c1b0d5000679ab5463'
  },
  request_id: 'req_2be451edfbf842c1b0d5000679ab5463',
  error: {
    message: 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
    type: 'insufficient_quota',
    param: null,
    code: 'insufficient_quota'
  },
  code: 'insufficient_quota',
  param: null,
  type: 'insufficient_quota'

**Comment by idootop** [comment]
不充钱用不了。可以看看国内有免费额度的大模型。
