### ISSUE TITLE
好像是找不到镜像idootop/mi-gpt:latest

### ISSUE THREAD

**Issue by Haiyang-Zhou** [idootop/mi-gpt#136]
C:\Users\25739>docker run --env-file "E:\快速访问\桌面\pycharm20\pythonProject\mi-gpt-main\.env" -v "E:\快速访问\桌面\pycharm20\pythonProject\mi-gpt-main\.migpt.js:/app/.migpt.js" idootop/mi-gpt:latest
Unable to find image 'idootop/mi-gpt:latest' locally
latest: Pulling from idootop/mi-gpt
ec99f8b99825: Retrying in 1 second
826542d541ab: Retrying in 1 second
dffcc26d5732: Retrying in 1 second
db472a6f05b5: Waiting
1b7d295ce070: Waiting
297743dd96bf: Waiting
25fc47588c9a: Waiting
ce6325f46117: Waiting
385e52814a0e: Waiting
bef69d97d972: Waiting

**Comment by idootop** [comment]
网络问题，国内直接 pull docker 镜像最近比较困难，自行百度如何处理。
