### ISSUE TITLE
小米账号异地登录安全验证机制 验证后依然登录不了

### ISSUE THREAD

**Issue by PunkSarich** [idootop/mi-gpt#138]
使用docker启动，参数设置好后启动，日志提示去小米账号异地登录安全验证链接
点进链接，发消息到自己手机上了，填写验证码后
![image](https://github.com/idootop/mi-gpt/assets/63685727/f095a4cc-a982-4fab-8629-af7c4c587aff)

想问下这是小米自身的问题嘛？遇到这种情况怎么办？

**Comment by idootop** [comment]
正常现象，等待一两个小时之后，尝试重启重新登录即可。
如果还是提示登录失败，请看FAQ中其他的解法。
