### ISSUE TITLE
调用mi-gpt-tts(火山引擎)，单独内网测试tts都没问题，但是mi-git无法调用没有声音

### ISSUE THREAD

**Issue by hardy110** [idootop/mi-gpt#139]
原issues是https://github.com/idootop/mi-gpt/issues/107 
我后面遇到同样问题，估计是音响型号有关系，我的是L05B，我自己内网测试tts都没问题，但是就是调用会报unWakeUp，mi-gpt-tts那边没有请求
2024/07/01 16:13:40 Speaker  设备信息： {
    "name": "小爱音箱Play",
    "desc": "设备在线 ",
    "model": "xiaomi.wifispeaker.l05b",
    "rom": "1.0.2"
}
2024/07/01 16:13:40 Speaker ✅ 服务已启动...
2024/07/01 16:13:47 Speaker  你是谁
2024/07/01 16:13:48 Speaker  让我先想想
2024/07/01 16:13:48 Speaker  unWakeUp
2024/07/01 16:13:56 Open AI ✅ Answer: 我是ChatGPT，一个基于人工智能的语言模型，能够回答各种问题和进行对话。有什么我可以帮助你的吗？
2024/07/01 16:13:56 Speaker  unWakeUp
2024/07/01 16:13:56 Speaker  我是ChatGPT，一个基于人工智能的语言模型，能够回答各种问题和进行对话。有什么我可以帮助你的吗？
2024/07/01 16:13:56 Speaker  unWakeUp

**Comment by hardy110** [comment]
估计真的是型号问题，我用另一个项目xiaogpt，也配置第三方tts也没有成功，看来只有小米音响pro能调用第三方tts，其他人测试过吗？

**Comment by idootop** [comment]
跟机型有关，和 unwakeup 没太大关系，更像是播放指令下发到你的音箱之后，小爱音箱没有去访问对应的音频链接。
可以关注下这个 issue 的相关进展：https://github.com/idootop/mi-gpt/issues/134

Anyway，建议使用小爱音箱Pro运行此项目，其他型号的音箱我这边没有，适配的可能不那么全面。
不过之前也有人反馈，自己是小爱音箱Pro也有这个问题，不过我这边无法复现。🤷

**Comment by idootop** [comment]
我这边测试的旧版的小爱音箱Play也可以，就是这个型号反应太迟钝了，不推荐使用。

**Comment by hardy110** [comment]
好的，谢谢折腾一晚上了，xiaomi的原声tts经常不回答，折腾一晚上第三方tts都没搞定，今天也算有个暂时的结论了。

**Comment by hardy110** [comment]
> 我这边测试的旧版的小爱音箱Play也可以，就是这个型号反应太迟钝了，不推荐使用。

群主，是L05B，要不你贴下配置，我测试下？虽然我感觉可能是型号问题，跟我配置没啥关系。

**Comment by idootop** [comment]
跟你型号不一样，我手上这台是 LX05

![image](https://github.com/idootop/mi-gpt/assets/35302658/7da0fbf5-28e5-435d-a622-f3cd430fea30)

**Comment by hardy110** [comment]
好的，谢谢，看能不能蹲个一起研究搞定的？我看xiaomusic好像L05B可以放音乐的，应该可以访问网络文件，mi-gpt有日志看能否下发吗？现在就卡在是不是下发过去了，还是访问不到，如果是型号导致访问不到，那就真的死心了。

**Comment by idootop** [comment]
你如果熟悉nodejs的话，可以用这个项目测试下，能否正常播放：https://github.com/idootop/mi-service-lite

```js
import { getMiNA } from "mi-service-lite";

async function main() {
  const MiNA = await getMiNA({
    userId: '小米账号', 
    password: '密码'
    did: '小爱音箱名称', 
  });
   await MiNA!.play({
       url: '你的音频链接'
   });
}

main();
``

**Comment by hardy110** [comment]
好的 谢谢

**Comment by hardy110** [comment]
nodejs 不是很熟，我用一个开源的python项目，https://github.com/yihong0618/MiService?tab=readme-ov-file   这个项目可以调用tts，能播放的。
root@k8s-test:~/MiService# ./micli.py play "http://192.168.X.X:4321/api/tts.mp3"  就能听到

**Comment by hardy110** [comment]
我估计可能整个下发不一样，我研究研究，不过nodejs不是很熟

**Comment by idootop** [comment]
那你这个型号应该还有希望，有时间可以一起联调一下。

**Comment by hardy110** [comment]
> 那你这个型号应该还有希望，有时间可以一起联调一下。

还是要靠大佬你，nodejs实在是不熟悉，大佬有空的时候可以研究下。不过问题大概是这个。哈哈哈

**Comment by haimander** [comment]
我是的redmi小爱音响，tts调用正常，但就是不说话

**Comment by wide-k** [comment]
> 跟你型号不一样，我手上这台是 LX05
> 
> ![image](https://private-user-images.githubusercontent.com/35302658/344618113-7da0fbf5-28e5-435d-a622-f3cd430fea30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTgxNDYsIm5iZiI6MTcyMTI5Nzg0NiwicGF0aCI6Ii8zNTMwMjY1OC8zNDQ2MTgxMTMtN2RhMGZiZjUtMjhlNS00MzVkLWE2MjItZjNjZDQzMGZlYTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwMTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzNjZmM5NjJhNGFmNTY1MTAzZGVhZmZkNGM1NjAzM2I3NzU2MTQ1NTEyYzkxMTUzNGQwMDYzNDZhY2ExMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.69Bq3u1zQajUBTyJjIpZpt6sVwoUBUO-yhLKffQuFyA)

我手里的也是小米音箱Play2019版（LX05）。本地docker部署tts，服务端和音箱连接同一局域网，检查过tts的url能用（SECRET_PATH一致，pc网页测试tts.mp3有语音生成并且tts控制台有返回，手机在同一局域网下单独连url时tts控制台同样有返回）。

migpt控制台是正常的，文本的来回对答都没问题。唯一有问题的就是音箱没有播报声音，而且tts控制台里没有体现有关音箱tts请求的返回值。

请问有可能会是什么问题？

**Comment by idootop** [comment]
@wide-k 型号相同（LX05）但是没有播放成功的话，更有可能是因为你的小爱音箱到你部署的 TTS 服务之间的网络链接存在问题，你可以再仔细排查下。

**Comment by vicjl** [comment]
> > 跟你型号不一样，我手上这台是 LX05
> > ![image](https://private-user-images.githubusercontent.com/35302658/344618113-7da0fbf5-28e5-435d-a622-f3cd430fea30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDE3MjAsIm5iZiI6MTcyMTMwMTQyMCwicGF0aCI6Ii8zNTMwMjY1OC8zNDQ2MTgxMTMtN2RhMGZiZjUtMjhlNS00MzVkLWE2MjItZjNjZDQzMGZlYTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTUyMjUyYzg0ODkzYmE5MTI3YTAwZWJiYWRkMDFjNWJjMzhkY2JjZTQzM2MxZDRiZjMzYjFkMjZhYmViZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K6qYQXfz2fjM5YY8f7ppPdTeETnF5u2UyG6T6ipvIHs)
> 
> 我手里的也是小米音箱Play2019版（LX05）。本地docker部署tts，服务端和音箱连接同一局域网，检查过tts的url能用（SECRET_PATH一致，pc网页测试tts.mp3有语音生成并且tts控制台有返回，手机在同一局域网下单独连url时tts控制台同样有返回）。
> 
> migpt控制台是正常的，文本的来回对答都没问题。唯一有问题的就是音箱没有播报声音，而且tts控制台里没有体现有关音箱tts请求的返回值。
> 
> 请问有可能会是什么问题？

同样问题，我是L05B，默认音色OK，切换tts失败，电脑、手机访问tts.mp3有音频返回。tts控制台无反应，migpt控制台正常显示但是没发声，我用的是局域网的ip地址

**Comment by zqzhan2024** [comment]
各位，我也遇到这个问题，在mi-gpt配置TTS_BASE_URL，将 TTS_BASE_URL 中的 localhost 替换为运行 TTS 服务的设备的局域网 IP 地址。

废了半天劲才发现是这个问题。

**Comment by hiiseeu** [comment]
我小爱音箱 pro 也是没声音, tts和 mi-gpt 都在同一台电脑,最后把TTS_BASE_URL换成局域网ip 地址解决了, 127.0.0.1 和localhost都不行,真是个奇奇怪怪的 bug

**Comment by idootop** [comment]
> 我小爱音箱 pro 也是没声音, tts和 mi-gpt 都在同一台电脑,最后把TTS_BASE_URL换成局域网ip 地址解决了, 127.0.0.1 和localhost都不行,真是个奇奇怪怪的 bug

音频链接是从小爱音箱上去访问的，你填  127.0.0.1 和 localhost 自然访问不到你的局域网设备。
