### ISSUE TITLE
OpenAi回答过长的情况下小爱音箱没有读完整

### ISSUE THREAD

**Issue by lyddias** [idootop/mi-gpt#14]

**Comment by lyddias** [comment]
如果OpenAi回答过长，程序自动会将回答拆分成多个，但小爱音箱还没有读完第一个就开始读第二个了，后边的几条回答都是如此，每条回答都无法读完整，这个拆分功能是不是叫流式响应？

**Comment by lyddias** [comment]
如果openai回答不长，程序就不会拆分，小爱音箱只读1条的情况下就能将句子读完。

**Comment by idootop** [comment]
检查一下你用的是不是最新的 2.0.0 版本，新版本有尝试修复这个问题。
如果你用的已经是 2.0.0 版本，请发下你的设备型号和配置信息。

**Comment by lyddias** [comment]
是最新2.0.0版本，型号L05C，录音记录链接：https://pan.baidu.com/s/1yOhf3MPLXnAKOpV9RI1lsQ 
提取码：mafd

<img width="1430" alt="image" src="https://github.com/idootop/mi-gpt/assets/11193951/8aa043a6-469e-46a7-a14d-c2645fa4af92">

**Comment by idootop** [comment]
问题在于现在 TTS 是按句分段去读的，要等到第一句播放完再播放下一句，所以在下发 TTS 指令之后，会去检测当前设备的播放状态，此时拿到状态可能不是最新的，就会过早地判断为当前句子已经播放结束了。

**Comment by lyddias** [comment]
那程序是否可以不对句子进行拆分

**Comment by idootop** [comment]
拆分是必要的：
1. 小米音箱 TTS 一次的文字长度有上限。
2. 等待 AI 返回全部回答再播放，会拉长每次提问的等待时间。
3. 如果回复中存在敏感词，整个回答都会被驳回。

**Comment by idootop** [comment]
问题的关键在于，如何控制检测 TTS 播放是否开始/结束的时机，下个版本我再尝试优化下。

**Comment by idootop** [comment]
@lyddias 我本地用小爱音箱 Pro 测试的，效果很完美。手边没你那个型号的设备，如果你现在方便的话，可以到我[微信公众号](https://del.wang/about)后台私聊联调下。

**Comment by idootop** [comment]
我在 v2.0.1 版本添加了一个 debug 开关，你把它打开看下日志。
```js
// .migpt.js
export default {
  speaker: {
    // 打开调试开关
    debug: true,
    // ... 
  },
};

```

**Comment by lyddias** [comment]
<img width="1433" alt="1717312976567" src="https://github.com/idootop/mi-gpt/assets/11193951/34380451-cdcb-42db-be86-0398c1cb563c">
一直在打印Speaker undefined，没有其他日志

**Comment by idootop** [comment]
@lyddias  更新到 v2.1.0 版本，试试看。
```js
// .migpt.js
export default {
  speaker: {
    // 打开调试开关
    debug: true,
    // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
    playingCommand: [3, 1, 1], // L05C
    // ... 
  },
};

```

**Comment by lyddias** [comment]
更新加了配置后仍显示 undefined
<img width="935" alt="696a075a09fad4fee72fd1124710a91" src="https://github.com/idootop/mi-gpt/assets/11193951/244faf90-6b89-4d72-9109-a2c42fa18940">

![image](https://github.com/idootop/mi-gpt/assets/11193951/c60faf88-b31c-4ee3-bc16-1789619d85b7)

**Comment by idootop** [comment]
经过测试，当前音箱型号通过 MioT 接口（L05C,3,1）获取设备播放状态值时，返回错误 code 如下：
```shell
-704220043  Property value invalid
```
此问题源自小米 MioT 后端处理状态值异常，需要等待小米官方修复后才能继续使用。

**Comment by lyddias** [comment]
好的，感谢！

**Comment by idootop** [comment]
总结：小米音箱 Play 增强版 (L05C) 大部分 MioT 接口都无法调用，要想体验更完整的智能家居生态，慎入。相关 issue：
- https://github.com/al-one/hass-xiaomi-miot/issues/159
- https://github.com/al-one/hass-xiaomi-miot/issues/994
- https://web.vip.miui.com/page/info/mio/mio/detail?app_version=dev.20051&postId=38477486

**Comment by idootop** [comment]
> 那程序是否可以不对回答进行拆分

@lyddias [v3.0.0](https://github.com/idootop/mi-gpt/releases/tag/v3.0.0) 版本已发布，添加了流式响应开关。对于获取播放状态为空的小爱音箱设备，请在 `.migpt.js` 配置文件中关闭 `streamResponse` 选项，即可保证小爱的回复是完整的句子。

```js
export default {
  speaker: {
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: false,
    // ...
  },
};
```

**Comment by aieejk** [comment]
报了一个错误
![image](https://github.com/idootop/mi-gpt/assets/171260721/22cfc7d6-2603-453a-8ab1-744af6917bef)

**Comment by izumidonabe** [comment]
注：我的小米音箱 Play  (L05B) 也遇到了这个问题，应该是整个L05系列都有类似的问题

**Comment by wangqiang1988** [comment]
确实能回答完整了，但是每次问问题的时候，小爱同学会先说几个字，是设置问题吗

**Comment by idootop** [comment]
@wangqiang1988  与本项目的实现原理有关，目前无法完美避免出现这个问题。具体可以查看此处的说明：https://github.com/idootop/mi-gpt

**Comment by idootop** [comment]
> 有没有可能唤醒小爱的时候，直接mute掉小爱，然后等tts ai的答案后再开启呢

默认就是这种运行方式呢。问题在于小爱音箱上报状态到云端存在延迟。从服务端拉取到小爱消息的时候，小爱已经开始在说话了，这个时候再 mute 小爱已经能够察觉到了。

**Comment by kenliy** [comment]
mac 系统 无法修改文件名为.env文件 怎么办

**Comment by idootop** [comment]
@kenliy 把 docker 启动参数里的文件路径改成你当前的env文件名也 OK。但在 mac 里是可以正常重命名的，估计是你操作不大对。

**Comment by fky2015** [comment]
FYI，在老版本的小爱音箱 Pro 上也遇到了同样的问题。看起来同样是因为“小米服务端没有返回正常的响应状态”导致的。

![image](https://github.com/idootop/mi-gpt/assets/16451516/f052a430-d494-4430-b032-aa10d9d9404d)

**Comment by idootop** [comment]
看看小爱音箱有没有新固件可以升级

**Comment by idootop** [comment]
我现在的设备固件版本是 1.88

**Comment by fky2015** [comment]
> 看看小爱音箱有没有新固件可以升级

有的，但是升级后问题依然存在。
![image](https://github.com/idootop/mi-gpt/assets/16451516/b7cf0e5d-56bb-490d-ae69-9d0a2bb9bc6d)

**Comment by idootop** [comment]
@fky2015 你有试注释，配置playingCommand 分别输出的 play-state是什么吗？如果俩个获取到的状态值都为空，那估计就是这个机型也不支持流式响应和唤醒模式了。

**Comment by fky2015** [comment]
> @fky2015 你有试注释，配置playingCommand 分别输出的 play-state是什么吗？如果俩个获取到的状态值都为空，那估计就是这个机型也不支持流式响应和唤醒模式了。

- 注释/按照 spec 填入 `[3, 1, 1]`：为 `{"playState":"undefined"}`。
- 某一错误值（如 `[3, 1]`）：不断出现 `{"playState":"undefined"}`，且无响应。

是的，应该是不支持。
