### ISSUE TITLE
小米 sound pro 问题

### ISSUE THREAD

**Issue by wumohai** [idootop/mi-gpt#141]
无法连续回答。我查看文档。3-1-1 是表示在playing 。用micli.py  3-1 返回的是 [1]   3-1-1 返回的是 NULL。应该是这个设备对 这个指令做了修改。这个代码里面需要兼容一下

**Comment by idootop** [comment]
注释掉 palyingCommand 试试，目测你这个型号查询设备播放状态的属性只有通知权限，没有读取权限。

**Comment by wumohai** [comment]
您好！我是吴莫海!您给我的邮件我会尽快给您回复。谢谢！

**Comment by wumohai** [comment]
关闭这个之后，不能连续对话了，

**Comment by wumohai** [comment]
![image](https://github.com/idootop/mi-gpt/assets/7823070/9975b35d-424f-4a12-9d36-05a99f1bf9ad)

**Comment by idootop** [comment]
你这里的说法不是自相矛盾吗？
<img width="949" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/d3e90152-6c62-4def-956e-13da4b2611c1">
