### ISSUE TITLE
LLM 响应异常 BadRequestError: 400 Invalid parameter

### ISSUE THREAD

**Issue by gengzhichen** [idootop/mi-gpt#142]
访问gpt4模型时会返回以下错误，请帮忙看看是啥原因
`2024/07/05 11:53:43,stdout,2024/07/05 03:53:43 Open AI ❌ LLM 响应异常 BadRequestError: 400 Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.

2024/07/05 11:53:43,stdout,    at APIError.generate [90m(/app/[39mnode_modules/[4m.pnpm[24m/openai@4.51.0/node_modules/[4mopenai[24m/error.js:45:20[90m)[39m

2024/07/05 11:53:43,stdout,    at OpenAI.makeStatusError [90m(/app/[39mnode_modules/[4m.pnpm[24m/openai@4.51.0/node_modules/[4mopenai[24m/core.js:275:33[90m)[39m

2024/07/05 11:53:43,stdout,    at OpenAI.makeRequest [90m(/app/[39mnode_modules/[4m.pnpm[24m/openai@4.51.0/node_modules/[4mopenai[24m/core.js:318:30[90m)[39m

2024/07/05 11:53:43,stdout,[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m

2024/07/05 11:53:43,stdout,    at async OpenAIClient.chat [90m(/app/[39mdist/index.cjs:1196:28[90m)[39m

2024/07/05 11:53:43,stdout,    at async ShortTermMemoryAgent.generate [90m(/app/[39mdist/index.cjs:1965:17[90m)[39m

2024/07/05 11:53:43,stdout,    at async MemoryManager._updateShortTermMemory [90m(/app/[39mdist/index.cjs:2064:23[90m)[39m

2024/07/05 11:53:43,stdout,    at async MemoryManager.updateLongShortTermMemory [90m(/app/[39mdist/index.cjs:2041:21[90m)[39m {
"
2024/07/05 11:53:43,stdout,"  status: [33m400[39m,

2024/07/05 11:53:43,stdout,  headers: {
"
2024/07/05 11:53:43,stdout,"    [32m'alt-svc'[39m: [32m'h3=\":443\"; ma=86400'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'cf-cache-status'[39m: [32m'DYNAMIC'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'cf-ray'[39m: [32m'89e468debe400ff4-LAX'[39m,
"
2024/07/05 11:53:43,stdout,"    connection: [32m'keep-alive'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'content-length'[39m: [32m'217'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'content-type'[39m: [32m'application/json'[39m,
"
2024/07/05 11:53:43,stdout,"    date: [32m'Fri, 05 Jul 2024 03:53:43 GMT'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'openai-organization'[39m: [32m'user-t6dhuuexnlnxmvht3oryyd8x'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'openai-processing-ms'[39m: [32m'17'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'openai-version'[39m: [32m'2020-10-01'[39m,
"
2024/07/05 11:53:43,stdout,"    server: [32m'cloudflare'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'set-cookie'[39m: [32m'__cf_bm=ZxHVhl6vrx1_GuCmcHROQSksl8XE.Yk6qZvuokhA86k-1720151623-1.0.1.1-Cg_TzpJXu4BxX2FyS7.wjTe0OldvlgBpLzil33o4TTXr98H8zoO3dXQkaQRwhrkEMLQoWThE1AgNtFjdfs14cQ; path=/; expires=Fri, 05-Jul-24 04:23:43 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=K_vMhls5fPsIyN1zQQ6J.C.6Lw6lTw67BFv0yWwzq_8-1720151623729-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'strict-transport-security'[39m: [32m'max-age=31536000; includeSubDomains'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-limit-requests'[39m: [32m'5000'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-limit-tokens'[39m: [32m'80000'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-remaining-requests'[39m: [32m'4999'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-remaining-tokens'[39m: [32m'79280'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-reset-requests'[39m: [32m'12ms'[39m,
"
2024/07/05 11:53:43,stdout,"    [32m'x-ratelimit-reset-tokens'[39m: [32m'540ms'[39m,

2024/07/05 11:53:43,stdout,    [32m'x-request-id'[39m: [32m'req_425a9e47e10ea502a33ff1ca76f8c093'[39m
"
2024/07/05 11:53:43,stdout,"  },
"
2024/07/05 11:53:43,stdout,"  request_id: [32m'req_425a9e47e10ea502a33ff1ca76f8c093'[39m,

2024/07/05 11:53:43,stdout,  error: {
"
2024/07/05 11:53:43,stdout,"    message: [32m\"Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.\"[39m,
"
2024/07/05 11:53:43,stdout,"    type: [32m'invalid_request_error'[39m,
"
2024/07/05 11:53:43,stdout,"    param: [32m'response_format'[39m,

2024/07/05 11:53:43,stdout,    code: [1mnull[22m
"
2024/07/05 11:53:43,stdout,"  },
"
2024/07/05 11:53:43,stdout,"  code: [1mnull[22m,
"
2024/07/05 11:53:43,stdout,"  param: [32m'response_format'[39m,

2024/07/05 11:53:43,stdout,  type: [32m'invalid_request_error'[39m

2024/07/05 11:53:43,stdout,}`
[output.txt](https://github.com/user-attachments/files/16104728/output.txt)

**Comment by idootop** [comment]
请用 `gpt-4o` 或 `gpt-4-turbo` or `gpt-3.5-turbo`，长短期记忆功能需要模型支持 `json_object` 参数
