### ISSUE TITLE
text generation webui 的api无法使用

### ISSUE THREAD

**Issue by lugangqi** [idootop/mi-gpt#144]
通常，您可以使用以下环境变量强制使用 OpenAI API 的应用程序连接到本地 API：

OPENAI_API_HOST=http://127.0.0.1:5000
或

OPENAI_API_KEY=sk-111111111111111111111111111111111111111111111111
OPENAI_API_BASE=http://127.0.0.1:5000/v1

依旧无效，我使用是vue的这个修改了文件后npm run dev启动后，本地部署的大模型无法调用api
求解决

**Comment by lugangqi** [comment]
我的是小米ai音响二代，运行使用oobabooga-text-generation-webui运行模型，随后使用小爱这个无法调用，求解决

**Comment by idootop** [comment]
环境变量名称不对，请按照.env.example 填写正确的环境变量名称，以及值。请仔细阅读FAQ文档。

**Comment by lugangqi** [comment]
请问有q群吗

**Comment by lugangqi** [comment]
.env 填写的OPENAI_MODEL=14b-exl
OPENAI_API_KEY=sk-111111111111111111111111111111111111111111111111
OPENAI_BASE_URL=http://192.168.123.181:5000/v1
