### ISSUE TITLE
            throw new Errors.OpenAIError("The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).");                   ^

### ISSUE THREAD

**Issue by lugangqi** [idootop/mi-gpt#145]
OPENAI_MODEL=14b-exl
OPENAI_API_KEY=sk-111111111111111111111111111111111111111111111111
OPENAI_BASE_URL=http://127.0.0.1:5000/v1

已测试0.0.0.0,192.168.123.181,127.0.0.1依旧报错key的问题，我本地部署要什么key？
OpenAIError: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).

**Comment by lugangqi** [comment]
我已经阅读了你的全部文章，环境变量一起正常，api别的都能调用就这个调用不了，  OPENAI_MODEL:"14b-exl",
  OPENAI_API_KEY:"sk-111111111111111111111111111111111111111111111111",
  OPENAI_BASE_URL:"http://127.0.0.1:5000/v1",

**Comment by lugangqi** [comment]
不管怎么填都是问我要key

**Comment by lugangqi** [comment]
测试了两天了

**Comment by idootop** [comment]
打开debug自己看下打印出来的环境变量的值到底是什么。

你上面报的错误有且只有可能是你的 OPENAI_API_KEY 没填（如果你的本地模型不需要，那你可以随便给个非空字符串）

另外，非 OpenAI 官方接口和 API_KEY 的情况出现的问题，与 MiGPT 无关，请自行解决。
