### ISSUE TITLE
关于问他是哪个版本的GPT的问题

### ISSUE THREAD

**Issue by FuXiangGit** [idootop/mi-gpt#149]
我已经配置好了GPT相关的参数，但是我问她：你是哪个版本的GPT，或者你使用的是哪个模型，它都告诉我它叫傻妞，为什么回复我的不是“我是gpt4"或者我是gpt4o等，我怎么证明它在用这个gpt模型

**Comment by idootop** [comment]
> 它都告诉我它叫傻妞

说明已经在调用大模型，在用你设定的“傻妞”人设回答你的问题了。

> 我怎么证明它在用这个gpt模型

你在系统 Prompt 模版里设定它叫什么就叫什么，如果你不需要人设，请按照 FAQ 中的教程自行关闭系统 Prompt 。
