### ISSUE TITLE
首先必须夸赞这是个很Nice的项目，尽管还没用上，请大佬儿适配armv7Docker~~~

### ISSUE THREAD

**Issue by wt666666** [idootop/mi-gpt#15]
一开始看着Node步骤也不难，结果一看就会 一搞就废，报错跑不起来
想起还有一台多年前斥巨资购买的玩客云，
然后特意拆机-刷机~(省去一万字)为的就是想尝试Mi-GPT，
结果latest: Pulling from idootop/mi-gpt
no matching manifest for linux/arm/v7 in the manifest list entries~~~
请大佬儿是适配一下armv7Docker？玩客云的最后车位只为 Mi-GPT 而留~
![正在载入… - Opera 1_6_2024 上午 8_27_31](https://github.com/idootop/mi-gpt/assets/39096045/8f29a0a1-99cf-43dd-902c-bfb8cb9eed5c)

**Comment by idootop** [comment]
稍后更新

**Comment by wt666666** [comment]
> 稍后更新

牛得嘞~~

**Comment by idootop** [comment]
@wt666666  最新版镜像已支持 ARMv7
