### ISSUE TITLE
docker镜像在arm设备上无法启动

### ISSUE THREAD

**Issue by mylhei** [idootop/mi-gpt#151]
启动命令
```bash
docker run -d --env-file $(pwd)/.env -v $(pwd)/.migpt.js:/app/.migpt.js idootop/mi-gpt:latest
```
报错

```
  #  Node.js[1]: double node::GetCurrentTimeInMicroseconds() at ../src/util.cc:226
  #  Assertion failed: (0) == (uv_gettimeofday(&tv))
```

解决参考：
https://askubuntu.com/questions/1263284/apt-update-throws-signature-error-in-ubuntu-20-04-container-on-arm

启动命令增加 ` --security-opt seccomp:unconfined `

**Comment by idootop** [comment]
很遗憾，目前只支持标准的 linux/amd64, linux/arm64, linux/arm32/v7 设备，其他架构暂不支持（你的树莓派）。

**Comment by likohank** [comment]
感谢， 树莓派4b启动成功

env 文件配置如下：
# OpenAI（也支持通义千问、MoonShot、DeepSeek 等模型）
OPENAI_MODEL=gpt-4o
OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXL_OOOOOOOOOOOO55-sSSSSSSSS
OPENAI_BASE_URL=https://api.openai.com/v1

HTTP_PROXY=socks5h://user:pwd@IP:port
HTTPS_PROXY=socks5h://user:pwd@IP:port

需要用socks5h，不要写 socks5。

启动命令 docker run -d  --security-opt seccomp:unconfined  --env-file ./env -v ./migpt.js:/app/.migpt.js docker.unse
e.tech/idootop/mi-gpt:latest
