### ISSUE TITLE
❌ 找不到设备：小米AI音箱（第二代）

### ISSUE THREAD

**Issue by coolxy** [idootop/mi-gpt#156]
❌ 找不到设备：小米AI音箱（第二代）

ð请检查你的 did 与米家中的设备名称是否一致。注意错别字、空格和大小写，比如：音响 ð 音箱
2024/07/17 02:14:46 Speaker ❌ 初始化 Mi Services 失败

中文符号，英文符号等都用过了，这个要怎么做，求。

**Comment by idootop** [comment]
打开 debug 找到设备真实的 did 填上（一串数字/字母），具体如何操作自己翻翻 [FAQ](https://github.com/idootop/mi-gpt/blob/main/docs/faq.md) 看看。

**Comment by coolxy** [comment]
已解决 ，自己重新命名，去年了括号，成功，
