### ISSUE TITLE
群晖NAS Container 无法启动

### ISSUE THREAD

**Issue by Oliver-DT** [idootop/mi-gpt#159]
文件夹下 2 个文件已经上传了，但是启动时还是报错，求大佬指教

<img width="539" alt="1" src="https://github.com/user-attachments/assets/8a39a035-8ac6-40d8-82f3-e68d9aa0f2f8">
<img width="1040" alt="2" src="https://github.com/user-attachments/assets/e8e7bc96-8bf9-472e-b428-b702708d3d8a">

**Comment by idootop** [comment]
说明你Docker启动参数配置的不正确

**Comment by idootop** [comment]
如果没有其他反馈信息补充的话，我先关闭这个 issue 了。
