### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by xiaominggan** [idootop/mi-gpt#163]
C:\Users\Administrator>docker run -d --env-file G:/work/code/mi-gpt-4.1.0/.env -v G:/work/code/mi-gpt-4.1.0/.migpt.js:/app/.migpt.js idootop/mi-gpt:latest
docker: Error response from daemon: invalid volume specification: 'G:/work/code/mi-gpt-4.1.0/.migpt.js:/app/.migpt.js': invalid mount config for type "bind": source path must be a directory.
See 'docker run --help'.

**Comment by idootop** [comment]
显然你不应该使用 `G : xxx : xxx` 的语法来挂载文件，会被解析成挂载 `G` 到 `xxx`
