### ISSUE TITLE
[疑问]是否支持ollama呢

### ISSUE THREAD

**Issue by ldwnt** [idootop/mi-gpt#169]
本地部署的ollama，接口如下：
curl --request POST \
  --url http://localhost:11434/api/chat \
  --header 'Content-Type: application/json' \
  --data '{
    "model": "llama3.1:8b",
    "messages": [
        {
            "role": "system",
            "content": ""
        },
        {
            "role": "user",
            "content": ""
        }
    ],
    "stream": false
}
'
请问是否支持，以下几个参数要怎么填呢？谢谢
OPENAI_API_KEY | OpenAI API 密钥 | abc123
OPENAI_MODEL | 使用的 OpenAI 模型 | gpt-4o
OPENAI_BASE_URL | 可选，OpenAI API BaseURL | https://api.openai.com/v1

**Comment by idootop** [comment]
自行百度 ollama 接口如何兼容 OpenAI 接口格式，以及对应参数的含义与格式。
