### ISSUE TITLE
请问这个项目的正确使用方法是克隆还是引入对应的库？

### ISSUE THREAD

**Issue by csjuXYZ** [idootop/mi-gpt#17]
尝试了一下直接引入，手写了main.js，发现似乎需要build才能运行

**Comment by idootop** [comment]
README 有写怎么在 Node 项目中使用，不推荐直接克隆本仓库运行。
<img width="873" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/b4a4945b-61f0-4390-a084-84878f8888dc">
如果你按此方法运行出现问题，请贴上报错截图和最小可复现代码。

**Comment by idootop** [comment]
@csjuXYZ 现在的配置有点问题，你可以先使用 docker 镜像，稍后我更新下 Node 项目的使用文档和示例代码。

**Comment by csjuXYZ** [comment]
> @csjuXYZ 现在的配置有点问题，你可以先使用 docker 镜像，稍后我更新下 Node 项目的使用文档和示例代码。

目前靠克隆跑起来了，等更新了之后再尝试引入
