### ISSUE TITLE
LLM响应异常，是不支持chatanywhere吗？

### ISSUE THREAD

**Issue by cstybbt** [idootop/mi-gpt#170]
![275b2d29-22a0-4621-b6ba-875d56052c90](https://github.com/user-attachments/assets/991f7ff4-92c0-434b-a4ce-9771825bd993)
![90c9b3af-df91-4284-9574-e5aa566af0a6](https://github.com/user-attachments/assets/75e34537-c87f-4ac0-a561-61e14c93468b)
![c61b83cf-9a9b-4f96-8a41-fff2a9f0068e](https://github.com/user-attachments/assets/a82dd2f3-5314-4fb1-b098-ca7f5289b719)
相同网络环境下，用python调用接口有回复的，是我哪里设置错误了吗？

**Comment by idootop** [comment]
目测你的实际baseURL不正确，你可以打开debug查看下真实的环境变量值

**Comment by cstybbt** [comment]
你是对的，第一次配置的baseurl错了。就修改了.env应该是没起作用。删除容器后重来就可以用了
