### ISSUE TITLE
本地模型连接上后回答时，回答内含敏感信息请问如何回答？

### ISSUE THREAD

**Issue by lugangqi** [idootop/mi-gpt#176]
本地模型连接上后回答时，回答内含敏感信息请问如何回答？

**Comment by lugangqi** [comment]
然后一直显示设备在线，然后我说话，她并没有报错也没有用我本地模型回答，而是小米正经助手离谱

**Comment by idootop** [comment]
这是两个问题

> 本地模型连接上后回答时，回答内含敏感信息

走小米原生的 TTS 会有敏感词检测，可按照教程更换第三方 TTS 引擎

> 然后我说话，她并没有报错也没有用我本地模型回答
1. 你的第一个问题描述，说明已经能够正常调用你的本地模型来回答
2. 后面没有调用有几种可能：
    1. 你的问题没有触发你设定的 AI 唤醒关键词，自然不会调用大模型来回答
    2. 如果你是在连续对话模式，你说话他没有响应，说明你说话的时候它并没有在听取你的指令
    3. 你的指令触发了小爱自带的一些技能，比如讲笑话，查看天气等
