### ISSUE TITLE
当OpenAI回答较长时，小爱音箱说出该回答的2/3长度时就会戛然而止

### ISSUE THREAD

**Issue by LingoodBoy** [idootop/mi-gpt#182]
当OpenAI回答较长时，比如有200多个字，小爱音箱说出该回答的2/3长度时就会戛然而止

**Comment by LingoodBoy** [comment]
设置均默认，设备是小爱音箱pro
![Uploading image.png…]()

**Comment by LingoodBoy** [comment]
设置均默认，设备是小爱音箱pro
![1](https://github.com/user-attachments/assets/8117b353-011e-4735-b2a5-122c4e1d57b1)

**Comment by idootop** [comment]
小米 TTS 有文字上限，超出部分会被截断。

考虑在 .migpt.js 配置文件中打开 streamResponse 选项，此时长文本会拆分成好几段短文本播放。
