### ISSUE TITLE
没有错误，反正呼唤完就退出

### ISSUE THREAD

**Issue by meyer-net** [idootop/mi-gpt#184]
小爱同学，呼唤傻妞。
然后就是：哎呀，华人牌能量手机傻妞，能量不足，已停止服务。

日志如下：
![image](https://github.com/user-attachments/assets/6dd7460a-65b7-4b97-8b77-edb05875b88a)

**Comment by meyer-net** [comment]
型号为：小爱触屏音箱 Pro 8

**Comment by idootop** [comment]
换个名字，小爱同学自带一个叫傻妞的小爱技能，回答你的是原来的小爱同学，不是大模型。

**Comment by idootop** [comment]
显然，那是小爱同学自己原来的回复。建议先观看视频教程学习下，怎么提问才会让 MiGPT 调用 AI 回答你的问题。
