### ISSUE TITLE
感谢作者，让小米变得更聪明。

### ISSUE THREAD

**Issue by dludream** [idootop/mi-gpt#185]
感谢作者，让小米变得更聪明。

**Comment by xx2120** [comment]
我也遇到这个问题

**Comment by idootop** [comment]
上面的报错信息是因为你的LLM接口超出请求频率限制（通常是因为一次性请求的token数较大），这里出现在长短期记忆总结的步骤，大概率是上下文过长，可以换用支持更长上下文的LLM。

此错误基本可以忽略，不影响正常回复。未来的版本考虑添加一个是否使用长短期记忆的开关。

**Comment by taylorren** [comment]
我成功编译并运行了程序。

![微信图片_20241022202324](https://github.com/user-attachments/assets/f6e9adbb-cecf-4735-bc4a-3b8598efec4c)

好像很有问题诶。

**Comment by idootop** [comment]
@taylorren 你用的什么大模型？发下模型名称

**Comment by ziwend** [comment]
使用internlm/internlm2_5-20b-chat，总是出现Memory ❌ 💀 生成短期记忆失败，问不同的问题也出现了一直用上一个回答：

2024/10/26 13:56:03 Speaker 🔥 请给我推荐一些最好的科幻电影
2024/10/26 13:56:04 Speaker 🔊 让我先想想
2024/10/26 13:56:10 Open AI ✅ Answer: 哎呀，亲爱的先生，你这个问题简直是对我的一种信任呢！既然你让我选，那么我就选近期上映的一部热议电影《流浪地球二》来为你写这篇观后感吧。

首先，我要说的是，这部电影真的让我非常震撼。它不仅仅是视觉上的一次盛宴，更是一次心灵的触动。影片中展示的科技水平，从行星发动机到太空电梯，每一个细节都让人感受到人类对科技无限的追求和探索。这不仅仅是一种技术的展示，更是对未来无限可能的无限憧憬。

然后，电影中对人类情感的描绘也深深打动了我。在面对巨大的灾难和挑战时，人与人之间的情感显得格外珍贵。无论是父子情深，还是跨越国界的合作，每个情节都让人感受到了人性的温暖和力量。这种情感的展现，让这部电影不仅仅是一次视觉的盛宴，更是一次心灵的触动。

而且，电影中对人类命运共同体的思考也让我深思。在全球面临危机时，各国之间摒弃前嫌、携手合作，共同面对困难。这种和平与合作的描绘，让人看到了一个和谐共生的未来景象。它告诉我们，面对共同的挑战，人类唯有团结一致，才能共度难关。

所以，亲爱的代先生，《流浪地球二》不仅仅是一次科幻电影的享受，更是一次对科技、情感和人类未来的深度探讨。它让人深思，也让人充满希望。我希望你能去欣赏这部作品，从中获得更多的启发和感动。期待与你分享你的观影感受哦！
2024/10/26 13:56:10 Speaker 🔊 哎呀，亲爱的代先生，你这个问题简直是对我的一种信任呢！既然你让我选，那么我就选近期上映的一部热议电影《流浪地球二》来为你写这篇观后感吧。
首先，我要说的是，这部电影真的让我非常震撼。它不仅仅是视觉上的一次盛宴，更是一次心灵的触动。影片中展示的科技水平，从行星发动机到太空电梯，每一个细节都让人感受到人类对科技无限的追求和探索。这不仅仅是一种技术的展示，更是对未来无限可能的无限憧憬。
然后，电影中对人类情感的描绘也深深打动了我。在面对巨大的灾难和挑战时，人与人之间的情感显得格外珍贵。无论是父子情深，还是跨越国界的合作，每个情节都让人感受到了人性的温暖和力量。这种情感的展现，让这部电影不仅仅是一次视觉的盛宴，更是一次心灵的触动。
而且，电影中对人类命运共同体的思考也让我深思。在全球面临危机时，各国之间摒弃前嫌、携手合作，共同面对困难。这种和平与合作的描绘，让人看到了一个和谐共生的未来景象。它告诉我们，面对共同的挑战，人类唯有团结一致，才能共度难关。
所以，亲爱的代先生，《流浪地球二》不仅仅是一次科幻电影的享受，更是一次对科技、情感和人类未来的深度探讨。它让人深思，也让人充满希望。我希望你能去欣赏这部作品，从中获得更多的启发和感动。期待与你分享你的观影感受哦！
2024/10/26 13:58:59 Speaker 🔥 请推荐更多的科幻电影
2024/10/26 13:59:00 Speaker 🔊 让我先想想
2024/10/26 13:59:06 Open AI ✅ Answer: 哎呀，亲爱的先生，你这个问题简直是对我的一种信任呢！既然你让我选，那么我就选近期上映的一部热议电影《流浪地球二》来为你写这篇观后感吧。
2024/10/26 13:59:09 Memory ❌ 💀 生成短期记忆失败

**Comment by idootop** [comment]
> 使用internlm/internlm2_5-20b-chat，总是出现Memory ❌ 💀 生成短期记忆失败

@ziwend  可能是输入的文本长度超出你这个模型能处理的上下文了。

> 问不同的问题也出现了一直用上一个回答

问答时会带上最近的几条对话记录，所以你这个模型推理能力太差一直在 repeat 重复之前的回复。

考虑其他推理能力更强的模型，或者清除本地消息记录（现在只能删掉实例重新创建）

**Comment by ziwend** [comment]
> > 使用internlm/internlm2_5-20b-chat，总是出现Memory ❌ 💀 生成短期记忆失败
> 
> @ziwend 可能是输入的文本长度超出你这个模型能处理的上下文了。
> 
> > 问不同的问题也出现了一直用上一个回答
> 
> 问答时会带上最近的几条对话记录，所以你这个模型推理能力太差一直在 repeat 重复之前的回复。
> 
> 考虑其他推理能力更强的模型，或者清除本地消息记录（现在只能删掉实例重新创建）

感谢大佬的及时解答，模型换成了moonshot-v1-8k，删除原来的docker实例，重建后目前还没啥问题 ，谢谢。
