### ISSUE TITLE
无法通过音箱发声AI回复

### ISSUE THREAD

**Issue by 27chcn** [idootop/mi-gpt#186]
![ba05c3103ea6ca53134a65f002d95237](https://github.com/user-attachments/assets/98bddd38-d28f-44be-a7dd-c150f5cdb2c0)
打断小爱的回复后 可以正常获取到AI回复 但是无法通过音箱发送语音 为啥默认会unWakeUp

**Comment by 27chcn** [comment]
使用的是小米音箱Play

**Comment by xucaiqin** [comment]
me too
