### ISSUE TITLE
如何设置中国的时区，在群晖docker设置TZ环境变量无效

### ISSUE THREAD

**Issue by haimingwan** [idootop/mi-gpt#187]

**Comment by haimingwan** [comment]
![image](https://github.com/user-attachments/assets/f049d0ec-0221-496e-bf3e-35c0393e926f)

**Comment by idootop** [comment]
TZ Asia/Shanghai

**Comment by idootop** [comment]
坚持你的docker环境变量是否生效

**Comment by haimingwan** [comment]
> 检查你的docker环境变量是否生效

确实是配置参数没设置好，已经正常，谢谢了
