### ISSUE TITLE
 Open AI ❌ LLM 响应异常 NotFoundError: 404 Resource not found

### ISSUE THREAD

**Issue by kongqi987** [idootop/mi-gpt#188]
![image](https://github.com/user-attachments/assets/be4fce83-dad0-4597-a369-300564538827)
![image](https://github.com/user-attachments/assets/c27ccfff-3e3a-4062-9b76-8a35aa19dc69)

我是用azure openai ，但gui那里没有这个选项，选自定义，密匙和azure密匙都是必填，我两个都填了azure密匙，也切换了openai选项，密匙直接填azure的都不行

**Comment by idootop** [comment]
gui是另一个项目，与本仓库无关。可以按照 .env.template里的示例，填写对应参数。
