### ISSUE TITLE
停在等待语音输入一段时间后才回答AI答案

### ISSUE THREAD

**Issue by BussanQ** [idootop/mi-gpt#190]
机型小爱智能家庭屏 10[X10A]，关闭了连续对话，基本可用。
现在问题是，每次提问后，小爱自己的回答先被mute，回答请稍等，然后页面会一直停在等待语音输入的状态（这个时候有房间有说话也会显示到输入里）。过一段时间后才会开始读AI答案。

**Comment by idootop** [comment]
一直停在语音输入状态是因为你的背景声音有人在一直说话，小爱音箱系统行为，无法更改。
