### ISSUE TITLE
使用azure openai要如何配置

### ISSUE THREAD

**Issue by kongqi987** [idootop/mi-gpt#193]
ai服务自定义那里，我填了azure密匙，但是密匙不能空白，我也填了azure密匙，出错提示：

file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/index.mjs:145
            throw new Errors.OpenAIError("The OPENAI_API_VERSION environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).");
                  ^

**Comment by jieye-ericx** [comment]
您好，请问您是怎么解决的？我也用的azure openAI服务，也有这个疑惑
