### ISSUE TITLE
群晖 Azure 访问LLM 响应异常 NotFoundError: 404 Resource not found

### ISSUE THREAD

**Issue by jieye-ericx** [idootop/mi-gpt#194]
### 配置（隐去了key相关，key在其他客户端上测试可用）
<img width="674" alt="image" src="https://github.com/user-attachments/assets/f54f000e-4c5d-4d71-8bcc-28a415295ed1">

### 返回
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/69ee0134-866d-43c3-a030-7d929f4bef85">

想问下是设置有误吗，stream流对话关闭状态，小爱音箱pro

**Comment by idootop** [comment]
你填写的 endpoint 和 deployment 应该有误，可以按照 FAQ 里的示例检查下。
