### ISSUE TITLE
小爱音箱pro❌ LLM 响应异常

### ISSUE THREAD

**Issue by kongqi987** [idootop/mi-gpt#197]
❌ LLM 响应异常 BadRequestError: 400 Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.
![屏幕截图 2024-10-03 160531](https://github.com/user-attachments/assets/435f9bd6-70e3-4709-add6-0061640a9f9a)

**Comment by idootop** [comment]
是因为你使用的 LLM 服务不支持 json_format 请求参数，早期的 gpt-3.5-turbo 等模型并不支持此参数。
建议升级到最新的 gpt-4o 系列模型。
