### ISSUE TITLE
对于chatgpt多行回复，只能输出第一行的语音

### ISSUE THREAD

**Issue by McKinleyLu** [idootop/mi-gpt#20]
![image](https://github.com/idootop/mi-gpt/assets/45777553/93dff17c-72fd-4669-aac9-3aff0c5a61ba)
提问: 可可战国四大名将是谁？
回答：王翦（秦国）- 他是秦始皇的重要将领，多次带领秦军取得重大战功。
然后直接回复了： 🔊 还有其他问题吗？

也就是说，chatgpt多行回复只能输出第一行语音，希望作者可以修一修这个小bug，辛苦啦

**Comment by idootop** [comment]
你的小爱音箱是什么型号？有些型号需要配置 playingCommand

**Comment by shangjiyu** [comment]
借楼： 小爱触屏音箱pro 8， 配置 playingCommand: [4,1,1]， palyState: undefined, 导致未读完整

**Comment by idootop** [comment]
> 借楼： 小爱触屏音箱pro 8， 配置 playingCommand: [4,1,1]， palyState: undefined, 导致未读完整

你的这个设备 [playing-state](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:playing-state:00000041) 没有读取权限，把 playingCommand 注释掉，如果获取到的 palyState 还是 undefined，说明此设备不支持外部直接读取播放状态，无解。

**Comment by idootop** [comment]
后面我会添加一个开关，控制是否启用流式响应，对于这种不支持的获取播放状态的设备，流式响应和唤醒模式就都失效了，只能一句一句的唤醒小爱进行对话。

**Comment by shangjiyu** [comment]
手动写tts状态可以哇？不查playing state发自我的 iPhone在 2024年6月4日，15:59，Del ***@***.***> 写道：﻿
后面我会添加一个开关，控制是否启用流式响应，对于这种不支持的获取播放状态的设备，流式响应和唤醒模式就都失效了，只能一句一句的唤醒小爱进行对话。

**Comment by idootop** [comment]
没理解你说的 `手动写tts状态` 是什么意思

**Comment by idootop** [comment]
[v3.0.0](https://github.com/idootop/mi-gpt/releases/tag/v3.0.0) 版本已发布，添加了流式响应开关。对于获取播放状态为空的小爱音箱设备，请在 `.migpt.js` 配置文件中关闭 `streamResponse` 选项，即可保证小爱的回复是完整的句子。

```js
export default {
  speaker: {
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: false,
    // ...
  },
};
```

**Comment by BiuBiu2323** [comment]
感谢

**Comment by MsterMMM** [comment]
> 借楼： 小爱触屏音箱pro 8， 配置 playingCommand: [4,1,1]， palyState: undefined, 导致未读完整

请问下兄弟最后是怎么搞定的？我的同型号音箱总是无法播放
