### ISSUE TITLE
小爱音箱Play增强版问题

### ISSUE THREAD

**Issue by yanxiang1120** [idootop/mi-gpt#201]
![屏幕截图 2024-10-15 191413](https://github.com/user-attachments/assets/daae80a4-970f-4791-9c56-df7ec4ad62ae)
小爱音箱Play拿不到播放状态的问题，可以考虑根据字数做一个阅读时长的估算，到预估时长后再继续播放下一条。

**Comment by idootop** [comment]
也是一种策略，但实际体验未必会好。

**Comment by yanxiang1120** [comment]
默认tts的语速，总字数除以6算出大概时长，上条播完1秒左右，能顺利接上下一条结果，有兴趣的话可以试一下。

**Comment by BarryYin** [comment]
> 默认tts的语速，总字数除以6算出大概时长，上条播完1秒左右，能顺利接上下一条结果，有兴趣的话可以试一下。

具体怎么做，有代码吗？

**Comment by idootop** [comment]
> 默认tts的语速，总字数除以6算出大概时长，上条播完1秒左右，能顺利接上下一条结果，有兴趣的话可以试一下。

只能说可以这样近似处理，但无法精确推广到更普遍的场景哈。

1. 要考虑标点符号不发音
2. 要考虑英文单词的发音时长
3. 要考虑网络质量是否稳定
