### ISSUE TITLE
我让它说英文，就不回复了，是因为小爱原生的检测机制吗？如何直接劫持语音输入的内容，不让它做安全检测

### ISSUE THREAD

**Issue by BarryYin** [idootop/mi-gpt#202]

**Comment by idootop** [comment]
1. 中文外的其他语言，小爱TTS应该也是支持播放的。系统默认的prompt以中文对话环境为基础，你可能需要设计自己的系统Prompt。
2. 小米并未开放出任何接口来获取音响设备的语音输入，只有手动刷机破解硬件，然后刷写你自己破解后的处理逻辑。关于这一点在FAQ和多个issue下面都有提及，不妨搜搜看。

**Comment by BarryYin** [comment]
请问还有交流群吗，我可以拍视频给你看下

**Comment by BarryYin** [comment]
我说中文的时候，它能识别我的语音并文本传输。但我对着音箱说英文，它就没有反应
