### ISSUE TITLE
我自己本地写一个flask，按照openai的格式做输入输出，docker启动，音箱卡着没有反馈，flask本次是可以跑api的

### ISSUE THREAD

**Issue by BarryYin** [idootop/mi-gpt#206]
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://172.21.32.182:5002
INFO:werkzeug:Press CTRL+C to quit
Received request: message='你好啊，你是谁呀', user_id='123123***'
{'id': 'chatcmpl-123', 'object': 'chat.completion', 'created': 1729939125, 'model': '', 'system_fingerprint': 'fp_44709d6fcb', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '张奶奶您好呀，我是您的看护陪伴机器人瓦力哦。我可以陪您聊天解闷，给您讲讲有趣的故事和笑话，还能告诉您天气情况和当天的新闻呢。😉'}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': '', 'completion_tokens': '', 'total_tokens': ''}}
<class 'dict'>
INFO:werkzeug:127.0.0.1 - - [26/Oct/2024 18:38:45] "POST /v1/chat/completions HTTP/1.1" 200 -
Received request: message='你好啊，你是谁呀', user_id='123123***'
{'id': 'chatcmpl-123', 'object': 'chat.completion', 'created': 1729939137, 'model': '', 'system_fingerprint': 'fp_44709d6fcb', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '张奶奶您好呀，我是您的看护陪伴机器人瓦力哦。我可以陪您聊天解闷，给您讲讲有趣的故事和笑话，还能告诉您天气情况和当天的新闻呢。😉'}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': '', 'completion_tokens': '', 'total_tokens': ''}}
<class 'dict'>

音箱docker服务启动，也召唤出来AI，但是继续问问题时，卡着不动

**Comment by idootop** [comment]
那要考虑你本地的 TTS 服务返回的音频流，小爱音箱能不能播放出来，目测卡在音频播放。
