### ISSUE TITLE
傻妞的疑问句会出现：PKG：汪汪汪

### ISSUE THREAD

**Issue by mazzond** [idootop/mi-gpt#208]
试了qwen2.5-7b、llama3.1-8b两个模型，但是发现，在傻妞要提出问题时候，都会输出pkg/pk：汪汪汪，这个是什么原因呢？
感谢作者分享了这么厉害的东东~感谢~

**Comment by idootop** [comment]
不清楚，但看起来你用的本地部署的模型能力太差，不能很好理解你设置的 system prompt，可以换些大模型服务试试看
