### ISSUE TITLE
自定义语音听写Api的支持

### ISSUE THREAD

**Issue by AjaxZhan** [idootop/mi-gpt#21]
在这个项目的加持下，目前小爱音响的答复生成和答复语音（TTS）都可以自定义。
然而，目前小爱音响在最开始的语音理解转文字（语音听写）这个部分还是用的官方的。
如果我们能自定义语音听写这一层的API，就能够实现诸如方言识别、外语识别等功能。
因此我想询问一下这个项目能否支持自定义语音转写的Api呢，例如接入市面常见的讯飞Api。

**Comment by idootop** [comment]
很好的想法，但遗憾的是此功能（语音识别）无法通过官方合法途径实现，小米官方未开放任何相关能力接口。
只能通过刷机破解小爱音箱，植入自己定制的程序，实现对小爱音箱的完全控制。
这也是最完美的方案（可以彻底解决无法及时mute小爱回复的问题）。
但需要自己手动拆机刷写固件，门槛极高有变砖的风险，且失去了后续的官方固件升级更新，维护成本极高。
该方案并不在此项目的设计范围内。

不过，刷机方案社区也有人在尝试，你可以参考这个项目：https://github.com/jialeicui/open-lx01
