### ISSUE TITLE
接入成功了，无报错，但是回复内容很奇怪--豆包

### ISSUE THREAD

**Issue by jiangweidong** [idootop/mi-gpt#210]
2024/11/15 06:18:08 Speaker ✅ 服务已启动...
2024/11/15 06:19:09 Speaker 🔥 你是谁
2024/11/15 06:19:09 Speaker 🔊 让我先想想
2024/11/15 06:19:15 Open AI ✅ Answer: 我是傻妞呀
2024/11/15 06:19:15 Speaker 🔊 我是傻妞呀
2024/11/15 06:19:18 Speaker 🔊 还有其他问题吗
2024/11/15 06:21:38 Speaker 🔥 什么是哲学
2024/11/15 06:21:58 Speaker 🔥 请问什么是哲学
2024/11/15 06:21:59 Speaker 🔊 让我先想想
2024/11/15 06:22:05 Open AI ✅ Answer: 哎呀，我觉得哲学就是思考一些很深奥的问题，像人生的意义啦，世界的本质啦之类的，不过我也说不太清楚呢！
2024/11/15 06:22:05 Speaker 🔊 哎呀，我觉得哲学就是思考一些很深奥的问题，像人生的意义啦，世界的本质啦之类的，不过我也说不太清楚呢！
2024/11/15 06:22:18 Speaker 🔊 还有其他问题吗
2024/11/15 06:28:17 Speaker 🔥 打开豆包
2024/11/15 06:28:18 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024/11/15 06:28:51 Speaker 🔊 傻妞已退出

看了火山后台，访问成功了，但是回复的内容很奇怪

**Comment by idootop** [comment]
可以自己调整下系统prompt试试看，不同的模型适合不同的prompt。
