### ISSUE TITLE
如何彻底关闭傻妞

### ISSUE THREAD

**Issue by xietian0908** [idootop/mi-gpt#211]
老是在没人的时候自动唤醒傻妞，说一些莫名的话

**Comment by idootop** [comment]
你的问题应该拆分成2个：
 > 1. 没人的时候，为什么小爱同学会被唤醒？

显然，这是小爱音箱自己唤醒策略的问题，与该项目无关。

 > 2. 没人的时候，为什么小爱同学唤醒之后，MiGPT 会被唤起？

显然，这和你自己设置的 MiGPT 唤醒词有关。

而且我觉得在无人的时候，即使小爱音箱会被唤起，默认设置的 MiGPT 唤醒词也不会被触发。

显然，以上两个问题都和本项目自身内置的设定无关。

**Comment by xietian0908** [comment]
因为他说的是你好，我是傻妞 ； 然后过一段时间就说 傻妞退出。我没有运行项目的时候小爱并不会自动唤起，至少之前没遇到过早晨6点唤起；配置都是默认的，只配置了小米账号，设备名称，豆包apikey

**Comment by xietian0908** [comment]
设备是小爱音响pro，项目我是pnpm dev运行；傻妞关闭程序不会一起退出吗？

**Comment by xietian0908** [comment]
https://github.com/user-attachments/assets/6ef0ee67-f067-4b04-8ccb-a5ac8d1cd8ca

正好家里摄像机记录下来了，啥也没干自动唤起的傻妞

**Comment by idootop** [comment]
可能小米接口抽风拉取到了之前你唤醒傻妞的那条消息，触发了响应。

你可以直接关闭你运行 pnpm dev 的命令行来退出。
