### ISSUE TITLE
请问 Open AI ❌ LLM 响应异常 NotFoundError: 404 404 page not found怎么解决？

### ISSUE THREAD

**Issue by MarsCNS** [idootop/mi-gpt#221]
使用的是小米AI音箱（第二代），
ai配置是：
OPENAI_MODE=qwen2.5:7b
OPENAI_API_KEY=ollama
OPENAI_BASE_URL=http://myip:11434/api/v1

这里的地址http://myip:11434已经在其他地方都测试好用的。然后
http://myip:11434/v1
http://myip:11434/
http://myip:11434
http://myip:11434/api
都试过，全部都是报下面这个错误。

出错日志
==========================================
> mi-gpt@4.2.0 start
> node ./app.js
/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
| $$\  $ | $$| $$| $$  \ $$| $$         | $$   
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
|__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                 
         MiGPT v4.2.0  by: del.wang
2024/12/19 10:17:40 Speaker ✅ 服务已启动...
2024/12/19 10:18:33 Speaker 🔥 请介绍自己
2024/12/19 10:18:34 Speaker 🔊 让我先想想
2024/12/19 10:18:37 Open AI ❌ LLM 响应异常 NotFoundError: 404 404 page not found
    at APIError.generate (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/error.js:54:20)
    at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
  status: 404,

  headers: {
    connection: 'close',
    'content-length': '18',
    'content-type': 'text/plain',
    date: 'Thu, 19 Dec 2024 02:18:34 GMT'
  },
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
2024/12/19 10:18:38 Speaker 🔊 啊哦，出错了，请稍后再试吧！

**Comment by idootop** [comment]
报错已经很明显了，你的本地服务不存在对应接口地址，可能的原因有：
1. 你的接口不兼容 openai 格式
2. 你的 baseURL 配置未生效，打开 debug 自行排查
