### ISSUE TITLE
参照你的接口服务和框架，我自己添加了个vue的可视化界面

### ISSUE THREAD

**Issue by LipapaSma** [idootop/mi-gpt#222]
https://github.com/LipapaSma/mi-gpt-vue

**Comment by idootop** [comment]
看到了👍 你可以提个 PR 把这个项目加到推荐里。

PS: 你的项目 readme 里的图片资源没有加到 git 仓库里，看不到预览图。

**Comment by LipapaSma** [comment]
刚刚改好

**Comment by idootop** [comment]
已合并
