### ISSUE TITLE
用的群辉docker，一直提示登录失败。

### ISSUE THREAD

**Issue by czg82324** [idootop/mi-gpt#224]
![错误](https://github.com/user-attachments/assets/7a7e80fb-44e8-48f5-b136-0559bf4e9394)

**Comment by drkshen** [comment]
用的群辉docker 如何開啟:  监控容器的日志?

**Comment by czg82324** [comment]
没问题了，docker-compose里面加入
network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
     就好了

**Comment by McEyes** [comment]
我的一直加上这个，第一次部署的时候也是提示这个错误，后面重启就一直提示超时
