### ISSUE TITLE
关于获取设备列表 MiIOT接口的入参解释

### ISSUE THREAD

**Issue by LipapaSma** [idootop/mi-gpt#225]
大佬这个接口https://api.io.mi.com/app/home/device_list 的入参是啥；我看ts代码里面也是这样写的
<img width="667" alt="image" src="https://github.com/user-attachments/assets/e19f3dc9-3f69-4d73-a45e-abde57021c95" />
但是我调用的时候接口返回就是null

**Comment by idootop** [comment]
要带上 cookie，构造 headers，手动加解密请求参数。详细的逻辑 👉 [看这里](https://github.com/idootop/mi-service-lite/blob/820fc8f2abe0e821d99f4701bfc3dc54dbb61f41/src/mi/miot.ts#L45)

如果你还有疑问，请移步到另一个项目的 issue 区讨论：https://github.com/idootop/mi-service-lite

<img width="540" alt="图片" src="https://github.com/user-attachments/assets/546dd259-435c-49e5-9d07-5373b43730db" />

PS: 老哥都开始上 Rust 了，强啊 👍

**Comment by LipapaSma** [comment]
学习一下
