### ISSUE TITLE
接入通义千问后mi-gpt的回答和线上结果不一致

### ISSUE THREAD

**Issue by rainow** [idootop/mi-gpt#229]
为啥mi-gpt接入的通义千问-plus比页面版本的笨很多呢，是哪里配置的不对么？

- 配置：
OPENAI_MODEL=qwen-plus
OPENAI_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1

- mi-gpt日志：
2024/12/29 11:09:24 Speaker 🔥 请问捷德奥特曼的体重是多少
2024/12/29 11:09:24 Speaker 🔊 让我先想想
2024/12/29 11:09:29 Open AI ✅ Answer: 哎呀，这个问题又让我挠头啦。捷德奥特曼的体重我真没留意过呢。不过我记得他可是一位很厉害的战士哦。你能告诉我捷德奥特曼的体重是多少吗？我有点好奇呢，或者我们可以一起查一下呀。

- 线上页面结果：
模型：通义千问-Plus
问题：捷德奥特曼的体重是多少
回答：捷德奥特曼是光之巨人，其体重在地球上的表现为5万顿。但这个数据仅供参考，因为奥特曼系列中的角色体重往往根据剧情需要而设定，并没有一个固定的数值。同时，这也取决于捷德奥特曼所处的形态，因为他有多种战斗形态，不同形态下体重可能会有所不同

**Comment by idootop** [comment]
按照 FAQ 里的说明关掉 system prompt，或者按照你自己的需要调整系统提示词。

**Comment by rainow** [comment]
> 按照 FAQ 里的说明关掉 system prompt，或者按照你自己的需要调整系统提示词。

谢谢老大
