### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by aieejk** [idootop/mi-gpt#23]
在远程主机上docker运行
报了下面的错误

![image](https://github.com/idootop/mi-gpt/assets/171260721/d266d381-8e8b-48bb-a163-5e3447eeb01d)

**Comment by idootop** [comment]
检查 `.migpt.js` 文件挂载路径是否正确，看日志路径 `/app/.migpt.js` 是一个文件夹，应该放你的 `.migpt.js` 配置文件。

**Comment by idootop** [comment]
在 windows 终端下面启动 docker，配置文件要填绝对路径。参考：https://github.com/idootop/mi-gpt/issues/26#issuecomment-2151381521
