### ISSUE TITLE
自定义TTS音色名称不规范（如"不川秋衣"）的情况下很难正确匹配到音色

### ISSUE THREAD

**Issue by rainow** [idootop/mi-gpt#230]
大佬好，有空的时候看一下，不是高优需求。
我用旧手机装了个multitts，自建了个本地TTS服务，由于multitts可以自己导入不同的音色，很多音色的命名比较随便，切换音色的时候好像是用的名称全匹配（e.name === speaker || e.speaker === speaker），但是小爱同学对这些音色名称的文字识别经常不太准，有没有可能做个宽泛匹配或者拼音相似度匹配啥的啊，感谢。

提供个测试用例：

[{
	"name": "TVB小优",
	"gender": "女",
	"speaker": "bdetts_tvbxiaoyou"
}, {
	"name": "不川秋衣",
	"gender": "女",
	"speaker": "bdetts_buchuanqiuyi"
}, {
	"name": "乐乐妮儿",
	"gender": "女",
	"speaker": "bdetts_lelenier"
}, {
	"name": "念阿念",
	"gender": "女",
	"speaker": "bdetts_niananian"
}, {
	"name": "琪怪儿",
	"gender": "女",
	"speaker": "bdetts_qiguaier"
}, {
	"name": "孙笑川",
	"gender": "男",
	"speaker": "bdetts_sunxiaochuan1"
}, {
	"name": "堂堂一个小飞",
	"gender": "男",
	"speaker": "bdetts_tangtangyigexiaofei"
}, {
	"name": "甜蜜老张",
	"gender": "女",
	"speaker": "bdetts_tianmilaozhang"
}, {
	"name": "温馨予",
	"gender": "女",
	"speaker": "bdetts_lizi"
}, {
	"name": "下饭六六",
	"gender": "女",
	"speaker": "bdetts_xiafanliuliu"
}, {
	"name": "谢知初",
	"gender": "女",
	"speaker": "bdetts_xiezhichu"
}, {
	"name": "雪碧",
	"gender": "女",
	"speaker": "bdetts_xuebi"
}, {
	"name": "鱼蛋",
	"gender": "女",
	"speaker": "bdetts_yudan"
}, {
	"name": "张安琪",
	"gender": "女",
	"speaker": "bdetts_zhanganqi"
}, {
	"name": "丁真",
	"gender": "男",
	"speaker": "bdetts_dingzhen1"
}, {
	"name": "罗翔",
	"gender": "男",
	"speaker": "bdetts_luoxiang"
}, {
	"name": "冰糖IO",
	"gender": "女",
	"speaker": "bdetts_bingtangio"
}, {
	"name": "泠鸢yousa",
	"gender": "女",
	"speaker": "bdetts_yousa"
}, {
	"name": "叶悠悠",
	"gender": "女",
	"speaker": "bdetts_yeyouyou"
}, {
	"name": "苏轼Bot",
	"gender": "男",
	"speaker": "bdetts_sushi_bot"
},{
	"name": "祁柔",
	"gender": "女",
	"speaker": "bytedance_BV001"
}, {
	"name": "祁柔24k",
	"gender": "女",
	"speaker": "bytedance_BV001_24k"
}, {
	"name": "新闻主持",
	"gender": "男",
	"speaker": "bytedance_BV002"
}, {
	"name": "成熟大叔",
	"gender": "男",
	"speaker": "bytedance_BV003"
}, {
	"name": "开朗青年",
	"gender": "男",
	"speaker": "bytedance_BV004"
}, {
	"name": "开朗青年md",
	"gender": "男",
	"speaker": "bytedance_BV004-md"
}, {
	"name": "心怡",
	"gender": "女",
	"speaker": "bytedance_BV064_24k"
}, {
	"name": "温柔淑女",
	"gender": "女",
	"speaker": "bytedance_BV104"
}, {
	"name": "温柔淑女md",
	"gender": "女",
	"speaker": "bytedance_BV104-md"
}, {
	"name": "儒雅大叔",
	"gender": "男",
	"speaker": "bytedance_BV107_24k"
}, {
	"name": "情感女声",
	"gender": "女",
	"speaker": "bytedance_BV115_24k"
}, {
	"name": "武侠男声",
	"gender": "男",
	"speaker": "bytedance_BV119_24k"
}, {
	"name": "应晖",
	"gender": "男",
	"speaker": "bytedance_BV123_24k"
}, {
	"name": "甜美少女",
	"gender": "女",
	"speaker": "bytedance_BV405_24k"
}, {
	"name": "梦欣",
	"gender": "女",
	"speaker": "bytedance_BV406_24k"
}, {
	"name": "然月",
	"gender": "女",
	"speaker": "bytedance_BV407_24k"
}, {
	"name": "灿灿",
	"gender": "女",
	"speaker": "bytedance_BV700"
}, {
	"name": "灿灿24k",
	"gender": "女",
	"speaker": "bytedance_BV700_24k"
}, {
	"name": "浑厚男声",
	"gender": "男",
	"speaker": "bytedance_BV701"
}, {
	"name": "浑厚男声24k",
	"gender": "男",
	"speaker": "bytedance_BV701_24k"
}]

**Comment by wwfcnu** [comment]
这个项目支持类似于zh_female_taozi_conversation_v4_wvae_bigtts的豆包大模型的speaker吗

**Comment by idootop** [comment]
@rainow 多谢反馈。不过遗憾的是这个库目前并不考虑自定义音色列表和名称，如果你有需要，可以自行 fork 本仓库修改源码。

**Comment by idootop** [comment]
> 这个项目支持类似于zh_female_taozi_conversation_v4_wvae_bigtts的豆包大模型的speaker吗

@wwfcnu 暂时没有适配，因为火山大模型音色目前只有企业账号才能使用。你可以自行 fork 本仓库修改源码，适配起来很简单。

**Comment by hustlyt** [comment]
感觉有点不好识别，今天试了很多次，都开始怀疑自己普通话了。
然后是用GPT改了下源码，给应用加了个外部的接口，如果需要更换音色，就调用下接口。修改音色的逻辑在这里：
src\services\speaker\ai.ts：185-201
```
{
        match: (msg) =>
          this.switchSpeakerKeywords.some((e) => msg.text.startsWith(e)),
        run: async (msg) => {
          await this.response({
            text: "正在切换音色，请稍等...",
          });
          const prefix = this.switchSpeakerKeywords.find((e) =>
            msg.text.startsWith(e)
          )!;
          const speaker = msg.text.replace(prefix, "");
          const success = await this.switchSpeaker(speaker);
          await this.response({
            text: success ? "音色已切换！" : "",
            keepAlive: this.keepAlive,
          });
        },
      },
```

或者如果语音实现的话，在上面源码加一个命令，改成用序号：“请把音色切换为3号” :joy:
