### ISSUE TITLE
原本的小爱会插嘴

### ISSUE THREAD

**Issue by shuker2024** [idootop/mi-gpt#24]
唤醒AI以后，AI的第一句回复正常，但是继续对话原本的小爱同学会抢先回答说2-3个字以后切换到AI回答，这种体验怪怪的，总觉得小爱同学在刷存在感...  我的小爱音箱是“小米AI音箱”第一版

**Comment by idootop** [comment]
与本项目的实现原理有关。本项目通过轮询小米接口获取最新的对话信息，检测到小爱在回复的时候会通过播放静音音频等方式快速 mute 掉小爱原来的回复。但是从小爱开始回复，到上报状态给小米服务云端，再到本项目通过小米云端接口轮训到这个状态变更，会有大约 1 -2 秒的延迟时间，无解。理论上需要通过刷机才能完美解决这个问题，参考此 issue： https://github.com/idootop/mi-gpt/issues/21#issuecomment-2147125219
