### ISSUE TITLE
Network request failed: ECONNABORTED timeout of 10000ms exceeded AxiosError: timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by caiqinghua** [idootop/mi-gpt#25]
mac
node -v
v16.14.0

git clone https://github.com/idootop/mi-gpt
cd mi-gpt
npm install

修改 app.js
import config from "./.migpt.js";
import { MiGPT } from "./node_modules/mi-gpt/dist/index.cjs";

async function main() {
  const client = MiGPT.create(config);
  await client.start();
}

main();

node app.js

提示
Network request failed: ECONNABORTED timeout of 10000ms exceeded AxiosError: timeout of 10000ms exceeded

method: 'get',
    url: 'https://api2.mina.mi.com/sts?d=

**Comment by idootop** [comment]
网络连接超时，重试即可。

如果你是通过 clone 本项目仓库的方式来运行，记得在 `start` 之前先 `build` 一下。

```shell
pnpm  && pnpm build && pnpm start
```

另外， `start `命令默认没有注入 `.env` 文件里的环境变量。你可以在 VS Code 里按 F5 运行，会自动读取 `.env` ，或者你自己修改代码配置 `dotenv` 从 `.env` 读取环境变量。

**Comment by caiqinghua** [comment]
我用 node app.js 运行，会自动读取.env吗？

**Comment by idootop** [comment]
不会。可以参考此教程：https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs

```shell
node --env-file=.env app.js
```

**Comment by caiqinghua** [comment]
小爱音箱mini，不能用召唤傻妞 唤醒
还是要用小爱同学唤醒。

2024/06/06 11:31:51 Speaker ✅ 服务已启动...
2024/06/06 11:35:38 Speaker 🔥 打开傻妞
2024/06/06 11:35:39 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024/06/06 11:36:18 Speaker 🔊 傻妞已退出
_callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"ROM端未响应","code":3012}',
    reqID: 'd4b795ee-4c36-451f-ae38-a8604e0eb7f4'
  }
}
_callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"ROM端未响应","code":3012}',
    reqID: '0e30483c-3f54-416c-9fdf-da34a6148c1e'
  }
}

**Comment by caiqinghua** [comment]
后面小爱同学任何命令，都是提示无法连接无线网络，请按照手机客户端重新尝试。

**Comment by idootop** [comment]
小爱音箱掉线了吧，重启下小爱音箱应该就好了。

**Comment by idootop** [comment]
提示`ROM端未响应` 一般不用管，部分指令小爱音箱没有响应属于正常现象。如果出现一直唤醒小爱都没有响应的情况，说明小爱音箱内部出现了未知错误崩溃了，重启即可。

**Comment by idootop** [comment]
@caiqinghua 看你的型号应该是支持唤醒模式的。需要注意的是，在唤醒模式下，当小爱回复“说完了”的时候，才能继续和她对话，并且这个间隔不要等太久，否则她自己也会退出唤醒状态（大概10s左右），需要重新召唤“小爱同学”继续对话。

**Comment by caiqinghua** [comment]
“小爱同学，召唤傻妞”，可以起作用。
唤醒词“小爱同学”可以更改为“傻妞”吗？

**Comment by idootop** [comment]
不可以，小爱音箱的唤醒词是固件里写死的 token，外部无法自定义。要想修改只能刷机替换自己训练的语音识别模型。

**Comment by caiqinghua** [comment]
明白

**Comment by caiqinghua** [comment]
可以不要召唤傻妞，直接全部用大模型回复吗？

**Comment by caiqinghua** [comment]
VS code F5运行提示错误
Error: Provided --schema at ./prisma/schema.prisma doesn't exist.
2024/06/06 14:46:19 database ❌ 初始化数据库失败！
Uncaught Error Error: ❌ Assertion failed
    at assert (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:239:13)
    at assert (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:276:19)
    at initDB (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:1297:13)
    at processTicksAndRejections (internal/process/task_queues:96:5)
Process exited with code 1

**Comment by idootop** [comment]
额，确实有些逻辑上的冲突，下个版本我修复一下。你可以这样：

- 第一步：召唤傻妞
- 进入唤醒模式，傻妞回复：很高兴认识你。
- 后续直接对话即可，不需要再用傻妞开头了
- 退出唤醒模式后，可以再次召唤进入唤醒模式，或者直接用傻妞开头问问题。

参考这个讨论：https://github.com/idootop/mi-gpt/issues/28#issue-2337445345

**Comment by caiqinghua** [comment]
> VS code F5运行提示错误
> Error: Provided --schema at ./prisma/schema.prisma doesn't exist.
> 2024/06/06 14:46:19 database ❌ 初始化数据库失败！
> Uncaught Error Error: ❌ Assertion failed
> at assert (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:239:13)
> at assert (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:276:19)
> at initDB (/Users/lin/mi-gpt/node_modules/mi-gpt/dist/index.cjs:1297:13)
> at processTicksAndRejections (internal/process/task_queues:96:5)
> Process exited with code 1

@idootop 我的VS Code当前目录不正确，如何修改当前目录， 请问如何让当前目录的launch.json生效？

**Comment by idootop** [comment]
用 VS Code 打开你 clone 下来的 mi-gpt 项目文件夹，然后调试模式选到 `Test`（默认），启动之前先把 `tests/migpt.ts` 里面的配置修改成你自己的，并且在 mi-gpt 路径下执行以下命令：

```shell
pnpm install && pnpm build
```

![image](https://github.com/idootop/mi-gpt/assets/35302658/d5fd64fd-3d04-4fa2-b474-835f799e59e2)

**Comment by caiqinghua** [comment]
谢谢，可以了，要在vs code左侧工作区单独增加mi-gpt目录。

**Comment by caiqinghua** [comment]
2024/06/06 16:02:23 BotConfig ❌ find bot failed 请问提示这个是什么问题？

**Comment by caiqinghua** [comment]
MiGPT v3.0.1  by: del.wang
2024/06/06 16:09:28 BotConfig ❌ find bot failed
2024/06/06 16:09:32 Speaker ✅ 服务已启动...
2024/06/06 16:09:43 Speaker 🔥 打开傻妞
2024/06/06 16:09:44 Speaker 🔊 你好，我是傻妞，nice to meet you
2024/06/06 16:10:20 Speaker 🔊 傻妞已退出
2024/06/06 16:10:40 Speaker 🔥 召唤傻妞
2024/06/06 16:10:41 Speaker 🔊 你好，我是傻妞，nice to meet you
2024/06/06 16:11:15 Speaker 🔊 傻妞已退出

一直无法对话
是不是我的AZURE_OPENAI_API_KEY 不能生效？
OPENAI_BASE_URL 代码中没有使用

**Comment by idootop** [comment]
你的数据库重新初始化了，和之前的本地映射不匹配。删掉下面的文件重新运行即可：
- .bot.json 
- prisma/app.db 
- prisma/app.db-journal

或者在项目根目录下直接运行 `npm run db:rest`

**Comment by caiqinghua** [comment]
npm run db:rest
npm ERR! Missing script: "db:rest"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm run db:reset # run the "db:reset" package script
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by caiqinghua** [comment]
删除后
create bot failed

**Comment by idootop** [comment]
你执行的路径不对，自己手动删掉我上面说的那几个文件吧，等价的。

![image](https://github.com/idootop/mi-gpt/assets/35302658/e07891ef-1686-4e76-8c0c-0b81a6215eac)

**Comment by caiqinghua** [comment]
直接node app.js运行，也是报create bot failed
PrismaClientKnownRequestError:
Invalid `kPrisma.user.upsert()` invocation in
mi-gpt/dist/index.cjs:1461:25

  1458 async addOrUpdate(user) {
  1459   user.name = user.name.trim();
  1460   user.profile = user.profile.trim();
→ 1461   return kPrisma.user.upsert(
The table `main.User` does not exist in the current database.

**Comment by caiqinghua** [comment]
> 你执行的路径不对，自己手动删掉我上面说的那几个文件吧，等价的。
> 
> ![image](https://private-user-images.githubusercontent.com/35302658/337186831-e07891ef-1686-4e76-8c0c-0b81a6215eac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjMxNTMsIm5iZiI6MTcxNzY2Mjg1MywicGF0aCI6Ii8zNTMwMjY1OC8zMzcxODY4MzEtZTA3ODkxZWYtMTY4Ni00ZTc2LThjMGMtMGI4MWE2MjE1ZWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA4MzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOGMyZGUwOWI5ODYzNzQ5MmZlNzA5NjQyMzI2Y2EzNGI0MGYzYzkxOTVmZDg5ODVkNjAyZGM2OWI4NTdiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1H234tpmoFNg8nC_iOFFa5ZRdCn-1dNv3Ao0ZqOggzY)

npm run build 是可以的，
npm run db:reset 应该也可以吧？

**Comment by idootop** [comment]
不晓得什么东西被搞乱了，数据库表缺失，建议删掉重新 clone。

**Comment by idootop** [comment]
> npm run db:reset 应该也可以吧？

上面我的命令拼错了 `db:rest` -> `db:reset`
