### ISSUE TITLE
我才用nodejs模式，配置的.migpt.js不生效是什么原因呢？

### ISSUE THREAD

**Issue by kylinJWei** [idootop/mi-gpt#27]
无论.migpt.js是在 node_odules平级还是其子目录都不能生效。

**Comment by idootop** [comment]
在第三方项目中通过安装 `mi-gpt` NPM 包，需要自己配置参数和环境变量。简单讲就是，需要把你 `.migpt.js` 里的参数作为 `MiGPT` 初始化时的参数传入。示例代码：https://github.com/idootop/mi-gpt/blob/example/index.ts

**Comment by kylinJWei** [comment]
嗯，修改后配置能生效了，谢谢。
但介绍AI介绍自己的时候好像还是在代码里有一些固定信息。

**Comment by idootop** [comment]
嗯，目前并没有对外暴露修改系统 prompt 的能力。如果你需要自己定制的话，可以克隆本项目调整 prompt。
