### ISSUE TITLE
当我想部署在n1的路由器是发现固件好像不支持

### ISSUE THREAD

**Issue by w521791** [idootop/mi-gpt#3]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
04e19fceebe330ad1f40fd1ddc65b523b2b7cba2d2f182a3176a9c988657babe

**Comment by idootop** [comment]
现在docker镜像只打包了x64 平台的，你路由器芯片应该是arm64 的，架构不支持。
你可以在你电脑上先试试看能不能跑起来，自己拉下仓库打包一个arm64 的镜像。
明天周末，有时间我会尝试下打包arm64 的镜像。

**Comment by idootop** [comment]
最新镜像 `idootop/mi-gpt:latest` 已添加 arm64 支持
