### ISSUE TITLE
无论在群晖里，还是在笔记本上，都没有办法正常下载docker版本，卡 0% 然后下载失败

### ISSUE THREAD

**Issue by hkgood** [idootop/mi-gpt#31]
通过命令行的反馈是

Using default tag: latest
Error response from daemon: Head "https://registry-1.docker.io/v2/idootop/mi-gpt/manifests/latest": Get "https://auth.docker.io/token?account=rocky8848&scope=repository%3Aidootop%2Fmi-gpt%3Apull&service=registry.docker.io": EOF

**Comment by shaoyi1991** [comment]
国内镜像源配置
Docker Hub 国内镜像设置方法，解决Docker镜像拉取失败 
参考介绍：https://www.cnblogs.com/ikuai/p/18233775

**Comment by hkgood** [comment]
> 国内镜像源配置 Docker Hub 国内镜像设置方法，解决Docker镜像拉取失败 参考介绍：https://www.cnblogs.com/ikuai/p/18233775

多谢～

**Comment by idootop** [comment]
转自微信群友「今天去拉萨了吗」：国内的 docker 镜像站也都关了，目前应该只有 https://dockerproxy.com/docs  的镜像还能用

**Comment by jeffreydyy** [comment]
![image](https://github.com/idootop/mi-gpt/assets/15900071/9b92ab01-ab6c-4c7f-9b16-49192d98f883)
这个报错，是不是还是镜像拉取的问题，我把上面的地址都试了遍，还是这样。

之前按这配置启动成功过，今天换了台新的云服务器重新来，按这方法启动不了。

**Comment by idootop** [comment]
@jeffreydyy docker 网络问题，自行解决。

**Comment by Sellen0808** [comment]
sentOS阿里云服务器怎么部署
