### ISSUE TITLE
  code: 101,   message: 'ubus server or device returned invalid result'

### ISSUE THREAD

**Issue by samisme0818** [idootop/mi-gpt#32]
请教下这个是什么原因？

2024/06/06 15:05:33 Speaker 🔥 召唤路吧
2024/06/06 15:05:33 Speaker 🔊 你好，我是璐宝，很高兴认识你
_callMina failed {

  code: 101,
  message: 'ubus server or device returned invalid result',

{
    device_data: '{"msg":"ROM端未响应","code":3012}',
    reqID: 'f597b48a-492a-49c9-a5ea-2c4bc1ee254e'
  }
}

**Comment by idootop** [comment]
在 TTS 静音字符串的时候，有时会出现 ROM 端未响应的问题，可能是我选的静音字符串比较刁钻。不过基本不用管它，对功能正常运行没有影响。
```js
const kAreYouOK = "¿ʞо ∩оʎ ǝɹɐ"; // are you ok?
```
如果你发现持续出现 ROM 端未响应的问题，甚至喊小爱同学的时候都没有回复，可能这时小爱音箱内部发生了某些错误而导致崩溃死机了，关掉电源重启就好了，不影响正常使用。

**Comment by idootop** [comment]
下个版本我尝试优化下 `mute` 小爱的逻辑，降低此问题出现的概率。

**Comment by idootop** [comment]
[v3.1.0](https://github.com/idootop/mi-gpt/releases/tag/v3.1.0)版本已发布，此问题应该有所改善。
