### ISSUE TITLE
请问说话中如何打断

### ISSUE THREAD

**Issue by u2shana** [idootop/mi-gpt#38]
接入了免费的通义千问的1.8b，不知道为啥这模型主人会自己回复，AI一直巴拉巴拉说话说了几分钟断不了

**Comment by idootop** [comment]
你的小爱音箱型号是多少？在他回复的时候对他说 “小爱同学，请闭嘴”，试试看。理论上只要唤醒小爱同学，随便对他说句话就能停掉当前的 AI 回复。

**Comment by u2shana** [comment]
> 你的小爱音箱型号是多少？在他回复的时候对他说 “小爱同学，请闭嘴” 试试看。 理论上只要再次唤醒小爱同学，随便对他说句话就能停掉当前的 AI 回复。

我喊小爱同学没反应，GPT自个在那里一直说话，小爱play2019版

**Comment by idootop** [comment]
这个型号的小爱音箱我没专门测试过，但理论上应该也是能正常打断的。可能是你叫小爱同学的时候，他没听到识别出来，你把 debug 打开录一段出问题的视频，我帮你看看具体是哪里出了问题。

**Comment by thomashooo** [comment]
实测可以打断，就是不能接着问“傻妞”，要重新召唤哈
