### ISSUE TITLE
无法进入AI模式

### ISSUE THREAD

**Issue by robincuiguo** [idootop/mi-gpt#39]
设备已正常连接，偶尔也能中奖式的进入AI模式，但是始终无法跟AI互动，进入AI模式后也无法文字转语音，请问下是哪里配置有问题呢？

2024/06/07 20:21:55 Speaker ✅ 服务已启动...
2024/06/07 20:22:10 Speaker 🔥 连续对话
2024/06/07 20:22:31 Speaker 🔥 唤醒神兽
2024/06/07 20:22:31 Speaker 🔊 请稍等
2024/06/07 20:22:34 Speaker 🐛 {"playState":{"status":"idle","volume":20,"loop_type":1}}
2024/06/07 20:22:34 Speaker 🐛 checkIfHasNewMsg:false
2024/06/07 20:22:41 Open AI ✅ Answer: 龙哥，别担心，神兽傻妞一直都在呀！(*≧ω≦) 今天你想听什么故事呢？好奇心已经满满啦！
2024/06/07 20:22:42 Speaker 🔊 龙哥，别担心，神兽傻妞一直都在呀！(*≧ω≦) 今天你想听什么故事呢？好奇心已经满满啦！
2024/06/07 20:22:45 Speaker 🐛 {"playState":{"status":"idle","volume":20,"loop_type":1}}
2024/06/07 20:22:45 Speaker 🐛 checkIfHasNewMsg:false
2024/06/07 20:22:45 Speaker 🔊 我说完了
2024/06/07 20:22:48 Speaker 🐛 {"playState":{"status":"idle","volume":20,"loop_type":1}}
2024/06/07 20:22:48 Speaker 🐛 checkIfHasNewMsg:false
2024/06/07 20:23:08 Speaker 🔥 嗯朗读一首李白傻妞傻妞朗读一首李白最有名的诗
2024/06/07 20:23:24 Speaker 🔥 傻妞朗读一首李白最有名的诗

--migpt.js
    // 当消息以下面的关键词开头时，会进入 AI 唤醒状态
    wakeUpKeywords: ["打开神兽", "召唤神兽"],
    // 当消息以下面的关键词开头时，会退出 AI 唤醒状态
    exitKeywords: ["关闭", "退出", "再见"],
    // 进入 AI 模式的欢迎语
    onEnterAI: ["你好神兽"],
    // 退出 AI 模式的提示语
    onExitAI: ["宝贝已退出"],
    // AI 开始回答时的提示语
    onAIAsking: ["让我先想想", "请稍等"],
    // AI 结束回答时的提示语
    onAIReplied: ["我说完了", "还有其他问题吗"],
    // AI 回答异常时的提示语
    onAIError: ["啊哦，出错了，请稍后再试吧！"],
    // 无响应一段时间后，多久自动退出唤醒模式（默认 30 秒）
    exitKeepAliveAfter: 60,
    // TTS 指令，请到 https://home.miot-spec.com 查询具体指令
    ttsCommand: [5, 1],
    // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
    wakeUpCommand: [5, 3],
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: true,
    // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
    // playingCommand: [3, 1, 1],
    // 打开调试日志输出
    debug: true,

**Comment by idootop** [comment]
注意观察你填写的 wakeUpKeywords 列表，看看你的唤醒词有没有命中里面的词语（文字完全匹配），匹配成功才会进入唤醒模式，此时小爱同学会回复你设置的进入AI模式的欢迎语。

**Comment by idootop** [comment]
<img width="901" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/cd1cd60e-35ae-4f70-a2c0-44bd5ac2e707">

**Comment by robincuiguo** [comment]
![image](https://github.com/idootop/mi-gpt/assets/54022414/0067303a-6aa8-4e13-b6c0-1a9888087405)
上图应该说明已经进入AI模式了，但是进入AI模式后音箱灯就灭了，无法进行互动，两个问题：

**Comment by idootop** [comment]
1.  从你提供的截图和配置文件来看，你的第一句召唤神兽，与配置文件中的唤醒词并不相符，我自然认为未能唤醒进入AI模式。
2. 但根据你后续的AI回复消息来看，从AI开始第一句回复的时候，就已经进入了唤醒模式了，说明你提供的截图与配置文件内容不符。
3. 🔥最关键的，根据你的消息时间戳来看，在唤醒模式中，当小爱回答“我说完了”之后，你有超过 10s没有回复新消息，应该是小爱自己退出唤醒状态了（每次唤醒都有一定的时效，超过一段时间就没法自动续上了，这一点注意事项后面我会更新到faq里）
4. 如果进入唤醒模式后，发现对小爱说话没反应，基本就是回复的时间间隔过久了，如果小爱还没有主动提示已退出唤醒状态，那么此时可以对小爱音箱说“小爱同学，xxx（你想问的问题）”，来重新唤醒小爱继续对话，唤醒成功后即不再需要以 callAIKeywords 开头。
5.  在非唤醒（AI）模式下，消息需要以 callAIKeywords 开头才会调用 AI 回复，比如：“小爱同学，请你 xxxxx （你的问题）”。

**Comment by idootop** [comment]
这一块通过文字可能比较难理解，后面有时间我看看出一个完整的视频教程出来，讲解每个参数和常见问题到底有什么作用，应该如何处理。
另外，当前的faq确实有些注意事项没有讲清楚，如果你有更好的想法和建议，欢迎提意见和PR🤝
