### ISSUE TITLE
OpenAi回答过长的情况下小爱音箱没有读完整 LX06

### ISSUE THREAD

**Issue by kictto** [idootop/mi-gpt#40]
已经看过 https://github.com/idootop/mi-gpt/issues/14

音箱型号：小爱音箱Pro，LX06

Docker image版本：3.0.0

playingCommand: [3, 1, 1],

配置debug之后，控制台输出：

<img width="1451" alt="截屏2024-06-07 20 43 15" src="https://github.com/idootop/mi-gpt/assets/19290189/c1ddece6-8162-4543-b4d4-2ec2776f801d">

**Comment by kictto** [comment]
尝试过test的代码之后，这个型号的音箱，移除 playingCommand: [3, 1, 1] 配置之后，一切正常

**Comment by idootop** [comment]
小爱音箱Pro（LX06）不需要设置playingCommand，默认的配置文件模板就是按照这个机型配置的，开箱即用。
