### ISSUE TITLE
小爱音箱l06a无法连续对话

### ISSUE THREAD

**Issue by zhanglc** [idootop/mi-gpt#42]
我安装后完，可以调用到ai对话，但是没有办法像在视频中看到的，连续对话。看了文档，https://home.miot-spec.com/spec/xiaomi.wifispeaker.l06a，感觉没有配错，能帮忙看看我的配置么？

```js
    exitKeepAliveAfter: 30,
    // TTS 指令，请到 https://home.miot-spec.com 查询具体指令
    ttsCommand: [5, 1],
    // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
    wakeUpCommand: [5, 3],
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: true,
    // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
    playingCommand: [3, 1, 1],
```

**Comment by idootop** [comment]
你这个应该跟小米音箱 Pro 是类似的型号，不需要填写 playingCommand，把这行配置注释掉就可以。
备注：playingCommand 配置项只在默认配置（不开启）有问题的时候，再尝试填写，正常情况下用不到的。

**Comment by francofan** [comment]
的确是小米音箱pro，也的确注释了playingCommand，但是还是做不到连续问答。
每次小爱说完“还有其他问题吗”之后，并没有激活唤醒模式。

 // 无响应一段时间后，多久自动退出唤醒模式（默认 30 秒，我自己改的3000）
    exitKeepAliveAfter: 3000,
    // TTS 指令，请到 https://home.miot-spec.com 查询具体指令
    ttsCommand: [5, 1],
    // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
    wakeUpCommand: [5, 3],
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: true,
    // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
    //playingCommand: [3, 1, 1],

**Comment by idootop** [comment]
你需要先用你配置的语音指令（wakeUpKeywords）进入唤醒模式（类比，小爱技能），在唤醒模式下才能连续对话。

**Comment by idootop** [comment]
@zhanglc `wakeUpCommand` 配错了，应该是 [5, 2]，修改之后再试试看能不能连续对话。

**Comment by Undest2000** [comment]
同样遇到这个型号的问题，无法进行连续通话

**Comment by idootop** [comment]
> 同样遇到这个型号的问题，无法进行连续通话

贴一下你的配置参数，试试看这个：

```js
{
    ttsCommand: [5, 1],
    wakeUpCommand: [5, 2],
    streamResponse: true,
    //  playingCommand: [3, 1, 1],
}
```

**Comment by situZM** [comment]
我也不行，配置 wakeUpCommand: [5, 2] 了

**Comment by idootop** [comment]
@situZM 你是播放不出来声音，还是不能连续对话？L06A 不支持连续对话功能。

**Comment by situZM** [comment]
> @situZM 你是播放不出来声音，还是不能连续对话？L06A 不支持连续对话功能。

不能连续对话，然后他有视好像在自动循环放歌

**Comment by idootop** [comment]
循环放歌应该是你配置的 ttsCommand 或者 wakeUpCommand 不对，打开 debug 贴下你控制台输出的设备型号，还有你配置的那几个指令参数。

**Comment by situZM** [comment]
> 循环放歌应该是你配置的 ttsCommand 或者 wakeUpCommand 不对，打开 debug 贴下你控制台输出的设备型号，还有你配置的那几个指令参数。

2024/06/20 18:14:28 Speaker 🐛 设备信息： {
    "name": "小爱音箱Pro",
    "desc": "设备在线 ",
    "model": "xiaomi.wifispeaker.lx06",
    "rom": "1.82.5"
}

    // TTS 指令，请到 https://home.miot-spec.com 查询具体指令
    ttsCommand: [5, 1],
    // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
    wakeUpCommand: [5, 2],
    // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
    streamResponse: true,
    // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
    // playingCommand: [3, 1, 1], // 默认无需配置此参数，播放出现问题时再尝试开启
