### ISSUE TITLE
DOCKER镜像无法获得

### ISSUE THREAD

**Issue by taozhiyuai** [idootop/mi-gpt#46]
我和另外一个朋友用的都是MAC.都无法拉取镜像. 请问如何解决?

![WechatIMG105](https://github.com/idootop/mi-gpt/assets/146583103/fd8dab17-0055-4368-95d0-ed812b69fdd6)

**Comment by idootop** [comment]
网络问题，国内网络环境拉取镜像，建议配置可靠代理，近期代理节点普遍网络连接不稳定。

**Comment by idootop** [comment]
另外检查你的docker是否之前配置了国内的加速镜像，之前看新闻说国内某个docker镜像站停止服务了。

**Comment by taozhiyuai** [comment]
搞定了.
