### ISSUE TITLE
小爱音箱Play没有语音输出

### ISSUE THREAD

**Issue by BiuBiu2323** [idootop/mi-gpt#47]
![image](https://github.com/idootop/mi-gpt/assets/32856649/5854855c-3182-4a9f-b378-cddc819107b1)
有文字，但是没有语音输出，这是怎么回事呀

**Comment by idootop** [comment]
你的小爱音箱型号是？应该是你配置文件里设置的 ttsCommand不正确，具体如何配置请仔细阅读项目readme。

**Comment by a11995910** [comment]
相同问题  我的是小爱同学增强版  应该是[5,1]没错啊
![image](https://github.com/idootop/mi-gpt/assets/35448510/8e66dc02-5143-438e-bfc2-2d82b0061087)

**Comment by BiuBiu2323** [comment]
> 相同问题 我的是小爱同学增强版 应该是[5,1]没错啊 ![image](https://private-user-images.githubusercontent.com/35448510/337832064-8e66dc02-5143-438e-bfc2-2d82b0061087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjE1MTQsIm5iZiI6MTcxNzgyMTIxNCwicGF0aCI6Ii8zNTQ0ODUxMC8zMzc4MzIwNjQtOGU2NmRjMDItNTE0My00MzhlLWJmYzItMmQ4MmIwMDYxMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NWEzYTNiZjY1YTU3NDkwNzc3MjkxNzdlMDgzZjA5NWY1MWFhYWNkYTU3YWU0OWIyMDE5N2JhMTI3YzdmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UQbeE5lKcftqdiR81KG1bv3rvoTCN9GRE5H7A75ua8)

![image](https://github.com/idootop/mi-gpt/assets/32856649/02db5720-7969-493a-a041-587da155de28)
要这样，感谢idootop

**Comment by a11995910** [comment]
> > 相同问题 我的是小爱同学增强版 应该是[5,1]没错啊![图像](https://private-user-images.githubusercontent.com/35448510/337832064-8e66dc02-5143-438e-bfc2-2d82b0061087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjE1MTQsIm5iZiI6MTcxNzgyMTIxNCwicGF0aCI6Ii8zNTQ0ODUxMC8zMzc4MzIwNjQtOGU2NmRjMDItNTE0My00MzhlLWJmYzItMmQ4MmIwMDYxMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NWEzYTNiZjY1YTU3NDkwNzc3MjkxNzdlMDgzZjA5NWY1MWFhYWNkYTU3YWU0OWIyMDE5N2JhMTI3YzdmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UQbeE5lKcftqdiR81KG1bv3rvoTCN9GRE5H7A75ua8)
> 
> ![图像](https://private-user-images.githubusercontent.com/32856649/337832738-02db5720-7969-493a-a041-587da155de28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjE2NjIsIm5iZiI6MTcxNzgyMTM2MiwicGF0aCI6Ii8zMjg1NjY0OS8zMzc4MzI3MzgtMDJkYjU3MjAtNzk2OS00OTNhLWEwNDEtNTg3ZGExNTVkZTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZWZhNTI4ODNkYjdhNWVlYzUyYWJiMzcxZjhiNDRlNmNiZmM3MjI4ZDYzMTdmYTcyMWZmNjhkN2RkZmQxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1MU9112XdquTRiNWsHBfNkmwNKbXp-G5DuGw3q46jQ4) 要这样，感谢idootop

欧克了 感谢~

**Comment by BiuBiu2323** [comment]
不过我发现好像还没等ai说完，小爱就抢答了，这个应该怎么处理呢？

**Comment by MaoAnmi** [comment]
> > > 相同问题 我的是小爱同学增强版 应该是[5,1]没错啊![图像](https://private-user-images.githubusercontent.com/35448510/337832064-8e66dc02-5143-438e-bfc2-2d82b0061087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjE1MTQsIm5iZiI6MTcxNzgyMTIxNCwicGF0aCI6Ii8zNTQ0ODUxMC8zMzc4MzIwNjQtOGU2NmRjMDItNTE0My00MzhlLWJmYzItMmQ4MmIwMDYxMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NWEzYTNiZjY1YTU3NDkwNzc3MjkxNzdlMDgzZjA5NWY1MWFhYWNkYTU3YWU0OWIyMDE5N2JhMTI3YzdmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UQbeE5lKcftqdiR81KG1bv3rvoTCN9GRE5H7A75ua8)
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/32856649/337832738-02db5720-7969-493a-a041-587da155de28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjE2NjIsIm5iZiI6MTcxNzgyMTM2MiwicGF0aCI6Ii8zMjg1NjY0OS8zMzc4MzI3MzgtMDJkYjU3MjAtNzk2OS00OTNhLWEwNDEtNTg3ZGExNTVkZTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZWZhNTI4ODNkYjdhNWVlYzUyYWJiMzcxZjhiNDRlNmNiZmM3MjI4ZDYzMTdmYTcyMWZmNjhkN2RkZmQxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1MU9112XdquTRiNWsHBfNkmwNKbXp-G5DuGw3q46jQ4) 要这样，感谢idootop
> 
> 欧克了 感谢~

老哥，你的图片我看不到，你的问题是如何解决的呢
