### ISSUE TITLE
小爱音响 L05B 没有播放完 AI 的一段返回，小爱就抢答或者继续播放下一段AI返回

### ISSUE THREAD

**Issue by BiuBiu2323** [idootop/mi-gpt#48]
小爱音响 L05B 没有播放完 AI 的一段返回，小爱就抢答或者继续播放下一段AI返回，这个如何处理
![image](https://github.com/idootop/mi-gpt/assets/32856649/f9f8ee98-8cb2-43d7-bb50-653a92bf964d)

**Comment by idootop** [comment]
L05 系列的小爱音箱不支持流式响应（streamResponse），在 .migpt.js 配置文件里把 streamResponse 选项改成 false 即可。
相关 issue：
- https://github.com/idootop/mi-gpt/issues/20
- https://github.com/idootop/mi-gpt/issues/24
- https://github.com/idootop/mi-gpt/issues/21#issuecomment-2147125219

**Comment by BiuBiu2323** [comment]
感谢

**Comment by xiaobingwudi** [comment]
请问你的L05B音箱有播放gpt的声音出来吗，我的后台有方音，但是没有声音，这是我的配置

![微信截图_20240610184612](https://github.com/idootop/mi-gpt/assets/96056189/f6c76125-59a1-48af-9227-bc8f1cfdb2d6)
![微信截图_20240610184644](https://github.com/idootop/mi-gpt/assets/96056189/ec5dba2a-feea-4f47-9d7b-e6c36ec3c54d)

**Comment by idootop** [comment]
@xiaobingwudi  `wakeUpCommand` 配错了，应该填 [5, 1]

**Comment by xiaobingwudi** [comment]
谢谢&nbsp;


工薪阶层
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月14日(星期五) 晚上7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [idootop/mi-gpt] 小爱音响 L05B 没有播放完 AI 的一段返回，小爱就抢答或者继续播放下一段AI返回 (Issue #48)














 
@xiaobingwudi  wakeUpCommand 配错了，应该填 [5, 1]
