### ISSUE TITLE
小爱音箱并未转达chatgpt的回答

### ISSUE THREAD

**Issue by lyddias** [idootop/mi-gpt#5]
在docker交互日志上，程序已经成功调用chatgpt并且gpt已经给出回答，但小爱音箱并未读出回复内容，请问下可能是什么原因呢？

**Comment by lyddias** [comment]
是否在配置文件中加入tts: "xiaoai"就可以了？

**Comment by idootop** [comment]
你说的这个问题有以下几种可能：
1. 小米 TTS 有敏感词检测，一些敏感回答会被拦截
2. 小米 IoT 后端收到 tts 指令后，没有透传给本地设备
3. 本地设备收到 tts 指令后没有正常播放（指令错乱）
4. 你的设备不支持默认的 TTS 指令

其中，因为敏感词被拦截的可能性很大。

其次是因为指令错乱小爱音箱没有正确执行，此时可以重启设备试试看。

如果是每个回答都没有正确播放，则可能是你的设备不支持默认的 TTS 指令。

考虑 fork 本项目修改 TTS 指令，或自己实现 TTS 接口，接入百度，微软等 TTS 服务（本项目暂不提供第三方 TTS 的支持）

> 是否在配置文件中加入tts: "xiaoai"就可以了？

默认就是使用小米自带的 TTS

**Comment by idootop** [comment]
可以参考以下 issue：
- https://github.com/yihong0618/xiaogpt/issues/504
- https://github.com/yihong0618/xiaogpt/issues/363
> 目前已知 LX04、X10A 和 L05B L05C 可能需要使用 --use_command，否则可能会出现终端能输出GPT的回复但小爱同学不回答GPT的情况。这几个型号也只支持小爱原本的 tts.

**Comment by lyddias** [comment]
我的型号确实是L05C

**Comment by idootop** [comment]
等等吧，这两天有空我会加上一个使用 command 发送 TTS 指令的选项。

或者你动手能力强的话，也可以自己直接修改源码，欢迎 PR。

**Comment by idootop** [comment]
@lyddias  1.2.0 版本添加了 TTS 命令配置选项，你可以在这个网站上查询具体指令参数：https://home.miot-spec.com

```javascript
// .mi-gpt.js
export default {
  speaker: {
    // ...
    ttsCommand: [5, 3], // L05C
    wakeUpCommand: [5, 1], // L05C
  },
  // ...
};
```

**Comment by lyddias** [comment]
好的，谢谢！

**Comment by Ruiyuan-Zhang** [comment]
> @lyddias 1.2.0 版本添加了 TTS 命令配置选项，你可以在这个网站上查询具体指令参数：https://home.miot-spec.com
> 
> ```js
> // .mi-gpt.js
> export default {
>   speaker: {
>     // ...
>     ttsCommand: [5, 3], // L05C
>     wakeUpCommand: [5, 1], // L05C
>   },
>   // ...
> };
> ```
这个具体怎么查呢？比如说下面这个型号。
https://home.miot-spec.com/s/xiaomi.wifispeaker.l17a

**Comment by Ruiyuan-Zhang** [comment]
是这个吗
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l17a:1

**Comment by Ruiyuan-Zhang** [comment]
HARDWARE_COMMAND_DICT = {
    "LX06": "5-1",  # 小爱音箱Pro（黑色）
    "L05B": "5-3",  # 小爱音箱Play
    "S12A": "5-1",  # 小爱音箱
    "LX01": "5-1",  # 小爱音箱mini
    "L06A": "5-1",  # 小爱音箱
    "LX04": "5-1",  # 小爱触屏音箱
    "L05C": "5-3",  # 小爱音箱Play增强版
    "L17A": "7-3",  # 小爱音箱Sound Pro
    "X08E": "7-3",  # 红米小爱触屏音箱Pro
    "LX05A": "5-1",  # 小爱音箱遥控版（黑色）
    "LX5A": "5-1",  # 小爱音箱遥控版（黑色）
    # add more here
}

**Comment by idootop** [comment]
@Ruiyuan-Zhang 你的这个设备分别对应是 [7, 3] 和 [7, 1]，文档 FAQ里有图片教程。

**Comment by Ruiyuan-Zhang** [comment]
> @Ruiyuan-Zhang 你的这个设备分别对应是 [7, 3] 和 [7, 1]，文档 FAQ里有图片教程。

好的，谢谢。

另外，目前是还没有可以终止 “比较长的语音” 这个Action的是吧

**Comment by idootop** [comment]
重新唤醒小爱同学，随便说句话即可打断正在回复的内容。

**Comment by Ruiyuan-Zhang** [comment]
> 重新唤醒小爱同学，随便说句话即可打断正在回复的内容。

不行诶，我重新唤醒之后。他回答完还会继续讲上一个没回答完的问题。

比如：我问他什么是扩散模型？他会说一大堆，然后我在他说话的时候打断他问他1+1等于多少。他首先回答我2，然后再继续说上一个问题的回答

**Comment by idootop** [comment]
@Ruiyuan-Zhang 多谢反馈，长回答无法被终止的问题已修复。此修复随下一个版本更新，大概今晚我会再发一个版本。

**Comment by idootop** [comment]
@Ruiyuan-Zhang [v3.0.0](https://github.com/idootop/mi-gpt/releases/tag/v3.0.0) 版本已发布，修复了长回答无法被终止的问题。

**Comment by Ruiyuan-Zhang** [comment]
> @Ruiyuan-Zhang [v3.0.0](https://github.com/idootop/mi-gpt/releases/tag/v3.0.0) 版本已发布，修复了长回答无法被终止的问题。

收到，辛苦！！！

**Comment by idootop** [comment]
@JefferWong  打开米家看看你的小爱音箱叫什么，需要填写完整名称注意空格（比如：小爱音箱Pro）。另外，在海外服务器等非中国大陆网络环境下，也有可能会导致设备列表获取失败。
![telegram-cloud-photo-size-5-6269166936961171135-y](https://github.com/idootop/mi-gpt/assets/35302658/5ba6a706-60c1-49b1-ad7c-07c2c35e175e)

**Comment by litedad** [comment]
大佬，我的设备名称输入是正确的，但仍然显示找不到设备

**Comment by hcfong2020** [comment]
![屏幕截图_9-1-2025_212128_192 168 0 17](https://github.com/user-attachments/assets/526fcf07-6640-471c-b19a-bb7806496a8b)
后台启动了，但是无法召唤，召唤的时候没有任何提示，音箱也没有任何反应，使用的是docker。.mi.json文件也能识别到音箱，账号登录正常，用的是小米AI音箱
