### ISSUE TITLE
为啥英文提问回复说只懂中文啊，我接的是4o模型

### ISSUE THREAD

**Issue by shog86** [idootop/mi-gpt#50]
如题

**Comment by idootop** [comment]
我系统prompt是用中文写的，GPT的回复跟这也有关系。你可以fork本项目自行修改prompt语言。

**Comment by shog86** [comment]
是在哪个文件下面啊

**Comment by shog86** [comment]
我fork之后怎么部署啊

**Comment by shog86** [comment]
是得自己打包docker吗

**Comment by idootop** [comment]
是的，不过需要你有些代码基础。或者也可以等后面我加上自定义系统 prompt 的功能（排期比较靠后，近期应该不会实现）。

**Comment by shog86** [comment]
那我等等吧

**Comment by idootop** [comment]
自定义系统 Prompt 功能将会在下一版本（v4.0.0）添加支持，敬请期待。

**Comment by idootop** [comment]
MiGPT [v4.0.0](https://github.com/idootop/mi-gpt/releases/tag/v4.0.0) 版本已发布，自定义系统 Prompt 教程：https://github.com/idootop/mi-gpt/blob/main/docs/prompt.md

**Comment by shog86** [comment]
感谢大佬！

**Comment by shog86** [comment]
我在系统prompt里说了回复语言跟随query语言，但好像它没听懂，回复还是用中文。。

**Comment by idootop** [comment]
> 但好像它没听懂

所以你需要尝试各种方案，直到调教到符合你的需要为止。推荐使用 gpt-4o 模型，其他的模型理解能力都太弱了。

**Comment by shog86** [comment]
主要是不太理解配置文件里的模块到底是怎么拼成给大模型的prompt的，所以不知道该改哪里
