### ISSUE TITLE
手机里的小爱同学能否使用?

### ISSUE THREAD

**Issue by taozhiyuai** [idootop/mi-gpt#52]
长按手机电源不是可以唤醒小爱同学吗? 这个小爱同学能否也可以用mi gpt呢

**Comment by idootop** [comment]
这个项目是给小爱音箱用的哈，和手机上的小爱同学不是同样的实现，所以手机上的小爱同学没法直接用的。

**Comment by taozhiyuai** [comment]
> 这个项目是给小爱音箱用的哈，和手机上的小爱同学不是同样的实现，所以手机上的小爱同学没法直接用的。

完全不可能吗?能否支持呢?

**Comment by idootop** [comment]
小米没开放相关的接口能力，只能底层去hook破解，不在此项目的范畴内。
