### ISSUE TITLE
id和密码都配置好了，运行报错？

### ISSUE THREAD

**Issue by yykk601** [idootop/mi-gpt#55]
![error](https://github.com/idootop/mi-gpt/assets/34054059/0c5baa80-120f-48f2-adc5-1b6bf7623c90)
![error](https://github.com/idootop/mi-gpt/assets/34054059/0c5baa80-120f-48f2-adc5-1b6bf7623c90)
id和密码都配置好了，运行报错？

**Comment by idootop** [comment]
登录小米账号失败，请检查你填写的账号密码是否正确。如果确认无误，请到小米账号官网登录一下你的账号，看能否正常登录。
