### ISSUE TITLE
提示找不到设备

### ISSUE THREAD

**Issue by thatscode** [idootop/mi-gpt#56]
报错提示找不到设备，修改了设备名称也不行，不确定是不是不支持此型号，我从哪里可以获得支持的设备型号的列表么？
PS：这个设备名称跟「米家App」里是保持一致的。

设备型号：Mi Smart Clock 4 inch
我嫌原始名称太长，改成了Mi Smart Clock，但是报错找不到设备；就改成了Clock，还是提示找不到。

报错信息：
```
> mi-gpt@3.0.0 start
> node ./app.js



/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$
| $$\  $ | $$| $$| $$  \ $$| $$         | $$
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$
|__/     |__/|__/ \______/ |__/         |__/

         MiGPT v3.0.0  by: del.wang


找不到设备：Mi Smart Clock
2024/06/08 17:23:17 Speaker ❌ 初始化 Mi Services 失败
2024/06/08 17:23:17 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/app/dist/index.cjs:239:13)
    at __Logger.assert (/app/dist/index.cjs:276:19)
    at AISpeaker.initMiServices (/app/dist/index.cjs:451:17)
    at async AISpeaker.run (/app/dist/index.cjs:695:5)
    at async main (file:///app/app.js:6:3)

> mi-gpt@3.0.0 start
> node ./app.js



/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$
| $$\  $ | $$| $$| $$  \ $$| $$         | $$
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$
|__/     |__/|__/ \______/ |__/         |__/

         MiGPT v3.0.0  by: del.wang


找不到设备：Clock
2024/06/08 17:28:44 Speaker ❌ 初始化 Mi Services 失败
2024/06/08 17:28:44 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/app/dist/index.cjs:239:13)
    at __Logger.assert (/app/dist/index.cjs:276:19)
    at AISpeaker.initMiServices (/app/dist/index.cjs:451:17)
    at async AISpeaker.run (/app/dist/index.cjs:695:5)
    at async main (file:///app/app.js:6:3)
```

**Comment by thatscode** [comment]
Info Update：用家里另外一台小米设备测试，提示启动成功了，继续去把玩下功能了~ 😁
PS：设备型号 「Xiaomi 智能家庭屏 Pro 8」

```
> mi-gpt@3.0.0 start
> node ./app.js



/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$
| $$\  $ | $$| $$| $$  \ $$| $$         | $$
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$
|__/     |__/|__/ \______/ |__/         |__/

         MiGPT v3.0.0  by: del.wang


2024/06/08 17:40:36 Speaker ✅ 服务已启动...
```

**Comment by idootop** [comment]
这个问题后面我优化下，在debug模式下面输出当前的设备列表，按照列表里的名称或did正确填写即可。

**Comment by darkrain88** [comment]
MiGPT v3.0.0  by: del.wang

找不到设备：小爱音箱play

找不到设备：小爱音箱play

2024/06/09 05:08:01 Speaker ❌ 初始化 Mi Services 失败

2024/06/09 05:08:01 database ❌  Error: ❌ Assertion failed

    at _LoggerManager.assert (/app/dist/index.cjs:239:13)

    at __Logger.assert (/app/dist/index.cjs:276:19)

    at AISpeaker.initMiServices (/app/dist/index.cjs:451:17)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async AISpeaker.run (/app/dist/index.cjs:695:5)

    at async main (file:///app/app.js:6:3)

**Comment by darkrain88** [comment]
容器 启动不了， 怎么进入debug模式 did肯定正确的。

**Comment by idootop** [comment]
@darkrain88 我猜你的设备名称是小爱音箱Play而不是小写的play

**Comment by darkrain88** [comment]
> @darkrain88 我猜你的设备名称是小爱音箱Play而不是小写的play

> mi-gpt@3.0.0 start

> node ./app.js

/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$

| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/

| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   

| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   

| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   

| $$\  $ | $$| $$| $$  \ $$| $$         | $$   

| $$ \/  | $$| $$|  $$$$$$/| $$         | $$   

|__/     |__/|__/ \______/ |__/         |__/                         

                                                                                                                 

         MiGPT v3.0.0  by: del.wang

2024/06/09 08:52:00 Speaker ✅ 服务已启动...

但是我输入did 怎么不对呢

**Comment by idootop** [comment]
检查下你填写的did是否真的就是你当前设备的did。登录成功后在.mi.json文件下面有保存的你当前设备的信息，里面有真实的did。
