### ISSUE TITLE
不能在小爱音响上独立运行吗？

### ISSUE THREAD

**Issue by alex13by** [idootop/mi-gpt#58]

**Comment by idootop** [comment]
小爱音箱的系统并不开放，想要直接在小爱音箱上定制运行任何程序，都需要拆机，刷机来破解，不在此项目的涉及范围内。更多细节参考此处：https://github.com/idootop/mi-gpt/issues/21#issuecomment-2147125219

**Comment by alex13by** [comment]
多谢解答
