### ISSUE TITLE
怎么直接在终端使用文字使用，不用通过小爱音箱

### ISSUE THREAD

**Issue by FenghenHome** [idootop/mi-gpt#61]
如题：怎么直接在终端使用文字使用，不用通过小爱音箱

**Comment by FenghenHome** [comment]
或者能对接https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web吗

**Comment by thatscode** [comment]
像你描述的这种在命令行调用GPT等大模型的工具不是一大堆么 [doge]

**Comment by idootop** [comment]
暂无此功能的开发计划，感兴趣的可以自行 fork 修改本项目。
