### ISSUE TITLE
Speaker ❌ 初始化 Mi Services 失败

### ISSUE THREAD

**Issue by imhsz** [idootop/mi-gpt#62]
![image](https://github.com/idootop/mi-gpt/assets/3312454/c4e4e38e-9f0a-45ce-b8f8-db2e7a74cda6)
MiNA一直失败,
奇怪的是sid == 'xiaomiio'时(MiIOT)就可以;
几次调用后,超时的是这个url:
https://api2.mina.mi.com/sts?d=android_4547db82-1011-47a5-abe6-51ca90e20aa2&ticket=0&pwd=1&p_ts=1717921003000&fid=0&p_lm=1&auth=ZNU6XgpTRCbLIReQtEMnQaUFSawkA8%2FyXqddNuhjXx8xv3DaMRZLlSzedFNg7uj%2FKF2GVsS%2FlfMUO47aiWgFV00vibb4qjtTrpgW6IGzpK0qIr9Vf3L7G%2FtQqQQjcd1Vwkzsfpd%2FaLqNXLo93B%2F%2FospnLKFF6AuAZzjbqJ6i9%2FQ%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CN&p_idc=China&nonce=kzbZtcoNxnkBtOPQ&_ssign=du3rNDzoyxeLBSk%2FzhTlrEW0R98%3D&_userIdNeedEncrypt=true&clientSign=3x%2BTLolMsb4cQGap1xNGJByY6Dg%3D

**Comment by idootop** [comment]
你试试看在浏览器开代理登录下你的小米账号，然后过个大概半个小时重新启动下。

**Comment by imhsz** [comment]
没用,挂clash默认也是走国内;挂上去,浏览器访问小米没问题,访问https://api2.mina.mi.com/sts?d=android_4547db82-1011-47a5-abe6-51ca90e20aa2&ticket=0&pwd=1&p_ts=1717921003000&fid=0&p_lm=1&auth=ZNU6XgpTRCbLIReQtEMnQaUFSawkA8%2FyXqddNuhjXx8xv3DaMRZLlSzedFNg7uj%2FKF2GVsS%2FlfMUO47aiWgFV00vibb4qjtTrpgW6IGzpK0qIr9Vf3L7G%2FtQqQQjcd1Vwkzsfpd%2FaLqNXLo93B%2F%2FospnLKFF6AuAZzjbqJ6i9%2FQ%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CN&p_idc=China&nonce=kzbZtcoNxnkBtOPQ&_ssign=du3rNDzoyxeLBSk%2FzhTlrEW0R98%3D&_userIdNeedEncrypt=true&clientSign=3x%2BTLolMsb4cQGap1xNGJByY6Dg%3D 这个就是不行

**Comment by imhsz** [comment]
[image: image.png]

Del ***@***.***> 于2024年6月9日周日 21:21写道：

**Comment by idootop** [comment]
你手机上下载个米家登录试试看呢？米家登录的时候时候走到mina的登录流程的，验证一下。

**Comment by imhsz** [comment]
因为家里有小爱,我手机一直登着米家

**Comment by idootop** [comment]
退出重新登录

**Comment by idootop** [comment]
看你第一张图发的，只是登录超时，看不出来哪里有毛病。

**Comment by imhsz** [comment]
手机重登没问题.
我跟踪代码,发现请求了很多个登录接口,一直验证不过,最后到这个超时的,这个超时的我在浏览器访问也是超时.

**Comment by idootop** [comment]
不太好调试，看起来你这个账号登录行为比较特殊。如果你能接受的话，可以在我个人[公众号后台](https://del.wang/about)，私发一下你的账号密码，我帮你本地联调下（联调完再把密码改掉）

**Comment by imhsz** [comment]
已发账号密码

**Comment by idootop** [comment]
@imhsz 破案了，MIoT 查询到的设备名称和米家里设置的不一致（中间多出来一个空格）。
等下一个版本修复这个问题后，你可以填写设备真实的 `did` 来解决此问题。


<img width="1038" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/34131dae-87af-4854-bbb9-85a0639d0230">

**Comment by idootop** [comment]
或者你也可以先在米家中把设备名称改成带空格的，也能正常用。

**Comment by idootop** [comment]
@imhsz [v3.1.0](https://github.com/idootop/mi-gpt/releases/tag/v3.1.0)版本已发布，修复了此问题。

**Comment by imhsz** [comment]
还是不行,我原来就是抄米家带空格的,刚刚把米家空格和配置里去掉了.另外之前也手动设置过did.

**Comment by imhsz** [comment]
IOT是有的，是MiNA没有，也是MiNA最后超时了

**Comment by imhsz** [comment]
第一次登录失败
![image](https://github.com/idootop/mi-gpt/assets/3312454/374a3b76-2af9-446a-91e7-a1af2bceea0f)
这里被重置
![image](https://github.com/idootop/mi-gpt/assets/3312454/beb62c82-0354-4719-ac51-508fbf4615fb)
未定义
![image](https://github.com/idootop/mi-gpt/assets/3312454/141cedfa-ae2b-43a5-9bfb-49dc4c88343a)
![image](https://github.com/idootop/mi-gpt/assets/3312454/f8301818-9eda-48cd-af11-e17f83a139be)
然后，结束再起，报超时：
![image](https://github.com/idootop/mi-gpt/assets/3312454/e1344328-adff-4468-999a-bd7665d25923)

**Comment by idootop** [comment]
网络问题。昨天你的账号在我本地测试 mina 可以正常获取到 device。

**Comment by imhsz** [comment]
我在公司和家里都一样的问题，网络环境这个我认为概率不大

**Comment by imhsz** [comment]
访问https://api2.mina.mi.com/sts?d=android_4547db82-1011-47a5-abe6-51ca90e20aa2&ticket=0&pwd=1&p_ts=1717921003000&fid=0&p_lm=1&auth=ZNU6XgpTRCbLIReQtEMnQaUFSawkA8%2FyXqddNuhjXx8xv3DaMRZLlSzedFNg7uj%2FKF2GVsS%2FlfMUO47aiWgFV00vibb4qjtTrpgW6IGzpK0qIr9Vf3L7G%2FtQqQQjcd1Vwkzsfpd%2FaLqNXLo93B%2F%2FospnLKFF6AuAZzjbqJ6i9%2FQ%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CN&p_idc=China&nonce=kzbZtcoNxnkBtOPQ&_ssign=du3rNDzoyxeLBSk%2FzhTlrEW0R98%3D&_userIdNeedEncrypt=true&clientSign=3x%2BTLolMsb4cQGap1xNGJByY6Dg%3D 这个就是不行，我这浏览器都打不开，你那可以吗

**Comment by idootop** [comment]
昨天用你的账号测试一切正常，可成功登录 Mina 和 MioT 并获取到设备列表。所以我说是网络原因。

**Comment by idootop** [comment]
控制台输出的日志链接，应该没法直接在浏览器打开，需要带上 cookie 访问才有效

**Comment by idootop** [comment]
@imhsz 上海电信网络，使用你昨天提供给我的账号登录一切正常：

<img width="1225" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/18f50a17-07e9-4573-a467-601a3ac9ae92">

**Comment by ryanlxb** [comment]
我的方法是给设备改个名字就行了

**Comment by idootop** [comment]
经过测试 @imhsz 的设备一切正常，可完美进行连续对话。上面登录超时的问题是因为他在本地 clone 了项目后，代码和 build 后的 dist 产物不是最新版本，存在一些潜在的冲突。更新到最新代码重新 build 后，可以正常使用了。

**Comment by loks666** [comment]
> 手机重登没问题.
> 
> 我跟踪代码,发现请求了很多个登录接口,一直验证不过,最后到这个超时的,这个超时的我在浏览器访问也是超时.

老哥你的设备是LX05A吗？

**Comment by badandboy** [comment]
"pincodeType": 0,
            "fw_version": "1.84.143",
            "needVerifyCode": 0,
            "isPasswordEncrypt": 0
        },
        "uid": 172176347,
        "pd_id": 3961,
        "password": "",
        "p2p_id": "",
        "rssi": -30,
        "family_id": 0,
        "reset_flag": 0
    }
}
2025/04/18 11:21:38 Speaker ❌ 初始化 Mi Services 失败
2025/04/18 11:21:38 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:270:13)
    at __Logger.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:307:19)
    at AISpeaker.initMiServices (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:487:17)
    at async AISpeaker.run (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:759:5)



我遇到同样的问题

不过我不是超时问题

**Comment by badandboy** [comment]
我登陆OK了，看到了返回的设备列表

**Comment by badandboy** [comment]
我上面还部署了另外一个服务，就是xiaomusic，有没有可能是这个原因导致的

**Comment by idootop** [comment]
@badandboy 一般是因为你的 miot 或 mina 设备列表里找不到对应的设备，可以打开 debug 看下 返回的 miot、mina 设备列表里你的设备的 did 是多少。
