### ISSUE TITLE
docker方式可以运行，node.js方式运行为啥说用户名密码有问题？

### ISSUE THREAD

**Issue by yykk601** [idootop/mi-gpt#63]
![image](https://github.com/idootop/mi-gpt/assets/34054059/667a3910-0bc1-4d01-b040-c803b877a0b1)

**Comment by idootop** [comment]
有点怪，发下你的完整 index.ts 代码看看（账号密码可以加**打码）

**Comment by yykk601** [comment]
可能是我编译的问题，现在好了
