### ISSUE TITLE
我有个大胆的想法，能否集成一个开源的比如IP摄像头项目，给小爱加上眼睛看到我们～～

### ISSUE THREAD

**Issue by shinedlc** [idootop/mi-gpt#65]
ts代码能力有限，我目前看到另外一个开源项目，也是ts版本的，原本是做一个AI眼镜的项目，
目前硬件看起来就只有一个拍照 + 蓝牙传图片给模型解析，最后抛给chatgpt去根据图片描述，来回复用户问题：
https://github.com/BasedHardware/OpenGlass/
如果能结合，是不是花几十块，让小爱能看到我们！！
![WechatIMG732](https://github.com/idootop/mi-gpt/assets/147293123/3b9a670a-dc18-432b-b276-4b143952b6a4)

**Comment by idootop** [comment]
从硬件上来讲，更需要的是一台可以自定义的带音响的摄像头哈哈哈。技术上都很容易实现，关键是没有厂商肯开放硬件能力接口，无法自定义。要想完全的自主可控要自己搭开发版玩了。或者也可以利用废旧手机，应该也刚刚好。

**Comment by shinedlc** [comment]
有需要的自取。需接入摄像头硬件 + 本机搭建ollama模型：https://github.com/shinedlc/mi-gpt

**Comment by idootop** [comment]
@shinedlc  牛 👍

**Comment by gantrol** [comment]
我看智慧屏有摄像头，比如[Xiaomi 智能家庭屏 Pro 8](https://home.miot-spec.com/s/xiaomi.wifispeaker.x8f)，不过不清楚有没有接口控制

**Comment by idootop** [comment]
@gantrol 看了下 MIoT 的开放接口，是没有获取摄像头相关能力的接口的。

**Comment by yihong0618** [comment]
小米摄像头应该就可以，我之前玩过这个东西不难实现的。

**Comment by idootop** [comment]
@yihong0618 多谢推荐👍有机会可以买一个来搞搞玩

**Comment by idootop** [comment]
@shinedlc 已经把这个项目加到推荐里了，欢迎提 PR 更新来源里你的个人主页链接。

<img width="919" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/c9bb6cee-0482-424c-996f-270980a60cb4">
