### ISSUE TITLE
是否能支持火山云tts websocket 模式的  豆包低层用的他

### ISSUE THREAD

**Issue by openainext** [idootop/mi-gpt#66]
https://www.volcengine.com/docs/6561/79821

**Comment by idootop** [comment]
对火山TTS的支持，近期几个版本会优先添加支持。

**Comment by idootop** [comment]
演示视频中的熊二等音色，在火山TTS里就有的。

**Comment by xumeng** [comment]
请问作者，豆包TTS接入的教程或资料是否有呢。
目前我沿着火山引擎的文档在配置，不知路线是否正确。
```
TTS_DOUBAO=https://openspeech.bytedance.com/api/v1/tts
#SPEAKERS_DOUBAO=豆包 TTS 音色列表接口
```
https://www.volcengine.com/docs/6561/79820

@idootop

**Comment by idootop** [comment]
现在还没这个功能呢，下几个版本才会支持火山引擎的TTS。那个是豆包TTS的配置（即演示视频中用到的音色），不对外开放。

**Comment by idootop** [comment]
此功能将会在下一版本（v4.0.0）添加支持，敬请期待。

**Comment by xumeng** [comment]
> 此功能将会在下一版本（v4.0.0）添加支持，敬请期待。

牛逼，期待。
有没有自己折腾的换语音方向可以指点一二。

**Comment by chaoqunxie** [comment]
> 此功能将会在下一版本（v4.0.0）添加支持，敬请期待。

希望能支持gpt-sovits

**Comment by ryanlxb** [comment]
目前支持访问的大模型 是不是只有 openai？ 看描述中也支持 通义千问 和  豆包，想问问怎么配置呢？

**Comment by idootop** [comment]
可以网上搜下oneapi，可以把豆包等模型的接口转换成OpenAI的格式，然后替换下baseURL就好了。

**Comment by idootop** [comment]
MiGPT [v4.0.0](https://github.com/idootop/mi-gpt/releases/tag/v4.0.0) 版本已发布，使用第三方 TTS 教程：https://github.com/idootop/mi-gpt/blob/main/docs/tts.md
