### ISSUE TITLE
新手docker运行报错求助

### ISSUE THREAD

**Issue by liliy886** [idootop/mi-gpt#67]
本人以为萌新，不太懂代码，然后就用了docker，把项目下载到e盘以后，再右键用powershell运行，复制docker运行代码后，显示无法运行，还请帮忙，感谢！
![无标题1](https://github.com/idootop/mi-gpt/assets/167604682/8e42f445-7721-461e-aaa7-03dc426fe30c)
![无标题2](https://github.com/idootop/mi-gpt/assets/167604682/54c033d9-adab-488e-af47-aa31ddc9dfcb)

**Comment by idootop** [comment]
试试这个
```shell
docker run -d --env-file $pwd\.env `
    -v $pwd\.migpt.js:/app/.migpt.js `
    idootop/mi-gpt:latest
```

**Comment by liliy886** [comment]
> 试试这个
> 
> ```shell
> docker run -d --env-file $pwd\.env `
>     -v $pwd\.migpt.js:/app/.migpt.js `
>     idootop/mi-gpt:latest
> ```
> 
> 或者
> 
> ```shell
> docker run -d --env-file $pwd\.env -v $pwd\.migpt.js:/app/.migpt.js idootop/mi-gpt:latest
> ```

大神回的也太快了，感谢！！第一个不行，您说的第二个代码可以运行，然后在docker里面就有Contaniner了，docker启动以后，重新插拔了一下音箱，但是我对着小爱音箱pro说了我自己设定的唤醒词没反应，请问是还要对音箱或者网络进行什么设置吗？谢谢！

**Comment by liliy886** [comment]
另外，请问一下这3个指令是什么作用？谢谢
tsCommand	小爱音箱 TTS 指令（[可在此查询](https://home.miot-spec.com/)）	[5, 1]
wakeUpCommand	小爱音箱唤醒指令（[可在此查询](https://home.miot-spec.com/)）	[5, 3]
playingCommand | 查询小爱音箱是否在播放中指令（可在此查询） | [3, 1, 1]

**Comment by idootop** [comment]
要这样唤醒（假设你的唤醒词是召唤傻妞）：“小爱同学，召唤小爱”。前面的小爱同学是唤醒小爱音箱开始接收语音文字输入，后面再跟你设置的唤醒词

**Comment by idootop** [comment]
这 3 个指令的含义readme里面有介绍，如果你是小爱音箱Pro，这几个命令不需要修改，默认就是按照小爱音箱Pro设置的。

**Comment by liliy886** [comment]
感谢大神，确实可以了，先说小爱以后就能唤醒，真的很好玩！感觉就是买了个看不见的机器人，哈哈哈！另外，我接的moonshot的模型，请问大神，国产模型有推荐的么？能精准回答问题的，同时讲话比较生动~
最后，还有个不情之请，我在火山模型里面买了付费的语音包，但是不懂使用，能简单介绍下如何把火山的语音接入到这里面吗？十分感谢！ 
![无标题3](https://github.com/idootop/mi-gpt/assets/167604682/011183b4-b49d-4681-9233-adc2815009ad)

**Comment by idootop** [comment]
国产模型用的不多，但好像最近阿里发布了很牛逼可以对标gpt4o 的开源模型，不晓得其他厂商有没有跟进。
另外关于火山引擎TTS能力，暂时还没添加支持。既然你已经买了，我争取早点加一下这个功能吧，预计下一两个版本更新此功能。

**Comment by liliy886** [comment]
> 国产模型用的不多，但好像最近阿里发布了很牛逼可以对标gpt4o 的开源模型，不晓得其他厂商有没有跟进。 另外关于火山引擎TTS能力，暂时还没添加支持。既然你已经买了，我争取早点加一下这个功能吧，预计下一两个版本更新此功能。

真心感谢~~~!!
