### ISSUE TITLE
建一个微信群，方便大家交流

### ISSUE THREAD

**Issue by chmod777john** [idootop/mi-gpt#69]
我看到 Readme 里面好像还没有群聊。大家可能有很多小问题，不足以构成 issue ，但是可以在群里发问

![image](https://github.com/idootop/mi-gpt/assets/146207719/22780388-e5da-4d10-8067-348e4f06537c)

**Comment by idootop** [comment]
@chmod777john  我看又新建了一个 issue，是同一个群，留一个就好，这个先关掉了哈。
