### ISSUE TITLE
Azure OpenAI 支持吗

### ISSUE THREAD

**Issue by WangNingkai** [idootop/mi-gpt#7]

**Comment by idootop** [comment]
默认不支持 Azure OpenAI，感兴趣的话可以按照 https://www.npmjs.com/package/openai 文档自己定制，欢迎 PR。
<img width="798" alt="image" src="https://github.com/idootop/mi-gpt/assets/35302658/8dc62b64-db6f-4648-8269-204e8b2e6f54">

**Comment by idootop** [comment]
[v2.0.0](https://github.com/idootop/mi-gpt/releases/tag/v2.0.0) 版本已添加支持，请按 [OpenAI 文档](https://github.com/openai/openai-node/blob/d7d5610d91573740d7e3c27e4afde5650ee6e349/src/index.ts#L370C28-L370C48)配置相应环境变量。

**Comment by shog86** [comment]
> [v2.0.0](https://github.com/idootop/mi-gpt/releases/tag/v2.0.0) 版本已添加支持，请按 [OpenAI 文档](https://github.com/openai/openai-node/blob/d7d5610d91573740d7e3c27e4afde5650ee6e349/src/index.ts#L370C28-L370C48)配置相应环境变量。

请问在env里设置了endpoint和key之后，设置model的变量还是 OPENAI_MODEL吗？

**Comment by idootop** [comment]
@shog86  模型变量名称 OPENAI_MODEL 不变

**Comment by shog86** [comment]
所以Azure的话设置endpoint，key，model三个变量就行是吧，和OpenAI的一样，deployment不用设置哈？

**Comment by shog86** [comment]
Azure的日志来了，求分析，响应了提示语，但缺参数得不到回复

2024/06/06 01:39:01 Speaker ✅ 服务已启动...
2024/06/06 01:39:29 Speaker 🔥 请你介绍一下美国儿科学会
2024/06/06 01:39:30 Speaker 🔊 请稍等
/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/index.js:163
            throw new Errors.OpenAIError("The OPENAI_API_VERSION environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).");
                  ^

OpenAIError: The OPENAI_API_VERSION environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).
    at new AzureOpenAI (/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/index.js:163:19)
    at OpenAIClient._init (/app/dist/index.cjs:1066:51)
    at OpenAIClient.chatStream (/app/dist/index.cjs:1128:10)
    at _MyBot.chatWithStreamResponse (/app/dist/index.cjs:2291:12)
    at _MyBot.ask (/app/dist/index.cjs:2273:33)
    at async AISpeaker._askAIForAnswerSteps.res.response (/app/dist/index.cjs:990:20)
    at async AISpeaker.askAIForAnswer (/app/dist/index.cjs:1024:19)
    at async AISpeaker.onMessage (/app/dist/index.cjs:739:24)

Node.js v20.14.0

**Comment by idootop** [comment]
补一下 OPENAI_API_VERSION 环境变量，具体填什么值，查一下 OpenAI 的使用文档

**Comment by shog86** [comment]
> 补一下 OPENAI_API_VERSION 环境变量，具体填什么值，查一下 OpenAI 的使用文档

完了之后是需要重启容器，还是删掉重启docker run？

**Comment by idootop** [comment]
直接删了重启吧

**Comment by shog86** [comment]
2024-05-13，像这样的是不是要用双引号包起来了？算字串了

**Comment by shog86** [comment]
现在长这样，晚上回家试试
<img width="266" alt="Server Box 2024-06-06 12 33 49" src="https://github.com/idootop/mi-gpt/assets/19712631/5a0b38f9-272a-4332-b1ba-c1662874d8ca">

**Comment by shog86** [comment]
![image](https://github.com/idootop/mi-gpt/assets/19712631/1be8bfaf-f03d-4c55-9ec7-7cc2c6f803e5)

**Comment by shog86** [comment]
![image](https://github.com/idootop/mi-gpt/assets/19712631/ff0914eb-2c76-4cd3-8ef0-d0839e548d4e)

另外在前面还有个这错误

**Comment by shog86** [comment]
从你的报错信息来看，这是一个典型的 HTTP 404 错误，即“资源未找到”（Resource Not Found）。这是由于在调用 Azure OpenAI API 时，指定的资源或端点不存在或无法找到。

以下是可能的解决步骤和检查点：

1. **检查 URL 和端点**:
    - 确保你使用的 API URL 是正确的。在某些情况下，拼写错误或路径错误可能导致找不到资源。
    ```javascript
    const apiUrl = "https://your-correct-endpoint.azure.com/path";
    ```

2. **检查 API 路径和版本**:
    - 确保你使用的 API 路径和版本是正确的。不正确的路径可能会引发 404 错误。

3. **检查资源 ID**:
    - 在请求中，如果需要特定资源 ID，请确认该 ID 是正确且存在的。

4. **确保资源已部署**:
    - 确保你在 Azure Portal 上正确地部署并配置了 OpenAI 服务和相关资源。

5. **查看 API 请求参数**:
    - 有时请求参数错误也可能导致 404 错误，确保参数名称和格式正确无误。

6. **Azure OpenAI 服务状态**:
    - 检查 Azure 服务的状态页面，确保没有运行维护或中断事件。

7. **示例代码校验**:
    - 确保你调用 API 的代码没有语法或逻辑错误。以下是一个调用 Azure OpenAI API 的示例代码：
    ```javascript
    const openai = require('openai');

    const apiKey = "your-api-key";
    openai.apiKey = apiKey;

    const apiClient = new openai.AzureOpenAI({
        baseUrl: "https://your-correct-endpoint.azure.com/path", // 确保此URL是正确的
        apiKey: apiKey,
    });

    async function fetchOpenAIData() {
        try {
            const response = await apiClient.chatStream({
                model: "model-id", // 确保模型ID是有效的
                messages: [
                    { role: "user", content: "Hello!" }
                ]
            });
            console.log(response);
        } catch (error) {
            console.error("Error:", error);
        }
    }

    fetchOpenAIData();
    ```

如果以上步骤都无法解决问题，建议查看详细的 API 文档或联系 Azure 支持团队获取更多帮助。

**Comment by shog86** [comment]
<img width="399" alt="Server Box 2024-06-07 08 56 00" src="https://github.com/idootop/mi-gpt/assets/19712631/8822f70b-4b53-45bf-9c4a-8abf72c78979">
成了

env里长这样
<img width="260" alt="image" src="https://github.com/idootop/mi-gpt/assets/19712631/bd6aa5ce-1f00-409c-bf1b-3f4da538a647">
API version要按Playground里示例代码那样写，不能按Azure部署那儿显示的写

**Comment by jooekong** [comment]
@shog86 @idootop 
请教两位大佬，azure openai还是遇到404报错， .env配置如下, 镜像是最新的6.22的，这是哪里配置的有问题吗？ 敏感信息用xxx替代了
```
deployment=gpt-4o
OPENAI_API_VERSION=2024-02-15-preview
AZURE_OPENAI_API_KEY=xxx
AZURE_OPENAI_ENDPOINT=https://xxxx.openai.azure.com/
AZURE_OPENAI_DEPLOYMENT=gpt-4o-2024-0513(OpenAI)
```

**Comment by idootop** [comment]
@jooekong 感觉像是这样

```shell
OPENAI_API_VERSION=2024-02-15-preview
AZURE_OPENAI_API_KEY=xxx
AZURE_OPENAI_ENDPOINT=https://xxxx.openai.azure.com
AZURE_OPENAI_DEPLOYMENT=gpt-4o
```

**Comment by jooekong** [comment]
> @jooekong 感觉像是这样
> 
> ```shell
> OPENAI_API_VERSION=2024-02-15-preview
> AZURE_OPENAI_API_KEY=xxx
> AZURE_OPENAI_ENDPOINT=https://xxxx.openai.azure.com
> AZURE_OPENAI_DEPLOYMENT=gpt-4o
> ```

这样也不行。。怎么打开debug日志？看看拼出来的url啥的，抓包太麻烦了

**Comment by idootop** [comment]
@jooekong  用的 OpenAI 的 SDK，没有打印日志的开关
