### ISSUE TITLE
一进入唤醒就会蹦出来一首歌，如然后一直自动关闭和开启，退出后歌曲自动关闭

### ISSUE THREAD

**Issue by WSXYT** [idootop/mi-gpt#71]
一进入唤醒就会蹦出来一首歌，如然后一直自动关闭和开启，退出后歌曲自动关闭

**Comment by WSXYT** [comment]
小爱触屏音箱，wakeUpCommand: [5, 3]，怎么打开debug qwq

**Comment by WSXYT** [comment]
噢对了顺便说一下怎么把AI 开始回答时的提示语和AI 结束回答时的提示语关了qwq

**Comment by WSXYT** [comment]
而且我的回复一直带小爱：这个文字，我说不要带这个之后在下次仍然有

**Comment by WSXYT** [comment]
哦还有这个怎么控制家电qwq

**Comment by idootop** [comment]
@WSXYT 

> 怎么打开debug

在 .migpt.js 里配置 speaker 的 debug 属性未 true

```js
{
    speaker:{
        debug: true,
        // ...
    }
}
```

> 怎么把AI 开始回答时的提示语和AI 结束回答时的提示语关了

```js
{
    speaker:{
        // AI 开始回答时的提示语
        onAIAsking: ["¿ʞо ∩оʎ ǝɹɐ"],
        // AI 结束回答时的提示语
        onAIReplied: ["¿ʞо ∩оʎ ǝɹɐ"],
        // ...
    }
}
```

> 怎么控制家电

这个功能还没上线，TODO

> 我的回复一直带小爱：这个文字，我说不要带这个之后在下次仍然有

没太理解什么意思。现在对话默认是会记录前面 10 条消息的上下文的，前面的旧消息可能会影响后面的回复。

**Comment by fengsixin** [comment]
同样的问题，进入唤醒模式 音箱就自动跳QQ音乐@@！

**Comment by idootop** [comment]
@fengsixin 进入唤醒模式后，每说一句话都会播放音乐，还是只在进入的时候播放？你进入唤醒模式的提示语是什么？感觉这个现象是小爱音箱把你的唤醒语识别成了歌名，然后自动播放了。

**Comment by WSXYT** [comment]
> @WSXYT
> 
> > 怎么打开debug
> 
> 在 .migpt.js 里配置 speaker 的 debug 属性为 true
> 
> ```js
> {
>     speaker:{
>         debug: true,
>         // ...
>     }
> }
> ```
> 
> > 怎么把AI 开始回答时的提示语和AI 结束回答时的提示语关了
> 
> ```js
> {
>     speaker:{
>         // AI 开始回答时的提示语
>         onAIAsking: ["¿ʞо ∩оʎ ǝɹɐ"],
>         // AI 结束回答时的提示语
>         onAIReplied: ["¿ʞо ∩оʎ ǝɹɐ"],
>         // ...
>     }
> }
> ```
> 
> > 怎么控制家电
> 
> 这个功能还没上线，TODO
> 
> > 我的回复一直带小爱：这个文字，我说不要带这个之后在下次仍然有
> 
> 没太理解什么意思。现在对话默认是会记录前面 10 条消息的上下文的，前面的旧消息可能会影响后面的回复。

意思是每次聊天的时候前面都会有“小爱”这个字，例如“小爱：你好”前面的这个“小爱”是真实存在并且会读出来的

**Comment by idootop** [comment]
prompt 的的问题，下个版本可以自定义系统 prompt，你可以调教她开头不要读出来自己的名字。

**Comment by idootop** [comment]
> 同样的问题，进入唤醒模式 音箱就自动跳QQ音乐@@！

@fengsixin 发下你的设备型号和配置的 command 参数看看，也有可能是你的 wakeUpCommand 设置的不正确。

**Comment by fengsixin** [comment]
上一个问题跳出QQ音乐问题，参数修改后已解决。

**Comment by idootop** [comment]
只要你的本地模型 API 符合 OpenAI API 规范就能正常用。感觉还是你设置的问题。
