### ISSUE TITLE
您好，L05B,在后台可以看到有回复，但是小爱音箱没有声音

### ISSUE THREAD

**Issue by xiaobingwudi** [idootop/mi-gpt#72]
![微信截图_20240610184612](https://github.com/idootop/mi-gpt/assets/96056189/1c7da315-f397-4b2f-ab46-da363bf3b1ae)
![微信截图_20240610184644](https://github.com/idootop/mi-gpt/assets/96056189/bb099fff-4080-49bb-944c-40af7886e043)
这是设置和后台反应的截图

**Comment by WSXYT** [comment]
什么型号的

**Comment by xiaobingwudi** [comment]
L05B的型号

**Comment by xiaobingwudi** [comment]
这个是L05B查询结果，麻烦帮我看看吧
![屏幕截图_10-6-2024_185732_home miot-spec com](https://github.com/idootop/mi-gpt/assets/96056189/83906b3e-5799-4465-80a0-44a4eabef93a)

**Comment by idootop** [comment]
@xiaobingwudi 

```js
ttsCommand: [5,3],
wakeUpCommand: [5,1],
```

**Comment by xiaobingwudi** [comment]
谢谢大佬，指令设置后，就可以有声音了，我在宝塔终端输入pnpm start,运行蛮好，但是关掉终端，小爱音箱就无法用gpt了，这个如何设施呀

**Comment by idootop** [comment]
可以用 docker run -d 后台运行，或者用 nohup 让其在后台运行。具体搜索下 linux 后台任务如何保活。
