### ISSUE TITLE
启动程序后显示此次登录需要安全验证

### ISSUE THREAD

**Issue by xt851231** [idootop/mi-gpt#73]
我是使用node.js 安装 migpt 后，根据示例代码写的 app.js ，
app.js 代码：

import { MiGPT } from "mi-gpt";

const botName = "小宅";
const botProfile = `
性别：男
性格：调皮捣蛋
爱好：喜欢搞怪，喜欢二次元
`;

const masterName = "涛酱";
const masterProfile = `
性别：男
性格：善良正直
其他：总是舍己为人，是小宅的主人。
`;

async function main() {
  const client = MiGPT.create({
    speaker: {
      userId: "8xxxxxxx", // 注意：不是手机号或邮箱，请在「个人信息」-「小米 ID」查看
      password: "xxxxxxxx", // 账号密码
      did: "Xiaomi Sound Pro", // 小爱音箱 ID 或在米家中设置的名称
      callAIKeywords: ["请", "你", "小宅"],
      // 当消息以下面的关键词开头时，会进入 AI 唤醒状态
      wakeUpKeywords: ["打开", "进入", "召唤"],
      // 当消息以下面的关键词开头时，会退出 AI 唤醒状态
      exitKeywords: ["关闭", "退出", "再见"],
      // 进入 AI 模式的欢迎语
      onEnterAI: ["你好，我是小宅，主人有什么吩咐"],
      // 退出 AI 模式的提示语
      onExitAI: ["小宅退下了，有什么需要再召唤我哦"],
      // AI 开始回答时的提示语
      onAIAsking: ["让我先想想", "请稍等"],
      // AI 结束回答时的提示语
      onAIReplied: ["我说完了", "还有其他问题吗"],
      // AI 回答异常时的提示语
      onAIError: ["啊哦，出错了，请稍后再试吧！"],
      // 无响应一段时间后，多久自动退出唤醒模式（默认 30 秒）
      exitKeepAliveAfter: 30,
      // TTS 指令，请到 https://home.miot-spec.com 查询具体指令
      ttsCommand: [7, 1],
      // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
      wakeUpCommand: [7, 3],
      // 是否启用流式响应，部分小爱音箱型号不支持查询播放状态，此时需要关闭流式响应
      streamResponse: true,
      // 查询是否在播放中指令，请到 https://home.miot-spec.com 查询具体指令
      // playingCommand: [3, 1, 1],
    },
    bot: {
        name: botName,
        profile: botProfile,
      },
    master: {
        name: masterName,
        profile: masterProfile,
      }
  });
  await client.start();
}

main();

启动后就一直显示以下error。已经超过30分钟了。还是一直显示这个error.

此次登录需要安全验证，请在浏览器打开以下链接，并按照提示授权验证账号（注意：授权成功后，大约需要等待 30 分钟左右账号信息才会更新，请在更新后尝试重新登录）:
 https://account.xiaomi.com/identity/authStart?sid=micoapi&context=5mDX6Rtas7F2CLVGzKhHMPNmzrzr6RyJTuR9flxCS5ipfxQNN0ixW8lFF0W0MVEhY4tHg8WmiMtX38YWX8PpdCj7HzuZRcjg0YZ8WJNeWFz7bTXjwWYGmbTE_B4ucWp8MEjh61HWz1Tz1iCy07UPr9_XhZjljAUrK1p_wa0UsJVs6T4o8XG0MkBzZ_HFoUPc7a5IrDMWIVYortnaRPmmxyUolIkoN3_N9DGROVFEzbzXNbhPfodZNwOIpCpT386fXHdtlvMOeEsAoW8AJ6W4I3MWCwG2jUjypOP4kJIx9-6z2sNWjw51HWB_mLFU_Y6Ef5Red2ajeAujVC5gP7EksU00xWTY02fidF-5wt8Pj4rWBHg5uFJsQVbFJrUtHHy2EzPsGFEu5V-G7ZDXHc4ECov8_C2GaQa8oQD3UUlBY0mc9Kpu5L26aiM8xfEnp0IW6d-2dcfjfxXMrFJGTU-iGYur9lsOYiK2T9FGAREurqX9wzuhrnZ7weKPKOqOsKRWSQS8D1iw678SP9WPluMd45DdX9ufT8bbKCBToj-V37aqbm6O_M0hT3W5QqgR3wZ9NRsJeAFVaLz0vo3_g4nDZX2o2pSoixwsyMFQCXm-0ktLCZtxoai6T-YXvFD1NfDDloAUADvcqFlgEocCNng5oJu9r2kIuOjQiT_IPsdiTm8koL6NY0nsLSj2o7DcrrkgTPA0fYaFhJdLJzSWU_5SPjx7OWDnpUxQmqryDuKtreaPi1sIviHs38AV7TBK3mxAdEnd_ghxSnERUZwownbDZS9c6_2LsaPR94fCKn8665WwceYEPvp1Sd_3eae-U5Ma&_locale=ja_JP
login failed &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=micoapi&context=5mDX6Rtas7F2CLVGzKhHMPNmzrzr6RyJTuR9flxCS5ipfxQNN0ixW8lFF0W0MVEhY4tHg8WmiMtX38YWX8PpdCj7HzuZRcjg0YZ8WJNeWFz7bTXjwWYGmbTE_B4ucWp8MEjh61HWz1Tz1iCy07UPr9_XhZjljAUrK1p_wa0UsJVs6T4o8XG0MkBzZ_HFoUPc7a5IrDMWIVYortnaRPmmxyUolIkoN3_N9DGROVFEzbzXNbhPfodZNwOIpCpT386fXHdtlvMOeEsAoW8AJ6W4I3MWCwG2jUjypOP4kJIx9-6z2sNWjw51HWB_mLFU_Y6Ef5Red2ajeAujVC5gP7EksU00xWTY02fidF-5wt8Pj4rWBHg5uFJsQVbFJrUtHHy2EzPsGFEu5V-G7ZDXHc4ECov8_C2GaQa8oQD3UUlBY0mc9Kpu5L26aiM8xfEnp0IW6d-2dcfjfxXMrFJGTU-iGYur9lsOYiK2T9FGAREurqX9wzuhrnZ7weKPKOqOsKRWSQS8D1iw678SP9WPluMd45DdX9ufT8bbKCBToj-V37aqbm6O_M0hT3W5QqgR3wZ9NRsJeAFVaLz0vo3_g4nDZX2o2pSoixwsyMFQCXm-0ktLCZtxoai6T-YXvFD1NfDDloAUADvcqFlgEocCNng5oJu9r2kIuOjQiT_IPsdiTm8koL6NY0nsLSj2o7DcrrkgTPA0fYaFhJdLJzSWU_5SPjx7OWDnpUxQmqryDuKtreaPi1sIviHs38AV7TBK3mxAdEnd_ghxSnERUZwownbDZS9c6_2LsaPR94fCKn8665WwceYEPvp1Sd_3eae-U5Ma&_locale=ja_JP","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
此次登录需要安全验证，请在浏览器打开以下链接，并按照提示授权验证账号（注意：授权成功后，大约需要等待 30 分钟左右账号信息才会更新，请在更新后尝试重新登录）:
 https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=wmesJ7Nnp0xIT3TfFAWksUo-cZV4f9SePvoJLxI2aw00SCFRlIinLI72DsiuQwhaSEmnSG21z0uJQC77KgSH8qzd23TKyXcYraWNEnHfHoKGJHh1lNyARnX3lg2RL8yMSNl3mBW_1GRatt4YXnRoNTjZRwBQKQuRdVBkt-Z3dGrbgRARGBGTnCqF3t2AzPRpfH1XiuCgsE2fgQUcTs0y8ibkbMkughySPDHJQeQ2L2OBIw1ABmfdimyWvlom2j_Jafb6hlenpXU33hysSDuCvZnHeVta21C7anNF9LiN9FCYB8oAfXU-e3wbNrUAUqdcDVjG2oBjRLuoJ8INb0MH7LoKXQC7ehA9YuA631-VZi5sWlKocCH23m0icpNqe1oVSQ2PLFvVnDLW9jylYGOYL-F2zVj21FUIwb-_A0cpxBLHMaiY-xlEhJE8YwHUZV5n5LGTwnvaM30X-SUTAmMZvOrJVyUU3sAUx9U8veq7-OQuvc6BFxv7SKdrM9TUvXpwA_YnImFOwfgkHrb7MuJVJOzdVKWIpYE--uBhvjLX33KJ1IK8tHULZQ2Hykx6W5i6WN1uiB2ZtJornvOpESiHOuLI6RkebThxRGmPi6IgkJKRHx3VculL0OJ09FFUx1W2ua0yjrdZjJpnXs-jwlnPZwpzFoxMHBb39E_npSW048C16KgKrE2JSe8L0mV6_IgXqwocgs3s6RFVZxCNnwhUA55rHQoie02vJQF7tZMWVP4Ln0LD7uKrsa8fBwIoFs_11eoaM4OQjgPSp7eSTkNJsw86Hs4mZiABscTXYAMUzCRyoesoUXR9K5fccWyNRMmo&_locale=ja_JP
login failed &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=wmesJ7Nnp0xIT3TfFAWksUo-cZV4f9SePvoJLxI2aw00SCFRlIinLI72DsiuQwhaSEmnSG21z0uJQC77KgSH8qzd23TKyXcYraWNEnHfHoKGJHh1lNyARnX3lg2RL8yMSNl3mBW_1GRatt4YXnRoNTjZRwBQKQuRdVBkt-Z3dGrbgRARGBGTnCqF3t2AzPRpfH1XiuCgsE2fgQUcTs0y8ibkbMkughySPDHJQeQ2L2OBIw1ABmfdimyWvlom2j_Jafb6hlenpXU33hysSDuCvZnHeVta21C7anNF9LiN9FCYB8oAfXU-e3wbNrUAUqdcDVjG2oBjRLuoJ8INb0MH7LoKXQC7ehA9YuA631-VZi5sWlKocCH23m0icpNqe1oVSQ2PLFvVnDLW9jylYGOYL-F2zVj21FUIwb-_A0cpxBLHMaiY-xlEhJE8YwHUZV5n5LGTwnvaM30X-SUTAmMZvOrJVyUU3sAUx9U8veq7-OQuvc6BFxv7SKdrM9TUvXpwA_YnImFOwfgkHrb7MuJVJOzdVKWIpYE--uBhvjLX33KJ1IK8tHULZQ2Hykx6W5i6WN1uiB2ZtJornvOpESiHOuLI6RkebThxRGmPi6IgkJKRHx3VculL0OJ09FFUx1W2ua0yjrdZjJpnXs-jwlnPZwpzFoxMHBb39E_npSW048C16KgKrE2JSe8L0mV6_IgXqwocgs3s6RFVZxCNnwhUA55rHQoie02vJQF7tZMWVP4Ln0LD7uKrsa8fBwIoFs_11eoaM4OQjgPSp7eSTkNJsw86Hs4mZiABscTXYAMUzCRyoesoUXR9K5fccWyNRMmo&_locale=ja_JP","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
2024/06/10 19:07:20 Speaker ❌ 初始化 Mi Services 失败
2024/06/10 19:07:20 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (file:///home/xt851231/code_example/MiGPT/node_modules/mi-gpt/dist/index.js:231:13)
    at __Logger.assert (file:///home/xt851231/code_example/MiGPT/node_modules/mi-gpt/dist/index.js:268:19)
    at AISpeaker.initMiServices (file:///home/xt851231/code_example/MiGPT/node_modules/mi-gpt/dist/index.js:443:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AISpeaker.run (file:///home/xt851231/code_example/MiGPT/node_modules/mi-gpt/dist/index.js:687:5)
    at async main (file:///home/xt851231/code_example/MiGPT/app.js:58:3)

**Comment by xt851231** [comment]
现在好了，之前已经打开链接验证过了，但过了40分钟，还是登不上。不过刚才又试了下，已经好了。

**Comment by xt851231** [comment]
不过现在的虽然通过验证了，也能进入对话模式和正常离开对话模式，但进入后再问他问题就没反应了。  
2024/06/10 23:03:45 Speaker ✅ 服务已启动...
2024/06/10 23:04:11 Speaker 🔥 帮我呼叫小宅
2024/06/10 23:04:25 Speaker 🔥 召唤小白
2024/06/10 23:04:29 Speaker 🔊 你好，我是小宅，主人有什么吩咐
2024/06/10 23:05:09 Speaker 🔊 小宅退下了，有什么需要再召唤我哦
2024/06/10 23:07:39 Speaker 🔥 召唤小白
2024/06/10 23:07:43 Speaker 🔊 你好，我是小宅，主人有什么吩咐

**Comment by idootop** [comment]
打开 debug 看下日志

**Comment by Xu768212312** [comment]
部署在宝塔的docker 如何搞出现这个

**Comment by idootop** [comment]
@Xu768212312 看看上面我回答的处理方法，项目常见问题文档里也有讲这个问题应该怎么处理。

**Comment by idootop** [comment]
简单来说，就是在你本地打开浏览器，在小米官网手动登录一下你的小米账号，如果你的服务器是在海外，最好打开代理登录小米账号。登录成功后过个 10 多分钟再重新运行应该就能正常登录了。
