### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by WSXYT** [idootop/mi-gpt#74]
> mi-gpt@3.0.0 start
> node ./app.js

/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
| $$\  $ | $$| $$| $$  \ $$| $$         | $$   
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
|__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                 
         MiGPT v3.0.0  by: del.wang

login failed &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=micoapi&context=_OHBVfqIq3QMGuXauICYEooF3sx4bg_AsdclPmD_DyNBwKqhQRSQKOGPI6gDBjVl6UPu65hoYyBBBQymJLQhHbiekzo6MPz9rE1zeMu1nOmk0JRdmSg0-d-Tws5W5_jAIAaOUCiJI4UTi4Z30FIUCskfXElxFUv4q6khF84R4jU2ObNRM6ibB7UjpsQZhyN2t7ZSTOsjUPhJ8CNKW4okGN0BCHoQgbvRazNs5_OleLrn_xpSmxfS3Wz8Xhs4okSkbos34jKqqWpx6b6BOhxtqPm7aZqqsp8hzBV5O2n-CBQ98_Pq2YrEKaOm_dJAomOmSKmgDPnCAUi7NXYs18lKLSILQl5_UtjgZP_WmAYCjMKA-DcPY6dchD4WjEnVKaTJrKV6u4C_edmbXmidrnr8a4NFtgxxAw7rRy4MegZ2qtBkyhQ8b5uxttA6Catdrg9ZqCCnyR1HVf9wGCqMp23aW5l_IyhFtsy582X4vPQ3YYf5y_IehO7v1Xh3K-wv5zCC8jk2VO2iI5vWpyGTH8y6n1zwZpRanlf22N8J2sk3ealhyirHUAbM1lCK-tFHsjC-SBvVJhLjmj9NaD4E4m5Y7l_gBxcqqxV203sfzsQnzcRemuvya5d4PrnLYkFYfxA7EbqTT9UP4M3tCL7GUnJdDyJymtgtBKzQ0NJqNJmJnPZjBWBzWV7sVuS53-T0fUsWJsLTkzIkWCSFbb3cqwCMifXm96aX1F3uLY5gTKoyQj4YmuKAS9Tb-TeUJ8hlvCn-Riol4SSgkeh0wHvo-DDTaH2ygDjN8rmLf8jZWORMLVN7w2uLB_-25bi6yBoBtNZi&_locale=zh_CN","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
login failed &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=VbmPec2np5Un5sdhDUUMzWoAUsgpUvxbUkyWFwduRbVjzHmc0J-eKXxck_fo4QgaMwBDZds30pURDsX0st1A8koW5J774UvG0lq_5fhMjUw8LS2QkSkDP7Er8uW0fSiGG3ahcBKf70cwO3PA2Ha2o4QEZtU84FaoScNGIlljaMQj_ajxGIGnsXV1vLDCnC9oWQZTwHJ3eCeKMQPKPndj8fhqMYqhQyeyMumZXMNcYudBQh7a_9-x-L_YqvhYf6_2WqA2Msedyiy007-ZgwhfAIswuDFfPkUJNUtZyNO9lwCFMjM9Dpq3pMjBLK1lhV4T9yPh-gPfMby4sbD8r7vIi2Uh7aGdGRJEO5vJ30ha5VeNa0p_vxBepHZrUtDGQrVsrO901fgkhjzhUv0X7ANR3O_KBttIA-6DXt2Y1wDZDJRjTQWQDvj-PdnEugj6RIOrpUMkGF5FZ1RKOnhZ24ieL37aS8sAHn5SuY-5P3Q3_4Nn7NQ2G2TXycRU2ENTdUzVyi-nR20js0zFBEcHxBhDDcWUfb0EzCReKPXt3227HEw6qoWiZ3nLKUme4io9EdMsKw6euJzj_hZSV1E7mdYm1_8l1wyxXJe_3mdnNTcMPk1ixK2Y0KRHTeDuEChe5TgbX8PUcGol2rpcL6GPLycpufVA6VE4CO6utAwrAgY2utLTylW5WOlN8JcpF2J0Y1HdL7u9eTZKCtwnuHIbCKdI1Cr7HWORHTfWJtft4BejqKOKxcnwySIz8Ts5ZBMH5r6lG91jTFihNltMWlgXSOKc4Ah5BpL4ZttNPJBZoVS4C1ScWi1UvB8MRdHBpLcVG2Ls&_locale=zh_CN","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
2024/06/10 12:59:57 Speaker ❌ 初始化 Mi Services 失败
2024/06/10 12:59:57 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/app/dist/index.cjs:239:13)
    at __Logger.assert (/app/dist/index.cjs:276:19)
    at AISpeaker.initMiServices (/app/dist/index.cjs:451:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AISpeaker.run (/app/dist/index.cjs:695:5)
    at async main (file:///app/app.js:6:3)

**Comment by huangzhenhao90** [comment]
应该是挂着代理导致的，可以关掉试一下，或者挂着代理登录一下小米账号，然后再试。我在另外的 issue看到的。

**Comment by idootop** [comment]
这个提示是因为你的小米账号触发了异地登录保护，需要手动安全验证。用你运行 MiGPT 的机器的网络，打开小米官网，登录你的小米账号，手动通过安全验证即可。

**Comment by dragenxp** [comment]
请问下，我想部署到服务器上，这种情况，服务器上没有浏览器有什么办法解决吗？

**Comment by dragenxp** [comment]
> 这个提示是因为你的小米账号触发了异地登录保护，需要手动安全验证。用你运行 MiGPT 的机器的网络，打开小米官网，登录你的小米账号，手动通过安全验证即可。
> 
> 

请问下，我想部署到服务器上，这种情况，服务器上没有浏览器有什么办法解决吗？

**Comment by idootop** [comment]
在你本地登录也可以，如果你的服务器是在海外，你可以在本地打开代理登录小米账号，服务器IP访问不是必要的。

**Comment by WSXYT** [comment]
> 在你本地登录也可以，如果你的服务器是在海外，你可以在本地打开代理登录小米账号，服务器IP访问不是必要的。

我服务器是国内阿里云，不行

**Comment by idootop** [comment]
国内也一样，触发了异地登陆安全验证机制，要到浏览器登录一下小米账号官网，然后等个半小时后再重启试试。

**Comment by zhusjfaker** [comment]
> 国内也一样，触发了异地登陆安全验证机制，要到浏览器登录一下小米账号官网，然后等个半小时后再重启试试。

是要一直让浏览器挂着吗？ 我这等了一个晚上还是报错

**Comment by sooden** [comment]
> 这个提示是因为你的小米账号触发了异地登录保护，需要手动安全验证。用你运行 MiGPT 的机器的网络，打开小米官网，登录你的小米账号，手动通过安全验证即可。

请问怎么手动通过安全验证？复制这段链接用浏览器打开，接收验证码通过验证后页面返回了“ok”不过好像没用，等1个小时，等1天了，等几天都试过了，还是这样。本地部署也一样。您说的打开小米官网，登录小米账号，手动通过安全验证，我找不到手动通过安全验证在哪里。头大！-_-!

**Comment by wptad** [comment]
我跟你的情况一样

**Comment by zhou-xuan** [comment]
跟你的情况一样，本地node运行（非docker），一直报“小米账号触发了异地登录保护”，不管手动验证后等待多长时间，始终报这个错！求赐教解决方法~
