### ISSUE TITLE
镜像docker pull doopt/mi-gpt:latest在哪下载？

### ISSUE THREAD

**Issue by gaozhichang** [idootop/mi-gpt#79]
精选docker pull doopt/mi-gpt:latest在哪下载？

**Comment by idootop** [comment]
要先在电脑上安装好 docker，建议先学习下 docker 的用法，然后按照 readme 里的命令，会自动下载镜像并运行。

**Comment by idootop** [comment]
如果镜像下载失败，参考[常见问题](https://github.com/idootop/mi-gpt/blob/main/docs/faq.md)文档里的配置 docker 国内镜像部分，或在网上自行搜索学习如何给 docker 配置国内下载镜像。
