### ISSUE TITLE
无法进入AI 唤醒状态

### ISSUE THREAD

**Issue by lyddias** [idootop/mi-gpt#8]
配置了wakeUpKeywords唤醒词，但程序无法进入AI唤醒状态，截图如下：
<img width="1427" alt="97b8292b9755f1fa07f119e4336a3b3" src="https://github.com/idootop/mi-gpt/assets/11193951/cfdcb58c-579d-4d5b-bb7d-10c14667132c">
<img width="819" alt="1716565718269" src="https://github.com/idootop/mi-gpt/assets/11193951/482916a4-76ed-4e3a-8218-738aad33c9de">

**Comment by idootop** [comment]
唤醒词行为后面修改过，忘了更新文档。
现在默认会在后面补上当前的 bot 名称，比如：
wakeUpKeywords: ['打开', '召唤', '进入']  + botName: '豆包'
实际唤醒词对应为： 打开豆包、召唤豆包、进入豆包

下个版本我按照你当前这种使用方式，调整下唤醒词行为。

**Comment by lyddias** [comment]
刚才试了一下你说明的方式，确实进入了AI唤醒状态，但是音箱未播放AI的输出。这和之前的ttsCommand是不是一个问题。

**Comment by idootop** [comment]
你能通过 callAIPrefix 唤起 ChatGPT 的回答，说明 ttsCommand 配的是正确的。有相关的输出日志截图吗？

**Comment by idootop** [comment]
[v2.0.0](https://github.com/idootop/mi-gpt/releases/tag/v2.0.0) 版本已修复

**Comment by shog86** [comment]
AI唤醒模式是啥意思啊，进入模式之后不用再叫小爱同学，可以连续对话了？我看进入模式之后灯就一直亮着，我是小爱mini

**Comment by idootop** [comment]
是的，类似召唤小爱技能。官方的小爱技能现在个人开发者不让注册了，只能通过此方式曲线救国。
