### ISSUE TITLE
小米智能家庭屏-小爱同学成功接入

### ISSUE THREAD

**Issue by Hongwing** [idootop/mi-gpt#80]
![image](https://github.com/idootop/mi-gpt/assets/15857517/b2bf1454-5abd-474a-aebd-4cc64ef50cb7)![Pasted Graphic](https://github.com/idootop/mi-gpt/assets/15857517/961c8973-0a51-49f2-80e0-41ea993f669c)

**Comment by Hongwing** [comment]
@idootop 应该也是可以集成其他tts吧

**Comment by Hongwing** [comment]
@idootop 语音可以阅读，但是阅读部分后，就直接“我说完了”，无法全部读完

**Comment by idootop** [comment]
感谢分享。

> 应该也是可以集成其他tts吧

下个版本，添加对第三方 TTS 服务的支持和相关教程

> 语音可以阅读，但是阅读部分后，就直接“我说完了”，无法全部读完

大概率是因为查询设备播放状态失败，可以到常见问题里找找看相关问题和 issue

**Comment by Hongwing** [comment]
> 感谢分享。
> 
> > 应该也是可以集成其他tts吧
> 
> 下个版本，添加对第三方 TTS 服务的支持和相关教程
> 
> > 语音可以阅读，但是阅读部分后，就直接“我说完了”，无法全部读完
> 
> 大概率是因为查询设备播放状态失败，可以到常见问题里找找看相关问题和 issue

可能是流式响应 对声音比较敏感，
尝试关闭流式：streamResponse: false 后，可以慢悠悠完整读完了
