### ISSUE TITLE
小度音响能用吗

### ISSUE THREAD

**Issue by xianyu110** [idootop/mi-gpt#83]
可以适配一下小度音响吗

**Comment by idootop** [comment]
目前暂无其他品牌音箱的适配计划（比如小度，天猫精灵，苹果等）

这个要看其他品牌的音箱有没有开放接口，之前我简单调研过一圈，看下来好像只有米家的音箱开放能力（相对）完善一些。

**Comment by TotoWang-hhh** [comment]
> 目前暂无其他品牌音箱的适配计划（比如小度，天猫精灵，苹果等）
> 
> 这个要看其他品牌的音箱有没有开放接口，之前我简单调研过一圈，看下来好像只有米家的音箱开放能力（相对）完善一些。

小度那玩意不是安卓吗？要不楼主考虑一下直接用openai自家安卓端，或者有条件的话上gemini？
