### ISSUE TITLE
请问“小爱同学”这个唤醒词能改么？比如改成“小米小米”之类的？

### ISSUE THREAD

**Issue by gantrol** [idootop/mi-gpt#84]

**Comment by idootop** [comment]
不可以，小爱音箱的唤醒词（小爱同学，xxx）是固件里写死的 token，外部无法自定义。要想修改只能刷机替换自己训练的语音识别模型。

相关讨论：
- https://github.com/idootop/mi-gpt/issues/25#issuecomment-2151395738
- https://github.com/idootop/mi-gpt/issues/21

**Comment by gantrol** [comment]
> 不可以，小爱音箱的唤醒词（小爱同学，xxx）是固件里写死的 token，外部无法自定义。要想修改只能刷机替换自己训练的语音识别模型。
> 
> 相关讨论：
> 
> * [Network request failed: ECONNABORTED timeout of 10000ms exceeded AxiosError: timeout of 10000ms exceeded #25 (comment)](https://github.com/idootop/mi-gpt/issues/25#issuecomment-2151395738)
> * [自定义语音听写Api的支持 #21](https://github.com/idootop/mi-gpt/issues/21)

好的，谢谢回复

**Comment by thisissirz** [comment]
> > 不可以，小爱音箱的唤醒词（小爱同学，xxx）是固件里写死的 token，外部无法自定义。要想修改只能刷机替换自己训练的语音识别模型。
> > 相关讨论：
> > 
> > * [Network request failed: ECONNABORTED timeout of 10000ms exceeded AxiosError: timeout of 10000ms exceeded #25 (comment)](https://github.com/idootop/mi-gpt/issues/25#issuecomment-2151395738)
> > * [自定义语音听写Api的支持 #21](https://github.com/idootop/mi-gpt/issues/21)
> 
> 好的，谢谢回复

可以通过曲线救国的方式，用其他语音识别模块触发调用小米无线开关，然后小米无线开关可以唤醒小爱音箱，可以改任意昵称，可以找找，b站有教程。
