### ISSUE TITLE
我想用nodejs运行，怎么将.env中的参数也可以在.js中定义并引用，示例只有.migps.js没有.env的

### ISSUE THREAD

**Issue by victorli-cn** [idootop/mi-gpt#85]

**Comment by idootop** [comment]
一个简单粗暴的方法是，直接给  process.env.[key] 赋值，但不建议这么做。
推荐在启动node项目的时候从.env读取相关配置，可以用 node --env-file，或者 dotenv。具体如何操作，自己网上搜一下教程吧。

**Comment by 54huanan** [comment]
安装依赖：
npm install dotenv -S  --registry=https://registry.npmmirror.com
使用变量：
```
import dotenv from 'dotenv';
// 加载 .env 文件中的环境变量
dotenv.config();
```
这样就可以了
