### ISSUE TITLE
没有报错信息，但是输出的话没有在小爱同学音响说出来，这是哪里有问题呢？ 小爱音响Play的版

### ISSUE THREAD

**Issue by alphandbelt** [idootop/mi-gpt#87]
![image](https://github.com/idootop/mi-gpt/assets/28209685/7c170ab0-1842-463e-92d6-8b6961c20dbe)

**Comment by idootop** [comment]
配置文件里 ttsCommand 和 wakeUpCommand配得不正确。没记错的话，play是[5,1],[5,3]，顺序刚好换过来。

**Comment by idootop** [comment]
@alphandbelt  看看这里的配置参数填没填对：https://github.com/idootop/mi-gpt/issues/92

**Comment by alphandbelt** [comment]
> @alphandbelt 看看这里的配置参数填没填对：#92

可以了，谢谢!

**Comment by alphandbelt** [comment]
> 配置文件里 ttsCommand 和 wakeUpCommand配得不正确。没记错的话，play是[5,1],[5,3]，顺序刚好换过来。可以了，谢谢。

**Comment by zhengguodong** [comment]
我的也是，有输出，但音响没有声响。看了下之前说的配置，应该没啥问题，也是小米音箱play。求助

**Comment by idootop** [comment]
@zhengguodong 小爱音箱 Play 有好几个版本，打开 bebug 看下你用的到底是哪个型号，然后贴下你的型号和配置的 ttsCommand、wakeUpCommand

**Comment by zhengguodong** [comment]
> @zhengguodong小爱音箱Play有好几个版本，打开bebug看你用的到底是哪个型号，然后贴下你的型号和配置的ttsCommand、wakeUpCommand

![image](https://github.com/idootop/mi-gpt/assets/83534401/7273d00c-d36e-4945-ab4f-c4e0ad8502c9)
好了，我改成这样就好了

**Comment by zhengguodong** [comment]
![image](https://github.com/idootop/mi-gpt/assets/83534401/8c9984fe-a4d5-4dce-a925-59e9d5da6800)
woh我会报错，设备状态异常，是什么原因造成的

**Comment by idootop** [comment]
连续多次获取设备播放状态失败了，可能是 ROM 端响应超时，可以尝试把配置文件里的 speaker.timeout 调大（单位毫秒，默认值 3000，3 秒）
```js
{
    speaker:{
        timeout: 10 * 1000, // 超时调到 10s 试试看
    }
}
```

**Comment by zhengguodong** [comment]
![image](https://github.com/idootop/mi-gpt/assets/83534401/462ad809-abf6-419a-88ad-160537f7f0ac)
会有个这个问题，不知道怎么造成的。版本是l05b

**Comment by idootop** [comment]
@zhengguodong 你的设备不支持连续对话模式，这是提示你把流式响应关闭之后就不能再继续使用连续对话模式了。
