### ISSUE TITLE
docker启动不起来但是没有报错

### ISSUE THREAD

**Issue by funnykeke** [idootop/mi-gpt#88]
启动命令：
docker run --rm --env-file /Users/funnykeke/Everything/projects/mi-gpt-3.1.0/.env -v /Users/funnykeke/Everything/projects/mi-gpt-3.1.0/.migpt.js:/app/.migpt.js idootop/mi-gpt:latest

.env.  .migpt.js已经修改好了

启动后打印
2024/06/14 00:55:30 Speaker ✅ 服务已启动...

然后就不动了，小爱音箱说话也不打印

**Comment by idootop** [comment]
试试对小爱音箱说“小爱同学，你好”，有没有打印“你好”
