### ISSUE TITLE
小爱音箱播放回答的问题不完整

### ISSUE THREAD

**Issue by lyddias** [idootop/mi-gpt#9]
AI返回的回答结果，自动拆分成2条，但小爱音箱只播放后1条，导致回答不完整
<img width="1428" alt="0ca8e1791748dabcf0c84541e8ec73b" src="https://github.com/idootop/mi-gpt/assets/11193951/3f3a7759-1543-4172-b483-a7040e5ea694">

**Comment by idootop** [comment]
小米默认的 TTS 理论上后面的回答会在上一句讲完后再继续播放，之前我在本地只测试了豆包的 TTS。
周末有时间我会复现修复下这个问题。
顺便问一下，你的设备型号是什么？

**Comment by lyddias** [comment]
L05C
