### ISSUE TITLE
小爱音箱HD 查询指令问题

### ISSUE THREAD

**Issue by romantech** [idootop/mi-gpt#91]
您好，我用的是小爱音箱HD。
我在 [home.miot-spec](https://home.miot-spec.com/spec/onemore.wifispeaker.sm4) 上查了一下指令，没有找到 Intelligent-speaker，只有Speaker，Play Control， Microphone。
如果这样的话我的音箱就不能配置mi-gpt吗？

![20240614_183816](https://github.com/idootop/mi-gpt/assets/8604840/634769ef-136a-4365-b9b4-e8b2b2121f9f)

**Comment by idootop** [comment]
是的，这款音箱不支持小爱。

<img width="604" alt="image" src="https://github.com/idootop/mi-gpt/assets/35302658/b8c75edb-88aa-4cdd-a21e-5c4bd7908b22">

**Comment by romantech** [comment]
看来得换个音箱了 😭
谢谢回复。
