### ISSUE TITLE
Open AI ❌ LLM 响应异常 NotFoundError: 404 The model `gpt-4o` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by ryanlxb** [idootop/mi-gpt#94]
RUN起来之后，与小爱交互报这个错误：
Open AI ❌ LLM 响应异常 NotFoundError: 404 The model `gpt-4o` does not exist or you do not have access to it.

拼写上应该没错呀，是否还需要再 https://platform.openai.com上对 bot类型service account 进行其它设置么？

不太懂，求教。

**Comment by ryanlxb** [comment]
可能我理解错了，是不是通过api形式调用收费的原因，导致我调用失败了呢

**Comment by idootop** [comment]
应该是的，看上去是你的这个账号没有使用 gpt-4 系列模型的权限，应该和你没充钱有关，哈哈。
