### ISSUE TITLE
Mi-GPT docker后台挂起时 超时报错 会产生巨量日志，无自动清理机制

### ISSUE THREAD

**Issue by wt666666** [idootop/mi-gpt#95]
玩客云装的Docker，闪存较小，第一次装完项目，被干爆了也不知道因为啥~
又重新刷了系统，这眼看着又要被干爆了，经过一番艰苦的排查，发现Mi-GPT后台挂起时，会超时报错，日志 正在几百兆上G的增加着~
来看看这几百兆的日志长啥样~发邮箱了

![Screenshot_3](https://github.com/idootop/mi-gpt/assets/39096045/653f3c2c-560f-44aa-a52b-2f00da88cefa)

![Screenshot_6](https://github.com/idootop/mi-gpt/assets/39096045/c0460662-4bcf-4c73-99c1-97e98746d13e)

![Screenshot_5](https://github.com/idootop/mi-gpt/assets/39096045/72f13cdb-d254-47e4-8ae6-6e7dcded4225)

**Comment by idootop** [comment]
新版本已经修复这个问题了，下个版本更新

**Comment by idootop** [comment]
MiGPT [v4.0.0](https://github.com/idootop/mi-gpt/releases/tag/v4.0.0) 版本已发布
