### ISSUE TITLE
支持通义千问了吗？

### ISSUE THREAD

**Issue by kkkn2024** [idootop/mi-gpt#97]
OPENAI_BASE_URL修改成`https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation`，OPENAI_API_KEY使用通义的key，报错了

![图片](https://github.com/idootop/mi-gpt/assets/19164121/3f8357e1-977f-47ca-9898-469ebd81c8ef)

**Comment by momoq** [comment]
我也是一样的问题

**Comment by momoq** [comment]
我怀疑是没有授权的原因，它不能直接通过API调用，而要通过业务空间授权
![image](https://github.com/idootop/mi-gpt/assets/16385764/c3ff4673-7dd6-4c66-bbab-2c584aa7f2a6)

**Comment by wt666666** [comment]
> OPENAI_BASE_URL修改成`https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation`，OPENAI_API_KEY使用通义的key，报错了
> 
> ![图片](https://private-user-images.githubusercontent.com/19164121/340091534-3f8357e1-977f-47ca-9898-469ebd81c8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDgwMzUsIm5iZiI6MTcxODU0NzczNSwicGF0aCI6Ii8xOTE2NDEyMS8zNDAwOTE1MzQtM2Y4MzU3ZTEtOTc3Zi00N2NhLTk4OTgtNDY5ZWJkODFjOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE0MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzliZDRjZTJmNTk4YWQwZjZkNGMwYTAwZGFlMzE4NmRjZTMxZmQyZDEzNjM5MGJjMGY1ZWNhMjViNDA3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qRHp2w0gUkFtflymyEjlsFTMaLwA8b1XkQ9l4qNfGvA)

URL写多了吧？
https://dashscope.aliyuncs.com/api/v1/ 到这儿就可以了吧，，

**Comment by idootop** [comment]
@kkkn2024 @momoq  楼上正解，请仔细阅读通义千问的官方使用文档：https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/?spm=a2c4g.11186623.0.i1

![telegram-cloud-photo-size-5-6305298911979486979-y](https://github.com/idootop/mi-gpt/assets/35302658/380da137-7135-4dca-9f62-7719f2b1a4ef)
