### ISSUE TITLE
月之暗面，deepseek等AI的API应该怎么设置？

### ISSUE THREAD

**Issue by longwangjiang** [idootop/mi-gpt#98]
月之暗面，deepseek等AI的API应该怎么设置？没有变量呀，我把openai的参数改成deepseek的不行。

**Comment by wt666666** [comment]
> 月之暗面，deepseek等AI的API应该怎么设置？没有变量呀，我把openai的参数改成deepseek的不行。

我用的deepseek，按API文档上写就行啊，，，

![image](https://github.com/idootop/mi-gpt/assets/39096045/f33682a6-9a54-46e1-8cb7-29a40047298e)

**Comment by idootop** [comment]
<img width="1069" alt="image" src="https://github.com/idootop/mi-gpt/assets/35302658/ce1e4849-de2d-4ad2-ab58-7d1a8a227fa3">
