### ISSUE TITLE
为什么一定要小爱音箱，别的不行吗

### ISSUE THREAD

**Issue by wang-xin-yuan-001** [idootop/mi-gpt#99]

**Comment by Star-ZER0** [comment]
你送个高级点的音箱给开发者就给你适配了👍

**Comment by idootop** [comment]
1. 我本人用的就是小爱音箱Pro
2. 我手上只有小爱音箱设备可供测试
3. 最重要的，其他的智能音响设备并没有小爱同学和米家这样的开放能力接口，理论上适配不了
